// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CLIENT_H_
#define FLATBUFFERS_GENERATED_CLIENT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

struct ClientHeartbeat;
struct ClientHeartbeatBuilder;

struct ClientInScene;
struct ClientInSceneBuilder;

struct ClientOutScene;
struct ClientOutSceneBuilder;

struct ClientExit;
struct ClientExitBuilder;

struct ClientHeroMove;
struct ClientHeroMoveBuilder;

struct ClientHeroGoal;
struct ClientHeroGoalBuilder;

struct ClientHeroTeleport;
struct ClientHeroTeleportBuilder;

struct ClientHeroRecruit;
struct ClientHeroRecruitBuilder;

struct ClientHeroDismiss;
struct ClientHeroDismissBuilder;

struct ClientHeroEquip;
struct ClientHeroEquipBuilder;

struct ClientHeroAdvBonuse;
struct ClientHeroAdvBonuseBuilder;

struct ClientHeroCreature;
struct ClientHeroCreatureBuilder;

struct ClientTownCreature;
struct ClientTownCreatureBuilder;

struct ClientDwe;
struct ClientDweBuilder;

struct ClientTownBuild;
struct ClientTownBuildBuilder;

struct ClientEndTurn;
struct ClientEndTurnBuilder;

struct ClientHeartbeat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientHeartbeatBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_TIME = 4
  };
  uint64_t client_time() const {
    return GetField<uint64_t>(VT_CLIENT_TIME, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_TIME, 8) &&
           verifier.EndTable();
  }
};

struct ClientHeartbeatBuilder {
  typedef ClientHeartbeat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_time(uint64_t client_time) {
    fbb_.AddElement<uint64_t>(ClientHeartbeat::VT_CLIENT_TIME, client_time, 0);
  }
  explicit ClientHeartbeatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientHeartbeat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientHeartbeat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientHeartbeat> CreateClientHeartbeat(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t client_time = 0) {
  ClientHeartbeatBuilder builder_(_fbb);
  builder_.add_client_time(client_time);
  return builder_.Finish();
}

struct ClientInScene FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientInSceneBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SCENE_ID = 4
  };
  uint32_t scene_id() const {
    return GetField<uint32_t>(VT_SCENE_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SCENE_ID, 4) &&
           verifier.EndTable();
  }
};

struct ClientInSceneBuilder {
  typedef ClientInScene Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_scene_id(uint32_t scene_id) {
    fbb_.AddElement<uint32_t>(ClientInScene::VT_SCENE_ID, scene_id, 0);
  }
  explicit ClientInSceneBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientInScene> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientInScene>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientInScene> CreateClientInScene(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t scene_id = 0) {
  ClientInSceneBuilder builder_(_fbb);
  builder_.add_scene_id(scene_id);
  return builder_.Finish();
}

struct ClientOutScene FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientOutSceneBuilder Builder;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct ClientOutSceneBuilder {
  typedef ClientOutScene Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit ClientOutSceneBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientOutScene> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientOutScene>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientOutScene> CreateClientOutScene(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  ClientOutSceneBuilder builder_(_fbb);
  return builder_.Finish();
}

struct ClientExit FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientExitBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_ID = 4
  };
  uint64_t client_id() const {
    return GetField<uint64_t>(VT_CLIENT_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_ID, 8) &&
           verifier.EndTable();
  }
};

struct ClientExitBuilder {
  typedef ClientExit Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_id(uint64_t client_id) {
    fbb_.AddElement<uint64_t>(ClientExit::VT_CLIENT_ID, client_id, 0);
  }
  explicit ClientExitBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientExit> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientExit>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientExit> CreateClientExit(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t client_id = 0) {
  ClientExitBuilder builder_(_fbb);
  builder_.add_client_id(client_id);
  return builder_.Finish();
}

struct ClientHeroMove FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientHeroMoveBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POR = 4,
    VT_LEVEL = 6,
    VT_X = 8,
    VT_Y = 10
  };
  uint8_t por() const {
    return GetField<uint8_t>(VT_POR, 0);
  }
  uint8_t level() const {
    return GetField<uint8_t>(VT_LEVEL, 0);
  }
  uint8_t x() const {
    return GetField<uint8_t>(VT_X, 0);
  }
  uint8_t y() const {
    return GetField<uint8_t>(VT_Y, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_POR, 1) &&
           VerifyField<uint8_t>(verifier, VT_LEVEL, 1) &&
           VerifyField<uint8_t>(verifier, VT_X, 1) &&
           VerifyField<uint8_t>(verifier, VT_Y, 1) &&
           verifier.EndTable();
  }
};

struct ClientHeroMoveBuilder {
  typedef ClientHeroMove Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_por(uint8_t por) {
    fbb_.AddElement<uint8_t>(ClientHeroMove::VT_POR, por, 0);
  }
  void add_level(uint8_t level) {
    fbb_.AddElement<uint8_t>(ClientHeroMove::VT_LEVEL, level, 0);
  }
  void add_x(uint8_t x) {
    fbb_.AddElement<uint8_t>(ClientHeroMove::VT_X, x, 0);
  }
  void add_y(uint8_t y) {
    fbb_.AddElement<uint8_t>(ClientHeroMove::VT_Y, y, 0);
  }
  explicit ClientHeroMoveBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientHeroMove> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientHeroMove>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientHeroMove> CreateClientHeroMove(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t por = 0,
    uint8_t level = 0,
    uint8_t x = 0,
    uint8_t y = 0) {
  ClientHeroMoveBuilder builder_(_fbb);
  builder_.add_y(y);
  builder_.add_x(x);
  builder_.add_level(level);
  builder_.add_por(por);
  return builder_.Finish();
}

struct ClientHeroGoal FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientHeroGoalBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POR = 4,
    VT_TYPE = 6,
    VT_LEVEL = 8,
    VT_X = 10,
    VT_Y = 12
  };
  uint8_t por() const {
    return GetField<uint8_t>(VT_POR, 0);
  }
  uint8_t type() const {
    return GetField<uint8_t>(VT_TYPE, 0);
  }
  uint8_t level() const {
    return GetField<uint8_t>(VT_LEVEL, 0);
  }
  uint8_t x() const {
    return GetField<uint8_t>(VT_X, 0);
  }
  uint8_t y() const {
    return GetField<uint8_t>(VT_Y, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_POR, 1) &&
           VerifyField<uint8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<uint8_t>(verifier, VT_LEVEL, 1) &&
           VerifyField<uint8_t>(verifier, VT_X, 1) &&
           VerifyField<uint8_t>(verifier, VT_Y, 1) &&
           verifier.EndTable();
  }
};

struct ClientHeroGoalBuilder {
  typedef ClientHeroGoal Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_por(uint8_t por) {
    fbb_.AddElement<uint8_t>(ClientHeroGoal::VT_POR, por, 0);
  }
  void add_type(uint8_t type) {
    fbb_.AddElement<uint8_t>(ClientHeroGoal::VT_TYPE, type, 0);
  }
  void add_level(uint8_t level) {
    fbb_.AddElement<uint8_t>(ClientHeroGoal::VT_LEVEL, level, 0);
  }
  void add_x(uint8_t x) {
    fbb_.AddElement<uint8_t>(ClientHeroGoal::VT_X, x, 0);
  }
  void add_y(uint8_t y) {
    fbb_.AddElement<uint8_t>(ClientHeroGoal::VT_Y, y, 0);
  }
  explicit ClientHeroGoalBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientHeroGoal> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientHeroGoal>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientHeroGoal> CreateClientHeroGoal(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t por = 0,
    uint8_t type = 0,
    uint8_t level = 0,
    uint8_t x = 0,
    uint8_t y = 0) {
  ClientHeroGoalBuilder builder_(_fbb);
  builder_.add_y(y);
  builder_.add_x(x);
  builder_.add_level(level);
  builder_.add_type(type);
  builder_.add_por(por);
  return builder_.Finish();
}

struct ClientHeroTeleport FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientHeroTeleportBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POR = 4,
    VT_LEVEL = 6,
    VT_X = 8,
    VT_Y = 10
  };
  uint8_t por() const {
    return GetField<uint8_t>(VT_POR, 0);
  }
  uint8_t level() const {
    return GetField<uint8_t>(VT_LEVEL, 0);
  }
  uint8_t x() const {
    return GetField<uint8_t>(VT_X, 0);
  }
  uint8_t y() const {
    return GetField<uint8_t>(VT_Y, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_POR, 1) &&
           VerifyField<uint8_t>(verifier, VT_LEVEL, 1) &&
           VerifyField<uint8_t>(verifier, VT_X, 1) &&
           VerifyField<uint8_t>(verifier, VT_Y, 1) &&
           verifier.EndTable();
  }
};

struct ClientHeroTeleportBuilder {
  typedef ClientHeroTeleport Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_por(uint8_t por) {
    fbb_.AddElement<uint8_t>(ClientHeroTeleport::VT_POR, por, 0);
  }
  void add_level(uint8_t level) {
    fbb_.AddElement<uint8_t>(ClientHeroTeleport::VT_LEVEL, level, 0);
  }
  void add_x(uint8_t x) {
    fbb_.AddElement<uint8_t>(ClientHeroTeleport::VT_X, x, 0);
  }
  void add_y(uint8_t y) {
    fbb_.AddElement<uint8_t>(ClientHeroTeleport::VT_Y, y, 0);
  }
  explicit ClientHeroTeleportBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientHeroTeleport> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientHeroTeleport>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientHeroTeleport> CreateClientHeroTeleport(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t por = 0,
    uint8_t level = 0,
    uint8_t x = 0,
    uint8_t y = 0) {
  ClientHeroTeleportBuilder builder_(_fbb);
  builder_.add_y(y);
  builder_.add_x(x);
  builder_.add_level(level);
  builder_.add_por(por);
  return builder_.Finish();
}

struct ClientHeroRecruit FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientHeroRecruitBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POR = 4,
    VT_LEVEL = 6,
    VT_X = 8,
    VT_Y = 10
  };
  uint8_t por() const {
    return GetField<uint8_t>(VT_POR, 0);
  }
  uint8_t level() const {
    return GetField<uint8_t>(VT_LEVEL, 0);
  }
  uint8_t x() const {
    return GetField<uint8_t>(VT_X, 0);
  }
  uint8_t y() const {
    return GetField<uint8_t>(VT_Y, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_POR, 1) &&
           VerifyField<uint8_t>(verifier, VT_LEVEL, 1) &&
           VerifyField<uint8_t>(verifier, VT_X, 1) &&
           VerifyField<uint8_t>(verifier, VT_Y, 1) &&
           verifier.EndTable();
  }
};

struct ClientHeroRecruitBuilder {
  typedef ClientHeroRecruit Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_por(uint8_t por) {
    fbb_.AddElement<uint8_t>(ClientHeroRecruit::VT_POR, por, 0);
  }
  void add_level(uint8_t level) {
    fbb_.AddElement<uint8_t>(ClientHeroRecruit::VT_LEVEL, level, 0);
  }
  void add_x(uint8_t x) {
    fbb_.AddElement<uint8_t>(ClientHeroRecruit::VT_X, x, 0);
  }
  void add_y(uint8_t y) {
    fbb_.AddElement<uint8_t>(ClientHeroRecruit::VT_Y, y, 0);
  }
  explicit ClientHeroRecruitBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientHeroRecruit> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientHeroRecruit>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientHeroRecruit> CreateClientHeroRecruit(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t por = 0,
    uint8_t level = 0,
    uint8_t x = 0,
    uint8_t y = 0) {
  ClientHeroRecruitBuilder builder_(_fbb);
  builder_.add_y(y);
  builder_.add_x(x);
  builder_.add_level(level);
  builder_.add_por(por);
  return builder_.Finish();
}

struct ClientHeroDismiss FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientHeroDismissBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POR = 4
  };
  uint8_t por() const {
    return GetField<uint8_t>(VT_POR, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_POR, 1) &&
           verifier.EndTable();
  }
};

struct ClientHeroDismissBuilder {
  typedef ClientHeroDismiss Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_por(uint8_t por) {
    fbb_.AddElement<uint8_t>(ClientHeroDismiss::VT_POR, por, 0);
  }
  explicit ClientHeroDismissBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientHeroDismiss> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientHeroDismiss>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientHeroDismiss> CreateClientHeroDismiss(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t por = 0) {
  ClientHeroDismissBuilder builder_(_fbb);
  builder_.add_por(por);
  return builder_.Finish();
}

struct ClientHeroEquip FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientHeroEquipBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POR = 4,
    VT_EQUIP_SLOT = 6,
    VT_BACK_INDEX = 8
  };
  uint8_t por() const {
    return GetField<uint8_t>(VT_POR, 0);
  }
  uint8_t equip_slot() const {
    return GetField<uint8_t>(VT_EQUIP_SLOT, 0);
  }
  uint8_t back_index() const {
    return GetField<uint8_t>(VT_BACK_INDEX, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_POR, 1) &&
           VerifyField<uint8_t>(verifier, VT_EQUIP_SLOT, 1) &&
           VerifyField<uint8_t>(verifier, VT_BACK_INDEX, 1) &&
           verifier.EndTable();
  }
};

struct ClientHeroEquipBuilder {
  typedef ClientHeroEquip Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_por(uint8_t por) {
    fbb_.AddElement<uint8_t>(ClientHeroEquip::VT_POR, por, 0);
  }
  void add_equip_slot(uint8_t equip_slot) {
    fbb_.AddElement<uint8_t>(ClientHeroEquip::VT_EQUIP_SLOT, equip_slot, 0);
  }
  void add_back_index(uint8_t back_index) {
    fbb_.AddElement<uint8_t>(ClientHeroEquip::VT_BACK_INDEX, back_index, 0);
  }
  explicit ClientHeroEquipBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientHeroEquip> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientHeroEquip>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientHeroEquip> CreateClientHeroEquip(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t por = 0,
    uint8_t equip_slot = 0,
    uint8_t back_index = 0) {
  ClientHeroEquipBuilder builder_(_fbb);
  builder_.add_back_index(back_index);
  builder_.add_equip_slot(equip_slot);
  builder_.add_por(por);
  return builder_.Finish();
}

struct ClientHeroAdvBonuse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientHeroAdvBonuseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INDEX = 4,
    VT_POR = 6,
    VT_SRC = 8,
    VT_TYPE = 10,
    VT_SUB_TYPE = 12,
    VT_VAL = 14
  };
  uint32_t index() const {
    return GetField<uint32_t>(VT_INDEX, 0);
  }
  uint8_t por() const {
    return GetField<uint8_t>(VT_POR, 0);
  }
  uint8_t src() const {
    return GetField<uint8_t>(VT_SRC, 0);
  }
  uint8_t type() const {
    return GetField<uint8_t>(VT_TYPE, 0);
  }
  uint8_t sub_type() const {
    return GetField<uint8_t>(VT_SUB_TYPE, 0);
  }
  uint8_t val() const {
    return GetField<uint8_t>(VT_VAL, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_INDEX, 4) &&
           VerifyField<uint8_t>(verifier, VT_POR, 1) &&
           VerifyField<uint8_t>(verifier, VT_SRC, 1) &&
           VerifyField<uint8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<uint8_t>(verifier, VT_SUB_TYPE, 1) &&
           VerifyField<uint8_t>(verifier, VT_VAL, 1) &&
           verifier.EndTable();
  }
};

struct ClientHeroAdvBonuseBuilder {
  typedef ClientHeroAdvBonuse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_index(uint32_t index) {
    fbb_.AddElement<uint32_t>(ClientHeroAdvBonuse::VT_INDEX, index, 0);
  }
  void add_por(uint8_t por) {
    fbb_.AddElement<uint8_t>(ClientHeroAdvBonuse::VT_POR, por, 0);
  }
  void add_src(uint8_t src) {
    fbb_.AddElement<uint8_t>(ClientHeroAdvBonuse::VT_SRC, src, 0);
  }
  void add_type(uint8_t type) {
    fbb_.AddElement<uint8_t>(ClientHeroAdvBonuse::VT_TYPE, type, 0);
  }
  void add_sub_type(uint8_t sub_type) {
    fbb_.AddElement<uint8_t>(ClientHeroAdvBonuse::VT_SUB_TYPE, sub_type, 0);
  }
  void add_val(uint8_t val) {
    fbb_.AddElement<uint8_t>(ClientHeroAdvBonuse::VT_VAL, val, 0);
  }
  explicit ClientHeroAdvBonuseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientHeroAdvBonuse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientHeroAdvBonuse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientHeroAdvBonuse> CreateClientHeroAdvBonuse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t index = 0,
    uint8_t por = 0,
    uint8_t src = 0,
    uint8_t type = 0,
    uint8_t sub_type = 0,
    uint8_t val = 0) {
  ClientHeroAdvBonuseBuilder builder_(_fbb);
  builder_.add_index(index);
  builder_.add_val(val);
  builder_.add_sub_type(sub_type);
  builder_.add_type(type);
  builder_.add_src(src);
  builder_.add_por(por);
  return builder_.Finish();
}

struct ClientHeroCreature FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientHeroCreatureBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POR = 4,
    VT_CREATURE_ID = 6,
    VT_CREATURE_NUM = 8
  };
  uint8_t por() const {
    return GetField<uint8_t>(VT_POR, 0);
  }
  const ::flatbuffers::Vector<uint16_t> *creature_id() const {
    return GetPointer<const ::flatbuffers::Vector<uint16_t> *>(VT_CREATURE_ID);
  }
  const ::flatbuffers::Vector<uint32_t> *creature_num() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_CREATURE_NUM);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_POR, 1) &&
           VerifyOffset(verifier, VT_CREATURE_ID) &&
           verifier.VerifyVector(creature_id()) &&
           VerifyOffset(verifier, VT_CREATURE_NUM) &&
           verifier.VerifyVector(creature_num()) &&
           verifier.EndTable();
  }
};

struct ClientHeroCreatureBuilder {
  typedef ClientHeroCreature Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_por(uint8_t por) {
    fbb_.AddElement<uint8_t>(ClientHeroCreature::VT_POR, por, 0);
  }
  void add_creature_id(::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> creature_id) {
    fbb_.AddOffset(ClientHeroCreature::VT_CREATURE_ID, creature_id);
  }
  void add_creature_num(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> creature_num) {
    fbb_.AddOffset(ClientHeroCreature::VT_CREATURE_NUM, creature_num);
  }
  explicit ClientHeroCreatureBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientHeroCreature> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientHeroCreature>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientHeroCreature> CreateClientHeroCreature(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t por = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> creature_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> creature_num = 0) {
  ClientHeroCreatureBuilder builder_(_fbb);
  builder_.add_creature_num(creature_num);
  builder_.add_creature_id(creature_id);
  builder_.add_por(por);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ClientHeroCreature> CreateClientHeroCreatureDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t por = 0,
    const std::vector<uint16_t> *creature_id = nullptr,
    const std::vector<uint32_t> *creature_num = nullptr) {
  auto creature_id__ = creature_id ? _fbb.CreateVector<uint16_t>(*creature_id) : 0;
  auto creature_num__ = creature_num ? _fbb.CreateVector<uint32_t>(*creature_num) : 0;
  return CreateClientHeroCreature(
      _fbb,
      por,
      creature_id__,
      creature_num__);
}

struct ClientTownCreature FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientTownCreatureBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POR = 4,
    VT_CREATURE_ID = 6,
    VT_CREATURE_NUM = 8
  };
  uint8_t por() const {
    return GetField<uint8_t>(VT_POR, 0);
  }
  const ::flatbuffers::Vector<uint16_t> *creature_id() const {
    return GetPointer<const ::flatbuffers::Vector<uint16_t> *>(VT_CREATURE_ID);
  }
  const ::flatbuffers::Vector<uint32_t> *creature_num() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_CREATURE_NUM);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_POR, 1) &&
           VerifyOffset(verifier, VT_CREATURE_ID) &&
           verifier.VerifyVector(creature_id()) &&
           VerifyOffset(verifier, VT_CREATURE_NUM) &&
           verifier.VerifyVector(creature_num()) &&
           verifier.EndTable();
  }
};

struct ClientTownCreatureBuilder {
  typedef ClientTownCreature Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_por(uint8_t por) {
    fbb_.AddElement<uint8_t>(ClientTownCreature::VT_POR, por, 0);
  }
  void add_creature_id(::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> creature_id) {
    fbb_.AddOffset(ClientTownCreature::VT_CREATURE_ID, creature_id);
  }
  void add_creature_num(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> creature_num) {
    fbb_.AddOffset(ClientTownCreature::VT_CREATURE_NUM, creature_num);
  }
  explicit ClientTownCreatureBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientTownCreature> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientTownCreature>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientTownCreature> CreateClientTownCreature(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t por = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> creature_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> creature_num = 0) {
  ClientTownCreatureBuilder builder_(_fbb);
  builder_.add_creature_num(creature_num);
  builder_.add_creature_id(creature_id);
  builder_.add_por(por);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ClientTownCreature> CreateClientTownCreatureDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t por = 0,
    const std::vector<uint16_t> *creature_id = nullptr,
    const std::vector<uint32_t> *creature_num = nullptr) {
  auto creature_id__ = creature_id ? _fbb.CreateVector<uint16_t>(*creature_id) : 0;
  auto creature_num__ = creature_num ? _fbb.CreateVector<uint32_t>(*creature_num) : 0;
  return CreateClientTownCreature(
      _fbb,
      por,
      creature_id__,
      creature_num__);
}

struct ClientDwe FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientDweBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INDEX = 4,
    VT_BUILD_ID = 6,
    VT_CREATURE_ID = 8,
    VT_CREATURE_NUM = 10
  };
  uint32_t index() const {
    return GetField<uint32_t>(VT_INDEX, 0);
  }
  uint8_t build_id() const {
    return GetField<uint8_t>(VT_BUILD_ID, 0);
  }
  const ::flatbuffers::Vector<uint16_t> *creature_id() const {
    return GetPointer<const ::flatbuffers::Vector<uint16_t> *>(VT_CREATURE_ID);
  }
  const ::flatbuffers::Vector<uint32_t> *creature_num() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_CREATURE_NUM);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_INDEX, 4) &&
           VerifyField<uint8_t>(verifier, VT_BUILD_ID, 1) &&
           VerifyOffset(verifier, VT_CREATURE_ID) &&
           verifier.VerifyVector(creature_id()) &&
           VerifyOffset(verifier, VT_CREATURE_NUM) &&
           verifier.VerifyVector(creature_num()) &&
           verifier.EndTable();
  }
};

struct ClientDweBuilder {
  typedef ClientDwe Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_index(uint32_t index) {
    fbb_.AddElement<uint32_t>(ClientDwe::VT_INDEX, index, 0);
  }
  void add_build_id(uint8_t build_id) {
    fbb_.AddElement<uint8_t>(ClientDwe::VT_BUILD_ID, build_id, 0);
  }
  void add_creature_id(::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> creature_id) {
    fbb_.AddOffset(ClientDwe::VT_CREATURE_ID, creature_id);
  }
  void add_creature_num(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> creature_num) {
    fbb_.AddOffset(ClientDwe::VT_CREATURE_NUM, creature_num);
  }
  explicit ClientDweBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientDwe> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientDwe>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientDwe> CreateClientDwe(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t index = 0,
    uint8_t build_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> creature_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> creature_num = 0) {
  ClientDweBuilder builder_(_fbb);
  builder_.add_creature_num(creature_num);
  builder_.add_creature_id(creature_id);
  builder_.add_index(index);
  builder_.add_build_id(build_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ClientDwe> CreateClientDweDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t index = 0,
    uint8_t build_id = 0,
    const std::vector<uint16_t> *creature_id = nullptr,
    const std::vector<uint32_t> *creature_num = nullptr) {
  auto creature_id__ = creature_id ? _fbb.CreateVector<uint16_t>(*creature_id) : 0;
  auto creature_num__ = creature_num ? _fbb.CreateVector<uint32_t>(*creature_num) : 0;
  return CreateClientDwe(
      _fbb,
      index,
      build_id,
      creature_id__,
      creature_num__);
}

struct ClientTownBuild FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientTownBuildBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INDEX = 4,
    VT_BUILD_ID = 6
  };
  uint32_t index() const {
    return GetField<uint32_t>(VT_INDEX, 0);
  }
  uint8_t build_id() const {
    return GetField<uint8_t>(VT_BUILD_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_INDEX, 4) &&
           VerifyField<uint8_t>(verifier, VT_BUILD_ID, 1) &&
           verifier.EndTable();
  }
};

struct ClientTownBuildBuilder {
  typedef ClientTownBuild Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_index(uint32_t index) {
    fbb_.AddElement<uint32_t>(ClientTownBuild::VT_INDEX, index, 0);
  }
  void add_build_id(uint8_t build_id) {
    fbb_.AddElement<uint8_t>(ClientTownBuild::VT_BUILD_ID, build_id, 0);
  }
  explicit ClientTownBuildBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientTownBuild> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientTownBuild>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientTownBuild> CreateClientTownBuild(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t index = 0,
    uint8_t build_id = 0) {
  ClientTownBuildBuilder builder_(_fbb);
  builder_.add_index(index);
  builder_.add_build_id(build_id);
  return builder_.Finish();
}

struct ClientEndTurn FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientEndTurnBuilder Builder;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct ClientEndTurnBuilder {
  typedef ClientEndTurn Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit ClientEndTurnBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientEndTurn> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientEndTurn>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientEndTurn> CreateClientEndTurn(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  ClientEndTurnBuilder builder_(_fbb);
  return builder_.Finish();
}

#endif  // FLATBUFFERS_GENERATED_CLIENT_H_
