// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CLIENT_H_
#define FLATBUFFERS_GENERATED_CLIENT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

struct ClientHeartbeat;
struct ClientHeartbeatBuilder;

struct ClientLogin;
struct ClientLoginBuilder;

struct ClientInScene;
struct ClientInSceneBuilder;

struct ClientOutScene;
struct ClientOutSceneBuilder;

struct ClientExit;
struct ClientExitBuilder;

struct ClientHeroMove;
struct ClientHeroMoveBuilder;

struct ClientHeroTeleport;
struct ClientHeroTeleportBuilder;

struct ClientHeartbeat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientHeartbeatBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_TIME = 4
  };
  uint64_t client_time() const {
    return GetField<uint64_t>(VT_CLIENT_TIME, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_TIME, 8) &&
           verifier.EndTable();
  }
};

struct ClientHeartbeatBuilder {
  typedef ClientHeartbeat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_time(uint64_t client_time) {
    fbb_.AddElement<uint64_t>(ClientHeartbeat::VT_CLIENT_TIME, client_time, 0);
  }
  explicit ClientHeartbeatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientHeartbeat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientHeartbeat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientHeartbeat> CreateClientHeartbeat(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t client_time = 0) {
  ClientHeartbeatBuilder builder_(_fbb);
  builder_.add_client_time(client_time);
  return builder_.Finish();
}

struct ClientLogin FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientLoginBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_TIME = 4
  };
  uint64_t client_time() const {
    return GetField<uint64_t>(VT_CLIENT_TIME, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_TIME, 8) &&
           verifier.EndTable();
  }
};

struct ClientLoginBuilder {
  typedef ClientLogin Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_time(uint64_t client_time) {
    fbb_.AddElement<uint64_t>(ClientLogin::VT_CLIENT_TIME, client_time, 0);
  }
  explicit ClientLoginBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientLogin> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientLogin>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientLogin> CreateClientLogin(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t client_time = 0) {
  ClientLoginBuilder builder_(_fbb);
  builder_.add_client_time(client_time);
  return builder_.Finish();
}

struct ClientInScene FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientInSceneBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SCENE_ID = 4
  };
  uint32_t scene_id() const {
    return GetField<uint32_t>(VT_SCENE_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SCENE_ID, 4) &&
           verifier.EndTable();
  }
};

struct ClientInSceneBuilder {
  typedef ClientInScene Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_scene_id(uint32_t scene_id) {
    fbb_.AddElement<uint32_t>(ClientInScene::VT_SCENE_ID, scene_id, 0);
  }
  explicit ClientInSceneBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientInScene> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientInScene>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientInScene> CreateClientInScene(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t scene_id = 0) {
  ClientInSceneBuilder builder_(_fbb);
  builder_.add_scene_id(scene_id);
  return builder_.Finish();
}

struct ClientOutScene FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientOutSceneBuilder Builder;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct ClientOutSceneBuilder {
  typedef ClientOutScene Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit ClientOutSceneBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientOutScene> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientOutScene>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientOutScene> CreateClientOutScene(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  ClientOutSceneBuilder builder_(_fbb);
  return builder_.Finish();
}

struct ClientExit FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientExitBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_ID = 4
  };
  uint64_t client_id() const {
    return GetField<uint64_t>(VT_CLIENT_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_ID, 8) &&
           verifier.EndTable();
  }
};

struct ClientExitBuilder {
  typedef ClientExit Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_id(uint64_t client_id) {
    fbb_.AddElement<uint64_t>(ClientExit::VT_CLIENT_ID, client_id, 0);
  }
  explicit ClientExitBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientExit> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientExit>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientExit> CreateClientExit(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t client_id = 0) {
  ClientExitBuilder builder_(_fbb);
  builder_.add_client_id(client_id);
  return builder_.Finish();
}

struct ClientHeroMove FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientHeroMoveBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POR = 4,
    VT_X = 6,
    VT_Y = 8
  };
  uint8_t por() const {
    return GetField<uint8_t>(VT_POR, 0);
  }
  uint8_t x() const {
    return GetField<uint8_t>(VT_X, 0);
  }
  uint8_t y() const {
    return GetField<uint8_t>(VT_Y, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_POR, 1) &&
           VerifyField<uint8_t>(verifier, VT_X, 1) &&
           VerifyField<uint8_t>(verifier, VT_Y, 1) &&
           verifier.EndTable();
  }
};

struct ClientHeroMoveBuilder {
  typedef ClientHeroMove Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_por(uint8_t por) {
    fbb_.AddElement<uint8_t>(ClientHeroMove::VT_POR, por, 0);
  }
  void add_x(uint8_t x) {
    fbb_.AddElement<uint8_t>(ClientHeroMove::VT_X, x, 0);
  }
  void add_y(uint8_t y) {
    fbb_.AddElement<uint8_t>(ClientHeroMove::VT_Y, y, 0);
  }
  explicit ClientHeroMoveBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientHeroMove> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientHeroMove>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientHeroMove> CreateClientHeroMove(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t por = 0,
    uint8_t x = 0,
    uint8_t y = 0) {
  ClientHeroMoveBuilder builder_(_fbb);
  builder_.add_y(y);
  builder_.add_x(x);
  builder_.add_por(por);
  return builder_.Finish();
}

struct ClientHeroTeleport FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientHeroTeleportBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POR = 4,
    VT_LEVEL = 6,
    VT_X = 8,
    VT_Y = 10
  };
  uint8_t por() const {
    return GetField<uint8_t>(VT_POR, 0);
  }
  uint8_t level() const {
    return GetField<uint8_t>(VT_LEVEL, 0);
  }
  uint8_t x() const {
    return GetField<uint8_t>(VT_X, 0);
  }
  uint8_t y() const {
    return GetField<uint8_t>(VT_Y, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_POR, 1) &&
           VerifyField<uint8_t>(verifier, VT_LEVEL, 1) &&
           VerifyField<uint8_t>(verifier, VT_X, 1) &&
           VerifyField<uint8_t>(verifier, VT_Y, 1) &&
           verifier.EndTable();
  }
};

struct ClientHeroTeleportBuilder {
  typedef ClientHeroTeleport Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_por(uint8_t por) {
    fbb_.AddElement<uint8_t>(ClientHeroTeleport::VT_POR, por, 0);
  }
  void add_level(uint8_t level) {
    fbb_.AddElement<uint8_t>(ClientHeroTeleport::VT_LEVEL, level, 0);
  }
  void add_x(uint8_t x) {
    fbb_.AddElement<uint8_t>(ClientHeroTeleport::VT_X, x, 0);
  }
  void add_y(uint8_t y) {
    fbb_.AddElement<uint8_t>(ClientHeroTeleport::VT_Y, y, 0);
  }
  explicit ClientHeroTeleportBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientHeroTeleport> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientHeroTeleport>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientHeroTeleport> CreateClientHeroTeleport(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t por = 0,
    uint8_t level = 0,
    uint8_t x = 0,
    uint8_t y = 0) {
  ClientHeroTeleportBuilder builder_(_fbb);
  builder_.add_y(y);
  builder_.add_x(x);
  builder_.add_level(level);
  builder_.add_por(por);
  return builder_.Finish();
}

#endif  // FLATBUFFERS_GENERATED_CLIENT_H_
