// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PROTOCOL_H_
#define FLATBUFFERS_GENERATED_PROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

struct NetHeartbeat;
struct NetHeartbeatBuilder;

struct NetHeartbeatAck;
struct NetHeartbeatAckBuilder;

struct NetPacket;
struct NetPacketBuilder;

enum NetPacketPayload : uint8_t {
  NetPacketPayload_NONE = 0,
  NetPacketPayload_NetHeartbeat = 1,
  NetPacketPayload_NetHeartbeatAck = 2,
  NetPacketPayload_MIN = NetPacketPayload_NONE,
  NetPacketPayload_MAX = NetPacketPayload_NetHeartbeatAck
};

inline const NetPacketPayload (&EnumValuesNetPacketPayload())[3] {
  static const NetPacketPayload values[] = {
    NetPacketPayload_NONE,
    NetPacketPayload_NetHeartbeat,
    NetPacketPayload_NetHeartbeatAck
  };
  return values;
}

inline const char * const *EnumNamesNetPacketPayload() {
  static const char * const names[4] = {
    "NONE",
    "NetHeartbeat",
    "NetHeartbeatAck",
    nullptr
  };
  return names;
}

inline const char *EnumNameNetPacketPayload(NetPacketPayload e) {
  if (::flatbuffers::IsOutRange(e, NetPacketPayload_NONE, NetPacketPayload_NetHeartbeatAck)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesNetPacketPayload()[index];
}

template<typename T> struct NetPacketPayloadTraits {
  static const NetPacketPayload enum_value = NetPacketPayload_NONE;
};

template<> struct NetPacketPayloadTraits<NetHeartbeat> {
  static const NetPacketPayload enum_value = NetPacketPayload_NetHeartbeat;
};

template<> struct NetPacketPayloadTraits<NetHeartbeatAck> {
  static const NetPacketPayload enum_value = NetPacketPayload_NetHeartbeatAck;
};

template <bool B = false>
bool VerifyNetPacketPayload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, NetPacketPayload type);
template <bool B = false>
bool VerifyNetPacketPayloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct NetHeartbeat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NetHeartbeatBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_TIME = 4
  };
  uint64_t client_time() const {
    return GetField<uint64_t>(VT_CLIENT_TIME, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_TIME, 8) &&
           verifier.EndTable();
  }
};

struct NetHeartbeatBuilder {
  typedef NetHeartbeat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_time(uint64_t client_time) {
    fbb_.AddElement<uint64_t>(NetHeartbeat::VT_CLIENT_TIME, client_time, 0);
  }
  explicit NetHeartbeatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<NetHeartbeat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<NetHeartbeat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<NetHeartbeat> CreateNetHeartbeat(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t client_time = 0) {
  NetHeartbeatBuilder builder_(_fbb);
  builder_.add_client_time(client_time);
  return builder_.Finish();
}

struct NetHeartbeatAck FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NetHeartbeatAckBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SERVER_TIME = 4
  };
  uint64_t server_time() const {
    return GetField<uint64_t>(VT_SERVER_TIME, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_SERVER_TIME, 8) &&
           verifier.EndTable();
  }
};

struct NetHeartbeatAckBuilder {
  typedef NetHeartbeatAck Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_server_time(uint64_t server_time) {
    fbb_.AddElement<uint64_t>(NetHeartbeatAck::VT_SERVER_TIME, server_time, 0);
  }
  explicit NetHeartbeatAckBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<NetHeartbeatAck> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<NetHeartbeatAck>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<NetHeartbeatAck> CreateNetHeartbeatAck(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t server_time = 0) {
  NetHeartbeatAckBuilder builder_(_fbb);
  builder_.add_server_time(server_time);
  return builder_.Finish();
}

struct NetPacket FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NetPacketBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  NetPacketPayload payload_type() const {
    return static_cast<NetPacketPayload>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const NetHeartbeat *payload_as_NetHeartbeat() const {
    return payload_type() == NetPacketPayload_NetHeartbeat ? static_cast<const NetHeartbeat *>(payload()) : nullptr;
  }
  const NetHeartbeatAck *payload_as_NetHeartbeatAck() const {
    return payload_type() == NetPacketPayload_NetHeartbeatAck ? static_cast<const NetHeartbeatAck *>(payload()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyNetPacketPayload(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
};

template<> inline const NetHeartbeat *NetPacket::payload_as<NetHeartbeat>() const {
  return payload_as_NetHeartbeat();
}

template<> inline const NetHeartbeatAck *NetPacket::payload_as<NetHeartbeatAck>() const {
  return payload_as_NetHeartbeatAck();
}

struct NetPacketBuilder {
  typedef NetPacket Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload_type(NetPacketPayload payload_type) {
    fbb_.AddElement<uint8_t>(NetPacket::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(NetPacket::VT_PAYLOAD, payload);
  }
  explicit NetPacketBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<NetPacket> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<NetPacket>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<NetPacket> CreateNetPacket(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    NetPacketPayload payload_type = NetPacketPayload_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  NetPacketBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

template <bool B>
inline bool VerifyNetPacketPayload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, NetPacketPayload type) {
  switch (type) {
    case NetPacketPayload_NONE: {
      return true;
    }
    case NetPacketPayload_NetHeartbeat: {
      auto ptr = reinterpret_cast<const NetHeartbeat *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case NetPacketPayload_NetHeartbeatAck: {
      auto ptr = reinterpret_cast<const NetHeartbeatAck *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyNetPacketPayloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyNetPacketPayload(
        verifier,  values->Get(i), types->GetEnum<NetPacketPayload>(i))) {
      return false;
    }
  }
  return true;
}

inline const NetPacket *GetNetPacket(const void *buf) {
  return ::flatbuffers::GetRoot<NetPacket>(buf);
}

inline const NetPacket *GetSizePrefixedNetPacket(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<NetPacket>(buf);
}

template <bool B = false>
inline bool VerifyNetPacketBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<NetPacket>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedNetPacketBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<NetPacket>(nullptr);
}

inline void FinishNetPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<NetPacket> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedNetPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<NetPacket> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_PROTOCOL_H_
