// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PROTOCOL_H_
#define FLATBUFFERS_GENERATED_PROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "Client.h"
#include "Server.h"

struct NetPacket;
struct NetPacketBuilder;

enum NetPayload : uint8_t {
  NetPayload_NONE = 0,
  NetPayload_ClientHeartbeat = 1,
  NetPayload_ClientInScene = 2,
  NetPayload_ClientOutScene = 3,
  NetPayload_ClientHeroMove = 4,
  NetPayload_ClientHeroGoal = 5,
  NetPayload_ClientHeroTeleport = 6,
  NetPayload_ClientHeroRecruit = 7,
  NetPayload_ClientHeroDismiss = 8,
  NetPayload_ClientEndTurn = 9,
  NetPayload_ServerHeartbeat = 10,
  NetPayload_ServerInScene = 11,
  NetPayload_ServerOutScene = 12,
  NetPayload_ServerHeroMove = 13,
  NetPayload_ServerHeroGoal = 14,
  NetPayload_ServerHeroTeleport = 15,
  NetPayload_ServerHeroRecruit = 16,
  NetPayload_ServerHeroDismiss = 17,
  NetPayload_ServerEndTurn = 18,
  NetPayload_MIN = NetPayload_NONE,
  NetPayload_MAX = NetPayload_ServerEndTurn
};

inline const NetPayload (&EnumValuesNetPayload())[19] {
  static const NetPayload values[] = {
    NetPayload_NONE,
    NetPayload_ClientHeartbeat,
    NetPayload_ClientInScene,
    NetPayload_ClientOutScene,
    NetPayload_ClientHeroMove,
    NetPayload_ClientHeroGoal,
    NetPayload_ClientHeroTeleport,
    NetPayload_ClientHeroRecruit,
    NetPayload_ClientHeroDismiss,
    NetPayload_ClientEndTurn,
    NetPayload_ServerHeartbeat,
    NetPayload_ServerInScene,
    NetPayload_ServerOutScene,
    NetPayload_ServerHeroMove,
    NetPayload_ServerHeroGoal,
    NetPayload_ServerHeroTeleport,
    NetPayload_ServerHeroRecruit,
    NetPayload_ServerHeroDismiss,
    NetPayload_ServerEndTurn
  };
  return values;
}

inline const char * const *EnumNamesNetPayload() {
  static const char * const names[20] = {
    "NONE",
    "ClientHeartbeat",
    "ClientInScene",
    "ClientOutScene",
    "ClientHeroMove",
    "ClientHeroGoal",
    "ClientHeroTeleport",
    "ClientHeroRecruit",
    "ClientHeroDismiss",
    "ClientEndTurn",
    "ServerHeartbeat",
    "ServerInScene",
    "ServerOutScene",
    "ServerHeroMove",
    "ServerHeroGoal",
    "ServerHeroTeleport",
    "ServerHeroRecruit",
    "ServerHeroDismiss",
    "ServerEndTurn",
    nullptr
  };
  return names;
}

inline const char *EnumNameNetPayload(NetPayload e) {
  if (::flatbuffers::IsOutRange(e, NetPayload_NONE, NetPayload_ServerEndTurn)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesNetPayload()[index];
}

template<typename T> struct NetPayloadTraits {
  static const NetPayload enum_value = NetPayload_NONE;
};

template<> struct NetPayloadTraits<ClientHeartbeat> {
  static const NetPayload enum_value = NetPayload_ClientHeartbeat;
};

template<> struct NetPayloadTraits<ClientInScene> {
  static const NetPayload enum_value = NetPayload_ClientInScene;
};

template<> struct NetPayloadTraits<ClientOutScene> {
  static const NetPayload enum_value = NetPayload_ClientOutScene;
};

template<> struct NetPayloadTraits<ClientHeroMove> {
  static const NetPayload enum_value = NetPayload_ClientHeroMove;
};

template<> struct NetPayloadTraits<ClientHeroGoal> {
  static const NetPayload enum_value = NetPayload_ClientHeroGoal;
};

template<> struct NetPayloadTraits<ClientHeroTeleport> {
  static const NetPayload enum_value = NetPayload_ClientHeroTeleport;
};

template<> struct NetPayloadTraits<ClientHeroRecruit> {
  static const NetPayload enum_value = NetPayload_ClientHeroRecruit;
};

template<> struct NetPayloadTraits<ClientHeroDismiss> {
  static const NetPayload enum_value = NetPayload_ClientHeroDismiss;
};

template<> struct NetPayloadTraits<ClientEndTurn> {
  static const NetPayload enum_value = NetPayload_ClientEndTurn;
};

template<> struct NetPayloadTraits<ServerHeartbeat> {
  static const NetPayload enum_value = NetPayload_ServerHeartbeat;
};

template<> struct NetPayloadTraits<ServerInScene> {
  static const NetPayload enum_value = NetPayload_ServerInScene;
};

template<> struct NetPayloadTraits<ServerOutScene> {
  static const NetPayload enum_value = NetPayload_ServerOutScene;
};

template<> struct NetPayloadTraits<ServerHeroMove> {
  static const NetPayload enum_value = NetPayload_ServerHeroMove;
};

template<> struct NetPayloadTraits<ServerHeroGoal> {
  static const NetPayload enum_value = NetPayload_ServerHeroGoal;
};

template<> struct NetPayloadTraits<ServerHeroTeleport> {
  static const NetPayload enum_value = NetPayload_ServerHeroTeleport;
};

template<> struct NetPayloadTraits<ServerHeroRecruit> {
  static const NetPayload enum_value = NetPayload_ServerHeroRecruit;
};

template<> struct NetPayloadTraits<ServerHeroDismiss> {
  static const NetPayload enum_value = NetPayload_ServerHeroDismiss;
};

template<> struct NetPayloadTraits<ServerEndTurn> {
  static const NetPayload enum_value = NetPayload_ServerEndTurn;
};

template <bool B = false>
bool VerifyNetPayload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, NetPayload type);
template <bool B = false>
bool VerifyNetPayloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct NetPacket FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NetPacketBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  NetPayload payload_type() const {
    return static_cast<NetPayload>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const ClientHeartbeat *payload_as_ClientHeartbeat() const {
    return payload_type() == NetPayload_ClientHeartbeat ? static_cast<const ClientHeartbeat *>(payload()) : nullptr;
  }
  const ClientInScene *payload_as_ClientInScene() const {
    return payload_type() == NetPayload_ClientInScene ? static_cast<const ClientInScene *>(payload()) : nullptr;
  }
  const ClientOutScene *payload_as_ClientOutScene() const {
    return payload_type() == NetPayload_ClientOutScene ? static_cast<const ClientOutScene *>(payload()) : nullptr;
  }
  const ClientHeroMove *payload_as_ClientHeroMove() const {
    return payload_type() == NetPayload_ClientHeroMove ? static_cast<const ClientHeroMove *>(payload()) : nullptr;
  }
  const ClientHeroGoal *payload_as_ClientHeroGoal() const {
    return payload_type() == NetPayload_ClientHeroGoal ? static_cast<const ClientHeroGoal *>(payload()) : nullptr;
  }
  const ClientHeroTeleport *payload_as_ClientHeroTeleport() const {
    return payload_type() == NetPayload_ClientHeroTeleport ? static_cast<const ClientHeroTeleport *>(payload()) : nullptr;
  }
  const ClientHeroRecruit *payload_as_ClientHeroRecruit() const {
    return payload_type() == NetPayload_ClientHeroRecruit ? static_cast<const ClientHeroRecruit *>(payload()) : nullptr;
  }
  const ClientHeroDismiss *payload_as_ClientHeroDismiss() const {
    return payload_type() == NetPayload_ClientHeroDismiss ? static_cast<const ClientHeroDismiss *>(payload()) : nullptr;
  }
  const ClientEndTurn *payload_as_ClientEndTurn() const {
    return payload_type() == NetPayload_ClientEndTurn ? static_cast<const ClientEndTurn *>(payload()) : nullptr;
  }
  const ServerHeartbeat *payload_as_ServerHeartbeat() const {
    return payload_type() == NetPayload_ServerHeartbeat ? static_cast<const ServerHeartbeat *>(payload()) : nullptr;
  }
  const ServerInScene *payload_as_ServerInScene() const {
    return payload_type() == NetPayload_ServerInScene ? static_cast<const ServerInScene *>(payload()) : nullptr;
  }
  const ServerOutScene *payload_as_ServerOutScene() const {
    return payload_type() == NetPayload_ServerOutScene ? static_cast<const ServerOutScene *>(payload()) : nullptr;
  }
  const ServerHeroMove *payload_as_ServerHeroMove() const {
    return payload_type() == NetPayload_ServerHeroMove ? static_cast<const ServerHeroMove *>(payload()) : nullptr;
  }
  const ServerHeroGoal *payload_as_ServerHeroGoal() const {
    return payload_type() == NetPayload_ServerHeroGoal ? static_cast<const ServerHeroGoal *>(payload()) : nullptr;
  }
  const ServerHeroTeleport *payload_as_ServerHeroTeleport() const {
    return payload_type() == NetPayload_ServerHeroTeleport ? static_cast<const ServerHeroTeleport *>(payload()) : nullptr;
  }
  const ServerHeroRecruit *payload_as_ServerHeroRecruit() const {
    return payload_type() == NetPayload_ServerHeroRecruit ? static_cast<const ServerHeroRecruit *>(payload()) : nullptr;
  }
  const ServerHeroDismiss *payload_as_ServerHeroDismiss() const {
    return payload_type() == NetPayload_ServerHeroDismiss ? static_cast<const ServerHeroDismiss *>(payload()) : nullptr;
  }
  const ServerEndTurn *payload_as_ServerEndTurn() const {
    return payload_type() == NetPayload_ServerEndTurn ? static_cast<const ServerEndTurn *>(payload()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyNetPayload(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
};

template<> inline const ClientHeartbeat *NetPacket::payload_as<ClientHeartbeat>() const {
  return payload_as_ClientHeartbeat();
}

template<> inline const ClientInScene *NetPacket::payload_as<ClientInScene>() const {
  return payload_as_ClientInScene();
}

template<> inline const ClientOutScene *NetPacket::payload_as<ClientOutScene>() const {
  return payload_as_ClientOutScene();
}

template<> inline const ClientHeroMove *NetPacket::payload_as<ClientHeroMove>() const {
  return payload_as_ClientHeroMove();
}

template<> inline const ClientHeroGoal *NetPacket::payload_as<ClientHeroGoal>() const {
  return payload_as_ClientHeroGoal();
}

template<> inline const ClientHeroTeleport *NetPacket::payload_as<ClientHeroTeleport>() const {
  return payload_as_ClientHeroTeleport();
}

template<> inline const ClientHeroRecruit *NetPacket::payload_as<ClientHeroRecruit>() const {
  return payload_as_ClientHeroRecruit();
}

template<> inline const ClientHeroDismiss *NetPacket::payload_as<ClientHeroDismiss>() const {
  return payload_as_ClientHeroDismiss();
}

template<> inline const ClientEndTurn *NetPacket::payload_as<ClientEndTurn>() const {
  return payload_as_ClientEndTurn();
}

template<> inline const ServerHeartbeat *NetPacket::payload_as<ServerHeartbeat>() const {
  return payload_as_ServerHeartbeat();
}

template<> inline const ServerInScene *NetPacket::payload_as<ServerInScene>() const {
  return payload_as_ServerInScene();
}

template<> inline const ServerOutScene *NetPacket::payload_as<ServerOutScene>() const {
  return payload_as_ServerOutScene();
}

template<> inline const ServerHeroMove *NetPacket::payload_as<ServerHeroMove>() const {
  return payload_as_ServerHeroMove();
}

template<> inline const ServerHeroGoal *NetPacket::payload_as<ServerHeroGoal>() const {
  return payload_as_ServerHeroGoal();
}

template<> inline const ServerHeroTeleport *NetPacket::payload_as<ServerHeroTeleport>() const {
  return payload_as_ServerHeroTeleport();
}

template<> inline const ServerHeroRecruit *NetPacket::payload_as<ServerHeroRecruit>() const {
  return payload_as_ServerHeroRecruit();
}

template<> inline const ServerHeroDismiss *NetPacket::payload_as<ServerHeroDismiss>() const {
  return payload_as_ServerHeroDismiss();
}

template<> inline const ServerEndTurn *NetPacket::payload_as<ServerEndTurn>() const {
  return payload_as_ServerEndTurn();
}

struct NetPacketBuilder {
  typedef NetPacket Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload_type(NetPayload payload_type) {
    fbb_.AddElement<uint8_t>(NetPacket::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(NetPacket::VT_PAYLOAD, payload);
  }
  explicit NetPacketBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<NetPacket> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<NetPacket>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<NetPacket> CreateNetPacket(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    NetPayload payload_type = NetPayload_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  NetPacketBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

template <bool B>
inline bool VerifyNetPayload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, NetPayload type) {
  switch (type) {
    case NetPayload_NONE: {
      return true;
    }
    case NetPayload_ClientHeartbeat: {
      auto ptr = reinterpret_cast<const ClientHeartbeat *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case NetPayload_ClientInScene: {
      auto ptr = reinterpret_cast<const ClientInScene *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case NetPayload_ClientOutScene: {
      auto ptr = reinterpret_cast<const ClientOutScene *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case NetPayload_ClientHeroMove: {
      auto ptr = reinterpret_cast<const ClientHeroMove *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case NetPayload_ClientHeroGoal: {
      auto ptr = reinterpret_cast<const ClientHeroGoal *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case NetPayload_ClientHeroTeleport: {
      auto ptr = reinterpret_cast<const ClientHeroTeleport *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case NetPayload_ClientHeroRecruit: {
      auto ptr = reinterpret_cast<const ClientHeroRecruit *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case NetPayload_ClientHeroDismiss: {
      auto ptr = reinterpret_cast<const ClientHeroDismiss *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case NetPayload_ClientEndTurn: {
      auto ptr = reinterpret_cast<const ClientEndTurn *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case NetPayload_ServerHeartbeat: {
      auto ptr = reinterpret_cast<const ServerHeartbeat *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case NetPayload_ServerInScene: {
      auto ptr = reinterpret_cast<const ServerInScene *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case NetPayload_ServerOutScene: {
      auto ptr = reinterpret_cast<const ServerOutScene *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case NetPayload_ServerHeroMove: {
      auto ptr = reinterpret_cast<const ServerHeroMove *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case NetPayload_ServerHeroGoal: {
      auto ptr = reinterpret_cast<const ServerHeroGoal *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case NetPayload_ServerHeroTeleport: {
      auto ptr = reinterpret_cast<const ServerHeroTeleport *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case NetPayload_ServerHeroRecruit: {
      auto ptr = reinterpret_cast<const ServerHeroRecruit *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case NetPayload_ServerHeroDismiss: {
      auto ptr = reinterpret_cast<const ServerHeroDismiss *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case NetPayload_ServerEndTurn: {
      auto ptr = reinterpret_cast<const ServerEndTurn *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyNetPayloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyNetPayload(
        verifier,  values->Get(i), types->GetEnum<NetPayload>(i))) {
      return false;
    }
  }
  return true;
}

inline const NetPacket *GetNetPacket(const void *buf) {
  return ::flatbuffers::GetRoot<NetPacket>(buf);
}

inline const NetPacket *GetSizePrefixedNetPacket(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<NetPacket>(buf);
}

template <bool B = false>
inline bool VerifyNetPacketBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<NetPacket>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedNetPacketBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<NetPacket>(nullptr);
}

inline void FinishNetPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<NetPacket> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedNetPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<NetPacket> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_PROTOCOL_H_
