// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SERVER_H_
#define FLATBUFFERS_GENERATED_SERVER_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

struct ServerHeartbeat;
struct ServerHeartbeatBuilder;

struct ServerLogin;
struct ServerLoginBuilder;

struct ServerInScene;
struct ServerInSceneBuilder;

struct ServerOutScene;
struct ServerOutSceneBuilder;

struct ServerHeroMove;
struct ServerHeroMoveBuilder;

struct ServerHeroGoal;
struct ServerHeroGoalBuilder;

struct ServerHeroTeleport;
struct ServerHeroTeleportBuilder;

struct ServerHeroRecruit;
struct ServerHeroRecruitBuilder;

struct ServerHeroDismiss;
struct ServerHeroDismissBuilder;

struct ServerObjectFade;
struct ServerObjectFadeBuilder;

struct ServerHeartbeat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerHeartbeatBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SERVER_TIME = 4
  };
  uint64_t server_time() const {
    return GetField<uint64_t>(VT_SERVER_TIME, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_SERVER_TIME, 8) &&
           verifier.EndTable();
  }
};

struct ServerHeartbeatBuilder {
  typedef ServerHeartbeat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_server_time(uint64_t server_time) {
    fbb_.AddElement<uint64_t>(ServerHeartbeat::VT_SERVER_TIME, server_time, 0);
  }
  explicit ServerHeartbeatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerHeartbeat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerHeartbeat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerHeartbeat> CreateServerHeartbeat(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t server_time = 0) {
  ServerHeartbeatBuilder builder_(_fbb);
  builder_.add_server_time(server_time);
  return builder_.Finish();
}

struct ServerLogin FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerLoginBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_ID = 4,
    VT_SERVER_TIME = 6
  };
  uint64_t client_id() const {
    return GetField<uint64_t>(VT_CLIENT_ID, 0);
  }
  uint64_t server_time() const {
    return GetField<uint64_t>(VT_SERVER_TIME, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_SERVER_TIME, 8) &&
           verifier.EndTable();
  }
};

struct ServerLoginBuilder {
  typedef ServerLogin Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_id(uint64_t client_id) {
    fbb_.AddElement<uint64_t>(ServerLogin::VT_CLIENT_ID, client_id, 0);
  }
  void add_server_time(uint64_t server_time) {
    fbb_.AddElement<uint64_t>(ServerLogin::VT_SERVER_TIME, server_time, 0);
  }
  explicit ServerLoginBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerLogin> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerLogin>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerLogin> CreateServerLogin(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t client_id = 0,
    uint64_t server_time = 0) {
  ServerLoginBuilder builder_(_fbb);
  builder_.add_server_time(server_time);
  builder_.add_client_id(client_id);
  return builder_.Finish();
}

struct ServerInScene FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerInSceneBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SCENE_HOST = 4,
    VT_SCENE_ID = 6
  };
  uint64_t scene_host() const {
    return GetField<uint64_t>(VT_SCENE_HOST, 0);
  }
  uint32_t scene_id() const {
    return GetField<uint32_t>(VT_SCENE_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_SCENE_HOST, 8) &&
           VerifyField<uint32_t>(verifier, VT_SCENE_ID, 4) &&
           verifier.EndTable();
  }
};

struct ServerInSceneBuilder {
  typedef ServerInScene Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_scene_host(uint64_t scene_host) {
    fbb_.AddElement<uint64_t>(ServerInScene::VT_SCENE_HOST, scene_host, 0);
  }
  void add_scene_id(uint32_t scene_id) {
    fbb_.AddElement<uint32_t>(ServerInScene::VT_SCENE_ID, scene_id, 0);
  }
  explicit ServerInSceneBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerInScene> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerInScene>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerInScene> CreateServerInScene(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t scene_host = 0,
    uint32_t scene_id = 0) {
  ServerInSceneBuilder builder_(_fbb);
  builder_.add_scene_host(scene_host);
  builder_.add_scene_id(scene_id);
  return builder_.Finish();
}

struct ServerOutScene FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerOutSceneBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_ID = 4
  };
  uint64_t client_id() const {
    return GetField<uint64_t>(VT_CLIENT_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_ID, 8) &&
           verifier.EndTable();
  }
};

struct ServerOutSceneBuilder {
  typedef ServerOutScene Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_id(uint64_t client_id) {
    fbb_.AddElement<uint64_t>(ServerOutScene::VT_CLIENT_ID, client_id, 0);
  }
  explicit ServerOutSceneBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerOutScene> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerOutScene>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerOutScene> CreateServerOutScene(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t client_id = 0) {
  ServerOutSceneBuilder builder_(_fbb);
  builder_.add_client_id(client_id);
  return builder_.Finish();
}

struct ServerHeroMove FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerHeroMoveBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POR = 4,
    VT_LEVEL = 6,
    VT_X = 8,
    VT_Y = 10
  };
  uint8_t por() const {
    return GetField<uint8_t>(VT_POR, 0);
  }
  uint8_t level() const {
    return GetField<uint8_t>(VT_LEVEL, 0);
  }
  uint8_t x() const {
    return GetField<uint8_t>(VT_X, 0);
  }
  uint8_t y() const {
    return GetField<uint8_t>(VT_Y, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_POR, 1) &&
           VerifyField<uint8_t>(verifier, VT_LEVEL, 1) &&
           VerifyField<uint8_t>(verifier, VT_X, 1) &&
           VerifyField<uint8_t>(verifier, VT_Y, 1) &&
           verifier.EndTable();
  }
};

struct ServerHeroMoveBuilder {
  typedef ServerHeroMove Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_por(uint8_t por) {
    fbb_.AddElement<uint8_t>(ServerHeroMove::VT_POR, por, 0);
  }
  void add_level(uint8_t level) {
    fbb_.AddElement<uint8_t>(ServerHeroMove::VT_LEVEL, level, 0);
  }
  void add_x(uint8_t x) {
    fbb_.AddElement<uint8_t>(ServerHeroMove::VT_X, x, 0);
  }
  void add_y(uint8_t y) {
    fbb_.AddElement<uint8_t>(ServerHeroMove::VT_Y, y, 0);
  }
  explicit ServerHeroMoveBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerHeroMove> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerHeroMove>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerHeroMove> CreateServerHeroMove(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t por = 0,
    uint8_t level = 0,
    uint8_t x = 0,
    uint8_t y = 0) {
  ServerHeroMoveBuilder builder_(_fbb);
  builder_.add_y(y);
  builder_.add_x(x);
  builder_.add_level(level);
  builder_.add_por(por);
  return builder_.Finish();
}

struct ServerHeroGoal FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerHeroGoalBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POR = 4,
    VT_TYPE = 6,
    VT_LEVEL = 8,
    VT_X = 10,
    VT_Y = 12
  };
  uint8_t por() const {
    return GetField<uint8_t>(VT_POR, 0);
  }
  uint8_t type() const {
    return GetField<uint8_t>(VT_TYPE, 0);
  }
  uint8_t level() const {
    return GetField<uint8_t>(VT_LEVEL, 0);
  }
  uint8_t x() const {
    return GetField<uint8_t>(VT_X, 0);
  }
  uint8_t y() const {
    return GetField<uint8_t>(VT_Y, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_POR, 1) &&
           VerifyField<uint8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<uint8_t>(verifier, VT_LEVEL, 1) &&
           VerifyField<uint8_t>(verifier, VT_X, 1) &&
           VerifyField<uint8_t>(verifier, VT_Y, 1) &&
           verifier.EndTable();
  }
};

struct ServerHeroGoalBuilder {
  typedef ServerHeroGoal Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_por(uint8_t por) {
    fbb_.AddElement<uint8_t>(ServerHeroGoal::VT_POR, por, 0);
  }
  void add_type(uint8_t type) {
    fbb_.AddElement<uint8_t>(ServerHeroGoal::VT_TYPE, type, 0);
  }
  void add_level(uint8_t level) {
    fbb_.AddElement<uint8_t>(ServerHeroGoal::VT_LEVEL, level, 0);
  }
  void add_x(uint8_t x) {
    fbb_.AddElement<uint8_t>(ServerHeroGoal::VT_X, x, 0);
  }
  void add_y(uint8_t y) {
    fbb_.AddElement<uint8_t>(ServerHeroGoal::VT_Y, y, 0);
  }
  explicit ServerHeroGoalBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerHeroGoal> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerHeroGoal>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerHeroGoal> CreateServerHeroGoal(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t por = 0,
    uint8_t type = 0,
    uint8_t level = 0,
    uint8_t x = 0,
    uint8_t y = 0) {
  ServerHeroGoalBuilder builder_(_fbb);
  builder_.add_y(y);
  builder_.add_x(x);
  builder_.add_level(level);
  builder_.add_type(type);
  builder_.add_por(por);
  return builder_.Finish();
}

struct ServerHeroTeleport FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerHeroTeleportBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POR = 4,
    VT_LEVEL = 6,
    VT_X = 8,
    VT_Y = 10
  };
  uint8_t por() const {
    return GetField<uint8_t>(VT_POR, 0);
  }
  uint8_t level() const {
    return GetField<uint8_t>(VT_LEVEL, 0);
  }
  uint8_t x() const {
    return GetField<uint8_t>(VT_X, 0);
  }
  uint8_t y() const {
    return GetField<uint8_t>(VT_Y, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_POR, 1) &&
           VerifyField<uint8_t>(verifier, VT_LEVEL, 1) &&
           VerifyField<uint8_t>(verifier, VT_X, 1) &&
           VerifyField<uint8_t>(verifier, VT_Y, 1) &&
           verifier.EndTable();
  }
};

struct ServerHeroTeleportBuilder {
  typedef ServerHeroTeleport Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_por(uint8_t por) {
    fbb_.AddElement<uint8_t>(ServerHeroTeleport::VT_POR, por, 0);
  }
  void add_level(uint8_t level) {
    fbb_.AddElement<uint8_t>(ServerHeroTeleport::VT_LEVEL, level, 0);
  }
  void add_x(uint8_t x) {
    fbb_.AddElement<uint8_t>(ServerHeroTeleport::VT_X, x, 0);
  }
  void add_y(uint8_t y) {
    fbb_.AddElement<uint8_t>(ServerHeroTeleport::VT_Y, y, 0);
  }
  explicit ServerHeroTeleportBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerHeroTeleport> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerHeroTeleport>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerHeroTeleport> CreateServerHeroTeleport(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t por = 0,
    uint8_t level = 0,
    uint8_t x = 0,
    uint8_t y = 0) {
  ServerHeroTeleportBuilder builder_(_fbb);
  builder_.add_y(y);
  builder_.add_x(x);
  builder_.add_level(level);
  builder_.add_por(por);
  return builder_.Finish();
}

struct ServerHeroRecruit FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerHeroRecruitBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POR = 4,
    VT_LEVEL = 6,
    VT_X = 8,
    VT_Y = 10
  };
  uint8_t por() const {
    return GetField<uint8_t>(VT_POR, 0);
  }
  uint8_t level() const {
    return GetField<uint8_t>(VT_LEVEL, 0);
  }
  uint8_t x() const {
    return GetField<uint8_t>(VT_X, 0);
  }
  uint8_t y() const {
    return GetField<uint8_t>(VT_Y, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_POR, 1) &&
           VerifyField<uint8_t>(verifier, VT_LEVEL, 1) &&
           VerifyField<uint8_t>(verifier, VT_X, 1) &&
           VerifyField<uint8_t>(verifier, VT_Y, 1) &&
           verifier.EndTable();
  }
};

struct ServerHeroRecruitBuilder {
  typedef ServerHeroRecruit Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_por(uint8_t por) {
    fbb_.AddElement<uint8_t>(ServerHeroRecruit::VT_POR, por, 0);
  }
  void add_level(uint8_t level) {
    fbb_.AddElement<uint8_t>(ServerHeroRecruit::VT_LEVEL, level, 0);
  }
  void add_x(uint8_t x) {
    fbb_.AddElement<uint8_t>(ServerHeroRecruit::VT_X, x, 0);
  }
  void add_y(uint8_t y) {
    fbb_.AddElement<uint8_t>(ServerHeroRecruit::VT_Y, y, 0);
  }
  explicit ServerHeroRecruitBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerHeroRecruit> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerHeroRecruit>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerHeroRecruit> CreateServerHeroRecruit(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t por = 0,
    uint8_t level = 0,
    uint8_t x = 0,
    uint8_t y = 0) {
  ServerHeroRecruitBuilder builder_(_fbb);
  builder_.add_y(y);
  builder_.add_x(x);
  builder_.add_level(level);
  builder_.add_por(por);
  return builder_.Finish();
}

struct ServerHeroDismiss FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerHeroDismissBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POR = 4,
    VT_LEVEL = 6,
    VT_X = 8,
    VT_Y = 10
  };
  uint8_t por() const {
    return GetField<uint8_t>(VT_POR, 0);
  }
  uint8_t level() const {
    return GetField<uint8_t>(VT_LEVEL, 0);
  }
  uint8_t x() const {
    return GetField<uint8_t>(VT_X, 0);
  }
  uint8_t y() const {
    return GetField<uint8_t>(VT_Y, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_POR, 1) &&
           VerifyField<uint8_t>(verifier, VT_LEVEL, 1) &&
           VerifyField<uint8_t>(verifier, VT_X, 1) &&
           VerifyField<uint8_t>(verifier, VT_Y, 1) &&
           verifier.EndTable();
  }
};

struct ServerHeroDismissBuilder {
  typedef ServerHeroDismiss Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_por(uint8_t por) {
    fbb_.AddElement<uint8_t>(ServerHeroDismiss::VT_POR, por, 0);
  }
  void add_level(uint8_t level) {
    fbb_.AddElement<uint8_t>(ServerHeroDismiss::VT_LEVEL, level, 0);
  }
  void add_x(uint8_t x) {
    fbb_.AddElement<uint8_t>(ServerHeroDismiss::VT_X, x, 0);
  }
  void add_y(uint8_t y) {
    fbb_.AddElement<uint8_t>(ServerHeroDismiss::VT_Y, y, 0);
  }
  explicit ServerHeroDismissBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerHeroDismiss> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerHeroDismiss>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerHeroDismiss> CreateServerHeroDismiss(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t por = 0,
    uint8_t level = 0,
    uint8_t x = 0,
    uint8_t y = 0) {
  ServerHeroDismissBuilder builder_(_fbb);
  builder_.add_y(y);
  builder_.add_x(x);
  builder_.add_level(level);
  builder_.add_por(por);
  return builder_.Finish();
}

struct ServerObjectFade FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerObjectFadeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_LEVEL = 6,
    VT_X = 8,
    VT_Y = 10
  };
  uint8_t type() const {
    return GetField<uint8_t>(VT_TYPE, 0);
  }
  uint8_t level() const {
    return GetField<uint8_t>(VT_LEVEL, 0);
  }
  uint8_t x() const {
    return GetField<uint8_t>(VT_X, 0);
  }
  uint8_t y() const {
    return GetField<uint8_t>(VT_Y, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<uint8_t>(verifier, VT_LEVEL, 1) &&
           VerifyField<uint8_t>(verifier, VT_X, 1) &&
           VerifyField<uint8_t>(verifier, VT_Y, 1) &&
           verifier.EndTable();
  }
};

struct ServerObjectFadeBuilder {
  typedef ServerObjectFade Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(uint8_t type) {
    fbb_.AddElement<uint8_t>(ServerObjectFade::VT_TYPE, type, 0);
  }
  void add_level(uint8_t level) {
    fbb_.AddElement<uint8_t>(ServerObjectFade::VT_LEVEL, level, 0);
  }
  void add_x(uint8_t x) {
    fbb_.AddElement<uint8_t>(ServerObjectFade::VT_X, x, 0);
  }
  void add_y(uint8_t y) {
    fbb_.AddElement<uint8_t>(ServerObjectFade::VT_Y, y, 0);
  }
  explicit ServerObjectFadeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerObjectFade> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerObjectFade>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerObjectFade> CreateServerObjectFade(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t type = 0,
    uint8_t level = 0,
    uint8_t x = 0,
    uint8_t y = 0) {
  ServerObjectFadeBuilder builder_(_fbb);
  builder_.add_y(y);
  builder_.add_x(x);
  builder_.add_level(level);
  builder_.add_type(type);
  return builder_.Finish();
}

#endif  // FLATBUFFERS_GENERATED_SERVER_H_
