#pragma once

#include "Enum/Enum.h"
#include "H3mLoader/H3mObject.h"
#include "SDL3/SDL_rect.h"
#include "Set/StructSet.h"
#include <array>
#include <cstddef>
#include <cstdint>
#include <optional>
#include <string>
#include <vector>

struct RampartFactionSet {
  const static inline FactionSetI
      faction =
          {.index = 1,
           .nativeTerrain = Enum::TERRAIN_GRASS,
           .creatureBackground = {"TPCASRAM.pcx", "CRBKGRAM.pcx"},
           .puzzleMap =
               {
                   {"PUZRAM02.pcx", {7, 8}},     {"PUZRAM13.pcx", {7, 101}},
                   {"PUZRAM20.pcx", {7, 195}},   {"PUZRAM06.pcx", {7, 310}},
                   {"PUZRAM22.pcx", {7, 378}},   {"PUZRAM21.pcx", {7, 449}},
                   {"PUZRAM19.pcx", {61, 8}},    {"PUZRAM08.pcx", {97, 42}},
                   {"PUZRAM24.pcx", {98, 201}},  {"PUZRAM36.pcx", {108, 308}},
                   {"PUZRAM01.pcx", {115, 461}}, {"PUZRAM07.pcx", {129, 366}},
                   {"PUZRAM04.pcx", {134, 8}},   {"PUZRAM25.pcx", {157, 188}},
                   {"PUZRAM39.pcx", {160, 309}}, {"PUZRAM11.pcx", {162, 441}},
                   {"PUZRAM28.pcx", {164, 126}}, {"PUZRAM33.pcx", {174, 390}},
                   {"PUZRAM46.pcx", {178, 188}}, {"PUZRAM41.pcx", {187, 258}},
                   {"PUZRAM38.pcx", {190, 24}},  {"PUZRAM45.pcx", {215, 272}},
                   {"PUZRAM09.pcx", {255, 443}}, {"PUZRAM40.pcx", {265, 323}},
                   {"PUZRAM47.pcx", {277, 45}},  {"PUZRAM27.pcx", {278, 383}},
                   {"PUZRAM43.pcx", {292, 196}}, {"PUZRAM48.pcx", {294, 266}},
                   {"PUZRAM17.pcx", {310, 8}},   {"PUZRAM16.pcx", {330, 493}},
                   {"PUZRAM12.pcx", {339, 8}},   {"PUZRAM29.pcx", {339, 167}},
                   {"PUZRAM35.pcx", {344, 108}}, {"PUZRAM31.pcx", {361, 239}},
                   {"PUZRAM44.pcx", {363, 385}}, {"PUZRAM42.pcx", {398, 310}},
                   {"PUZRAM23.pcx", {400, 130}}, {"PUZRAM32.pcx", {404, 436}},
                   {"PUZRAM26.pcx", {421, 127}}, {"PUZRAM37.pcx", {429, 8}},
                   {"PUZRAM30.pcx", {430, 106}}, {"PUZRAM14.pcx", {462, 393}},
                   {"PUZRAM10.pcx", {469, 270}}, {"PUZRAM03.pcx", {486, 8}},
                   {"PUZRAM15.pcx", {499, 481}}, {"PUZRAM34.pcx", {511, 255}},
                   {"PUZRAM18.pcx", {516, 48}},  {"PUZRAM05.pcx", {525, 169}},
               },
           .mapObject =
               {
                   "AVCramx0.def",
                   "AVCramx0.def",
                   "AVCramx0.def",
                   "AVCRAMP0.DEF",
                   "AVCRAMZ0.DEF",
               },
           .musicTheme = "Rampart.wav",
           .guildBackground = "TPMAGE.pcx",
           .townBackground = "TBRMBACK.pcx",
           .guildWindow = "TPMAGERM.pcx",
           .hallBackground = "TPTHBKRM.pcx",
           .hallSlots =
               {
                   {
                       {
                           Enum::BUILD_VILLAGE_HALL,
                           Enum::BUILD_TOWN_HALL,
                           Enum::BUILD_CITY_HALL,
                           Enum::BUILD_CAPITOL,
                       },
                       {
                           Enum::BUILD_FORT,
                           Enum::BUILD_CITADEL,
                           Enum::BUILD_CASTLE,
                       },
                       {
                           Enum::BUILD_TAVERN,
                       },
                       {
                           Enum::BUILD_BLACKSMITH,
                       },
                   },
                   {
                       {
                           Enum::BUILD_MARKETPLACE,
                           Enum::BUILD_RESOURCE_SILO,
                       },
                       {
                           Enum::BUILD_MAGE_GUILD_1,
                           Enum::BUILD_MAGE_GUILD_2,
                           Enum::BUILD_MAGE_GUILD_3,
                           Enum::BUILD_MAGE_GUILD_4,
                           Enum::BUILD_MAGE_GUILD_5,
                       },
                       {
                           Enum::BUILD_SPECIAL_18,
                           Enum::BUILD_SPECIAL_19,
                       },
                   },
                   {
                       {Enum::BUILD_SPECIAL_20}, //
                       {Enum::BUILD_HORDE_2},
                       {Enum::BUILD_HORDE_3},
                   },
                   {
                       {
                           Enum::BUILD_DWELLING_LEVEL_1,
                           Enum::BUILD_DWELLING_UPGRADE_LEVEL_1,
                       },
                       {
                           Enum::BUILD_DWELLING_LEVEL_2,
                           Enum::BUILD_DWELLING_UPGRADE_LEVEL_2,
                       },
                       {
                           Enum::BUILD_DWELLING_LEVEL_3,
                           Enum::BUILD_DWELLING_UPGRADE_LEVEL_3,
                       },
                       {
                           Enum::BUILD_DWELLING_LEVEL_4,
                           Enum::BUILD_DWELLING_UPGRADE_LEVEL_4,
                       },
                   },
                   {
                       {
                           Enum::BUILD_DWELLING_LEVEL_5,
                           Enum::BUILD_DWELLING_UPGRADE_LEVEL_5,
                       },
                       {
                           Enum::BUILD_DWELLING_LEVEL_6,
                           Enum::BUILD_DWELLING_UPGRADE_LEVEL_6,
                       },
                       {
                           Enum::BUILD_DWELLING_LEVEL_7,
                           Enum::BUILD_DWELLING_UPGRADE_LEVEL_7,
                       },
                   },
               },
           .blacksmith = {Enum::BALLISTA},
           .builds =
               {
                   {
                       .id = Enum::BUILD_VILLAGE_HALL,
                       .animation = "TBRMHALL.def",
                       .x = 565,
                       .y = 216,
                       .z = 0,
                       .border = "TORHAL1.bmp",
                       .area = "TZRHAL1.bmp",
                       .icon = "ThCsHal1.pcx", // 根据目标格式推断
                       .require = {},
                       .cost = {},
                       .income =
                           {
                               {
                                   .id = Enum::GOLD,
                                   .minVal = 500,
                                   .maxVal = 500,
                                   .frequency = 1,
                               },
                           },
                       .upgrades = std::nullopt,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_TOWN_HALL,
                       .animation = "TBRMHAL2.def",
                       .x = 538,
                       .y = 187,
                       .z = 0,
                       .border = "TORHAL2.bmp",
                       .area = "TZRHAL2.bmp",
                       .icon = "ThCsHal2.pcx",
                       .require = {Enum::BUILD_TAVERN},
                       .cost = {},
                       .income =
                           {
                               {
                                   .id = Enum::GOLD,
                                   .minVal = 1000,
                                   .maxVal = 1000,
                                   .frequency = 1,
                               },
                           },
                       .upgrades = Enum::BUILD_VILLAGE_HALL,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_CITY_HALL,
                       .animation = "TBRMHAL3.def",
                       .x = 538,
                       .y = 187,
                       .z = 0,
                       .border = "TORHAL3.bmp",
                       .area = "TZRHAL3.bmp",
                       .icon = "ThCsHal3.pcx",
                       .require =
                           {
                               Enum::BUILD_MAGE_GUILD_1,
                               Enum::BUILD_MARKETPLACE,
                               Enum::BUILD_BLACKSMITH,
                           },
                       .cost = {},
                       .income =
                           {
                               {
                                   .id = Enum::GOLD,
                                   .minVal = 2000,
                                   .maxVal = 2000,
                                   .frequency = 1,
                               },
                           },
                       .upgrades = Enum::BUILD_TOWN_HALL,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_CAPITOL,
                       .animation = "TBRMHAL4.def",
                       .x = 534,
                       .y = 187,
                       .z = 0,
                       .border = "TORHAL4.bmp",
                       .area = "TZRHAL4.bmp",
                       .icon = "ThCsHal4.pcx",
                       .require =
                           {
                               Enum::BUILD_CASTLE,
                           },
                       .cost = {},
                       .income =
                           {
                               {
                                   .id = Enum::GOLD,
                                   .minVal = 4000,
                                   .maxVal = 4000,
                                   .frequency = 1,
                               },
                           },
                       .upgrades = Enum::BUILD_CITY_HALL,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_FORT,
                       .animation = "TBRMCSTL.def",
                       .x = 63,
                       .y = 25,
                       .z = -4,
                       .border = "TORCAS1.bmp",
                       .area = "TZRCAS1.bmp",
                       .icon = "ThCsCAS1.pcx",
                       .require = {},
                       .cost = {},
                       .income = {},
                       .upgrades = std::nullopt,
                       .autoMode = false,
                       .bonus =
                           {
                               {
                                   .id = Enum::CREATURE_GROWTH_RATE,
                                   .subId = 1,
                                   .val = 50,
                               },
                               {
                                   .id = Enum::CREATURE_GROWTH_RATE,
                                   .subId = 2,
                                   .val = 50,
                               },
                               {
                                   .id = Enum::CREATURE_GROWTH_RATE,
                                   .subId = 3,
                                   .val = 50,
                               },
                               {
                                   .id = Enum::CREATURE_GROWTH_RATE,
                                   .subId = 4,
                                   .val = 50,
                               },
                               {
                                   .id = Enum::CREATURE_GROWTH_RATE,
                                   .subId = 5,
                                   .val = 50,
                               },
                               {
                                   .id = Enum::CREATURE_GROWTH_RATE,
                                   .subId = 6,
                                   .val = 50,
                               },
                               {
                                   .id = Enum::CREATURE_GROWTH_RATE,
                                   .subId = 7,
                                   .val = 50,
                               },
                               {
                                   .id = Enum::TOWN_BATTLE_SIEGE,
                                   .subId = NULL,
                                   .val = 0,
                               },
                           },
                   },
                   {
                       .id = Enum::BUILD_CITADEL,
                       .animation = "TBRMCAS2.def",
                       .x = 79,
                       .y = 18,
                       .z = -4,
                       .border = "TORCAS3.bmp",
                       .area = "TZRCAS3.bmp",
                       .icon = "ThCsCAS2.pcx",
                       .require = {},
                       .cost = {},
                       .income = {},
                       .upgrades = Enum::BUILD_FORT,
                       .autoMode = false,
                       .bonus =
                           {
                               {
                                   .id = Enum::CREATURE_GROWTH_RATE,
                                   .subId = 1,
                                   .val = 1,
                               },
                               {
                                   .id = Enum::CREATURE_GROWTH_RATE,
                                   .subId = 2,
                                   .val = 1,
                               },
                               {
                                   .id = Enum::CREATURE_GROWTH_RATE,
                                   .subId = 3,
                                   .val = 1,
                               },
                               {
                                   .id = Enum::CREATURE_GROWTH_RATE,
                                   .subId = 4,
                                   .val = 1,
                               },
                               {
                                   .id = Enum::CREATURE_GROWTH_RATE,
                                   .subId = 5,
                                   .val = 1,
                               },
                               {
                                   .id = Enum::CREATURE_GROWTH_RATE,
                                   .subId = 6,
                                   .val = 1,
                               },
                               {
                                   .id = Enum::CREATURE_GROWTH_RATE,
                                   .subId = 7,
                                   .val = 1,
                               },
                               {
                                   .id = Enum::TOWN_BATTLE_SIEGE,
                                   .subId = Enum::MARKSMAN,
                                   .val = 1,
                               },
                           },
                   },
                   {
                       .id = Enum::BUILD_CASTLE,
                       .animation = "TBRMCAS3.def",
                       .x = 79,
                       .y = 18,
                       .z = -4,
                       .border = "TORCAS2.bmp",
                       .area = "TZRCAS2.bmp",
                       .icon = "ThCsCAS3.pcx",
                       .require = {},
                       .cost = {},
                       .income = {},
                       .upgrades = Enum::BUILD_CITADEL,
                       .autoMode = false,
                       .bonus =
                           {
                               {
                                   .id = Enum::CREATURE_GROWTH_RATE,
                                   .subId = 1,
                                   .val = 150,
                               },
                               {
                                   .id = Enum::CREATURE_GROWTH_RATE,
                                   .subId = 2,
                                   .val = 150,
                               },
                               {
                                   .id = Enum::CREATURE_GROWTH_RATE,
                                   .subId = 3,
                                   .val = 150,
                               },
                               {
                                   .id = Enum::CREATURE_GROWTH_RATE,
                                   .subId = 4,
                                   .val = 150,
                               },
                               {
                                   .id = Enum::CREATURE_GROWTH_RATE,
                                   .subId = 5,
                                   .val = 150,
                               },
                               {
                                   .id = Enum::CREATURE_GROWTH_RATE,
                                   .subId = 6,
                                   .val = 150,
                               },
                               {
                                   .id = Enum::CREATURE_GROWTH_RATE,
                                   .subId = 7,
                                   .val = 150,
                               },
                               {
                                   .id = Enum::TOWN_BATTLE_SIEGE,
                                   .subId = Enum::MARKSMAN,
                                   .val = 3,
                               },
                           },
                   },
                   {
                       .id = Enum::BUILD_TAVERN,
                       .animation = "TBRMTVRN.def",
                       .x = 181,
                       .y = 229,
                       .z = 1,
                       .border = "TORTAV.bmp",
                       .area = "TZRTAV.bmp",
                       .icon = "ThCsTAV1.pcx",
                       .require = {},
                       .cost = {},
                       .income = {},
                       .upgrades = std::nullopt,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_BLACKSMITH,
                       .animation = "TBRMBLAK.def",
                       .x = 558,
                       .y = 105,
                       .z = -3,
                       .border = "TORAID.bmp",
                       .area = "TZRAID.bmp",
                       .icon = "ThCsBLAK.pcx",
                       .require = {},
                       .cost = {},
                       .income = {},
                       .upgrades = std::nullopt,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_MARKETPLACE,
                       .animation = "TBRMMARK.def",
                       .x = 129,
                       .y = 301,
                       .z = 3,
                       .border = "TORMRK1.bmp",
                       .area = "TZRMRK1.bmp",
                       .icon = "ThCsMRK1.pcx",
                       .require = {},
                       .cost = {},
                       .income = {},
                       .upgrades = std::nullopt,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_RESOURCE_SILO,
                       .animation = "TBRMSILO.def",
                       .x = 245,
                       .y = 324,
                       .z = 4,
                       .border = "TORMRK2.bmp",
                       .area = "TZRMRK2.bmp",
                       .icon = "ThCsMRK2.pcx",
                       .require = {},
                       .cost = {},
                       .income =
                           {
                               {
                                   .id = Enum::WOOD,
                                   .minVal = 1,
                                   .maxVal = 1,
                                   .frequency = 1,
                               },
                               {
                                   .id = Enum::ORE,
                                   .minVal = 1,
                                   .maxVal = 1,
                                   .frequency = 1,
                               },
                           },
                       .upgrades = std::nullopt,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_SPECIAL_10,
                       .animation = "",
                   },
                   {
                       .id = Enum::BUILD_MAGE_GUILD_1,
                       .animation = "TBRMMAGE.def",
                       .x = 454,
                       .y = 200,
                       .z = -1,
                       .border = "TORMAG1.bmp",
                       .area = "TZRMAG1.bmp",
                       .icon = "ThCsMAG1.pcx",
                       .require = {},
                       .cost = {},
                       .income = {},
                       .upgrades = std::nullopt,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_MAGE_GUILD_2,
                       .animation = "TBRMMAG2.def",
                       .x = 438,
                       .y = 178,
                       .z = -1,
                       .border = "TORMAG2.bmp",
                       .area = "TZRMAG2.bmp",
                       .icon = "ThCsMAG2.pcx",
                       .require = {},
                       .cost = {},
                       .income = {},
                       .upgrades = Enum::BUILD_MAGE_GUILD_1,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_MAGE_GUILD_3,
                       .animation = "TBRMMAG3.def",
                       .x = 418,
                       .y = 153,
                       .z = -1,
                       .border = "TORMAG3.bmp",
                       .area = "TZRMAG3.bmp",
                       .icon = "ThCsMAG3.pcx",
                       .require = {},
                       .cost = {},
                       .income = {},
                       .upgrades = Enum::BUILD_MAGE_GUILD_2,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_MAGE_GUILD_4,
                       .animation = "TBRMMAG4.def",
                       .x = 406,
                       .y = 129,
                       .z = -1,
                       .border = "TORMAG4.bmp",
                       .area = "TZRMAG4.bmp",
                       .icon = "ThCsMAG4.pcx",
                       .require = {},
                       .cost = {},
                       .income = {},
                       .upgrades = Enum::BUILD_MAGE_GUILD_3,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_MAGE_GUILD_5,
                       .animation = "TBRMMAG5.def",
                       .x = 384,
                       .y = 104,
                       .z = -1,
                       .border = "TORMAG5.bmp",
                       .area = "TZRMAG5.bmp",
                       .icon = "ThCsMAG5.pcx",
                       .require = {},
                       .cost = {},
                       .income = {},
                       .upgrades = Enum::BUILD_MAGE_GUILD_4,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_SHIPYARD,
                       .animation = "",
                   },
                   {
                       .id = Enum::BUILD_GRAIL,
                       .animation = "TBRMHOLY.def",
                       .x = 0,
                       .y = 54,
                       .z = -3,
                       .border = "TORHOLY.bmp",
                       .area = "TZRHOLY.bmp",
                       .icon = "ThCsHOLY.pcx",
                       .require = {},
                       .cost = {},
                       .income =
                           {
                               {
                                   .id = Enum::GOLD,
                                   .minVal = 5000,
                                   .maxVal = 5000,
                                   .frequency = 1,
                               },
                           },
                       .upgrades = std::nullopt,
                       .autoMode = false,
                       .bonus =
                           {
                               {
                                   .id = Enum::TOWN_BATTLE_MORALE_RAISE,
                                   .subId = NULL,
                                   .val = 2,
                               },
                           },
                   },
                   {
                       .id = Enum::BUILD_SPECIAL_18,
                       .animation = "TBRMSPEC.def",
                       .x = 555,
                       .y = 297,
                       .z = 2,
                       .border = "TORGAR1A.pcx", 
                       .area = "TZRGAR1A.pcx",
                       .icon = "",
                       .require = {},
                       .cost = {},
                       .income = {},
                       .upgrades = std::nullopt,
                       .autoMode = false,
                       .bonus =
                           {
                               {
                                   .id = Enum::HERO_MOVENT_SEA,
                                   .subId = NULL,
                                   .val = 500,
                               },
                           },
                   },
                   {
                       .id = Enum::BUILD_SPECIAL_19,
                       .animation = "TBCSEXT1.def",
                       .x = 0,
                       .y = 198,
                       .z = 2,
                       .border = "TOCSTAV2.pcx",
                       .area = "TZCSTAV2.pcx",
                       .icon = "ThCsTAV2.pcx",
                       .require = {},
                       .cost = {},
                       .income = {},
                       .upgrades = Enum::BUILD_TAVERN,
                       .autoMode = false,
                       .bonus =
                           {
                               {
                                   .id = Enum::TOWN_BATTLE_MORALE_RAISE,
                                   .subId = NULL,
                                   .val = 1,
                               },
                           },
                   },
                   {
                       .id = Enum::BUILD_SPECIAL_20,
                       .animation = "TBCSEXT0.def",
                       .x = 384,
                       .y = 193,
                       .z = -2,
                       .border = "TOCSCAVM.pcx",
                       .area = "TZCSCAVM.pcx",
                       .icon = "ThCsCv2S.pcx",
                       .require = {},
                       .cost = {},
                       .income = {},
                       .upgrades = std::nullopt,
                       .autoMode = false,
                       .bonus =
                           {
                               {
                                   .id = Enum::HERO_MOVENT_LAND,
                                   .subId = ObjectType::STABLES,
                                   .val = 500,
                                   .forceVisit = true,
                                   .frequency = 7,
                               },
                           },
                   },
                   {
                       .id = Enum::BUILD_SPECIAL_21,
                       .animation = "",
                   },
                   {
                       .id = Enum::BUILD_DWELLING_LEVEL_1,
                       .animation = "TBCSDW_0.def",
                       .x = 304,
                       .y = 92,
                       .z = -1,
                       .border = "TOCSPIK1.pcx",
                       .area = "TZCSPIK1.pcx",
                       .icon = "ThCsPIK1.pcx",
                       .require = {},
                       .cost = {},
                       .upgrades = std::nullopt,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_DWELLING_UPGRADE_LEVEL_1,
                       .animation = "TBCSUP_0.def",
                       .x = 304,
                       .y = 65,
                       .z = -1,
                       .border = "TOCSPIK2.pcx",
                       .area = "TZCSPIK2.pcx",
                       .icon = "ThCsPIK2.pcx",
                       .require = {},
                       .cost = {},
                       .upgrades = Enum::BUILD_DWELLING_LEVEL_1,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_HORDE_1,
                   },
                   {
                       .id = Enum::BUILD_DWELLING_LEVEL_2,
                       .animation = "TBCSDW_1.def",
                       .x = 360,
                       .y = 130,
                       .z = 0,
                       .border = "TOCSCRS1.pcx",
                       .area = "TZCSCRS1.pcx",
                       .icon = "ThCsCRS1.pcx",
                       .require = {},
                       .cost = {},
                       .upgrades = std::nullopt,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_DWELLING_UPGRADE_LEVEL_2,
                       .animation = "TBCSUP_1.def",
                       .x = 360,
                       .y = 115,
                       .z = 0,
                       .border = "TOCSCRS2.pcx",
                       .area = "TZCSCRS2.pcx",
                       .icon = "ThCsCRS2.pcx",
                       .require = {},
                       .cost = {},
                       .upgrades = Enum::BUILD_DWELLING_LEVEL_2,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_HORDE_2,
                   },
                   {
                       .id = Enum::BUILD_DWELLING_LEVEL_3,
                       .animation = "TBCSDW_2.def",
                       .x = 76,
                       .y = 57,
                       .z = -1,
                       .border = "TOCSGR1N.pcx",
                       .area = "TZCSGR1N.pcx",
                       .icon = "ThCsGR1.pcx",
                       .require = {Enum::BUILD_DWELLING_LEVEL_4},
                       .cost = {},
                       .upgrades = std::nullopt,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_DWELLING_UPGRADE_LEVEL_3,
                       .animation = "TBCSUP_2.def",
                       .x = 76,
                       .y = 35,
                       .z = -1,
                       .border = "TOCSGR2N.pcx",
                       .area = "TZCSGR2N.pcx",
                       .icon = "ThCsGR2.pcx",
                       .require = {},
                       .cost = {},
                       .upgrades = Enum::BUILD_DWELLING_LEVEL_3,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_HORDE_3,
                       .animation = "TBCSHRD1.def",
                       .x = 76,
                       .y = 53,
                       .z = -1,
                       .border = "TOCSGR1H.pcx",
                       .area = "TZCSGR1H.pcx",
                       .icon = "ThCsGR1H.pcx",
                       .require = {},
                       .cost = {},
                       .upgrades = Enum::BUILD_DWELLING_UPGRADE_LEVEL_3,
                       .autoMode = false,
                       .bonus =
                           {
                               {
                                   .id = Enum::CREATURE_GROWTH,
                                   .subId = 3,
                                   .val = 3,
                               },
                           },
                   },
                   {
                       .id = Enum::BUILD_DWELLING_LEVEL_4,
                       .animation = "TBCSDW_3.def",
                       .x = 176,
                       .y = 101,
                       .z = 0,
                       .border = "TOCSSWD1.pcx",
                       .area = "TZCSSWD1.pcx",
                       .icon = "ThCsSWD1.pcx",
                       .require = {Enum::BUILD_BLACKSMITH,
                                   Enum::BUILD_DWELLING_LEVEL_1},
                       .cost = {},
                       .upgrades = std::nullopt,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_DWELLING_UPGRADE_LEVEL_4,
                       .animation = "TBCSUP_3.def",
                       .x = 176,
                       .y = 85,
                       .z = 0,
                       .border = "TOCSSWD2.pcx",
                       .area = "TZCSSWD2.pcx",
                       .icon = "ThCsSWD2.pcx",
                       .require = {},
                       .cost = {},
                       .upgrades = Enum::BUILD_DWELLING_LEVEL_4,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_HORDE_4,
                   },
                   {
                       .id = Enum::BUILD_DWELLING_LEVEL_5,
                       .animation = "TBCSDW_4.def",
                       .x = 563,
                       .y = 211,
                       .z = 1,
                       .border = "TOCSMON1.pcx",
                       .area = "TZCSMON1.pcx",
                       .icon = "ThCsMON1.pcx",
                       .require = {Enum::BUILD_MAGE_GUILD_1,
                                   Enum::BUILD_DWELLING_LEVEL_4},
                       .cost = {},
                       .upgrades = std::nullopt,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_DWELLING_UPGRADE_LEVEL_5,
                       .animation = "TBCSUP_4.def",
                       .x = 563,
                       .y = 173,
                       .z = 1,
                       .border = "TOCSMON2.pcx",
                       .area = "TZCSMON2.pcx",
                       .icon = "ThCsMON2.pcx",
                       .require = {},
                       .cost = {},
                       .upgrades = Enum::BUILD_DWELLING_LEVEL_5,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_HORDE_5,
                   },
                   {
                       .id = Enum::BUILD_DWELLING_LEVEL_6,
                       .animation = "TBCSDW_5.def",
                       .x = 174,
                       .y = 190,
                       .z = -1,
                       .border = "TOCSC101.pcx",
                       .area = "TZCSCAV1.pcx",
                       .icon = "ThCsCv1.pcx",
                       .require = {Enum::BUILD_SPECIAL_20},
                       .cost = {},
                       .upgrades = std::nullopt,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_DWELLING_UPGRADE_LEVEL_6,
                       .animation = "TBCSUP_5.def",
                       .x = 160,
                       .y = 190,
                       .z = -1,
                       .border = "TOCSCAV2.pcx",
                       .area = "TZCSCAV2.pcx",
                       .icon = "ThCsCv2.pcx",
                       .require = {},
                       .cost = {},
                       .upgrades = Enum::BUILD_DWELLING_LEVEL_6,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_DWELLING_LEVEL_7,
                       .animation = "TBCSDW_6.def",
                       .x = 303,
                       .y = 0,
                       .z = -2,
                       .border = "TOCSANG1.pcx",
                       .area = "TZCSANG1.pcx",
                       .icon = "ThCsANG1.pcx",
                       .require = {Enum::BUILD_DWELLING_LEVEL_5},
                       .cost = {},
                       .upgrades = std::nullopt,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_DWELLING_UPGRADE_LEVEL_7,
                       .animation = "TBCSUP_6.def",
                       .x = 303,
                       .y = 0,
                       .z = -2,
                       .border = "TOCSANG2.pcx",
                       .area = "TZCSANG2.pcx",
                       .icon = "ThCsANG2.pcx",
                       .require = {},
                       .cost = {},
                       .upgrades = Enum::BUILD_DWELLING_LEVEL_7,
                       .autoMode = false,
                   },
                   {
                       .id = Enum::BUILD_SHIP,
                       .animation = "TBCSBOAT.def",
                       .x = 478,
                       .y = 134,
                       .z = -3,
                   },
                   {
                       .id = Enum::BUILD_HORDE_UPGRADE_1,
                   },
                   {
                       .id = Enum::BUILD_HORDE_UPGRADE_2,
                   },
                   {
                       .id = Enum::BUILD_HORDE_UPGRADE_3,
                       .animation = "TBCSHRD2.def",
                       .x = 76,
                       .y = 35,
                       .z = -1,
                       .border = "TOCSGR2H.pcx",
                       .area = "TZCSGR2H.pcx",
                       .require = {Enum::BUILD_DWELLING_UPGRADE_LEVEL_3},
                       .upgrades = Enum::BUILD_HORDE_3,
                       .autoMode = true,
                   },
                   {
                       .id = Enum::BUILD_HORDE_UPGRADE_4,
                   },
                   {
                       .id = Enum::BUILD_HORDE_UPGRADE_5,
                   },
                   {
                       .id = Enum::BUILD_EXTRA_ANIMATE_1,
                   },
                   {
                       .id = Enum::BUILD_EXTRA_ANIMATE_2,
                   },
                   {
                       .id = Enum::BUILD_EXTRA_ANIMATE_3,
                   },
               },
           .siege =
               {
                   .shooter = Enum::MARKSMAN,
                   .imagePrefix = "SGCS",
                   .gate = {.arch = {477, 238}, .gate = {399, 274}},
                   .moat = {.bank = {403, 80}, .moat = {410, 90}},
                   .stc =
                       {
                           .background = {600, 49},
                           .bottom = {512, 347},
                           .top = {489, 79},
                       },
                   .tower =
                       {
                           .bottom =
                               {
                                   .battlement = {.x = 602, .y = 500},
                                   .creature = {.x = 394, .y = 299},
                                   .tower = {.x = 602, .y = 500},
                               },
                           .keep =
                               {
                                   .battlement = {.x = 720, .y = 158},
                                   .creature = {.x = 526, .y = -29},
                                   .tower = {.x = 720, .y = 158},
                               },
                           .top =
                               {
                                   .battlement = {.x = 557, .y = 24},
                                   .creature = {.x = 342, .y = -187},
                                   .tower = {.x = 569, .y = 35},
                               },
                       },
                   .wall =
                       {
                           .bottom = {.x = 528, .y = 350},
                           .bottomMid = {.x = 469, .y = 291},
                           .upper = {.x = 524, .y = 32},
                           .upperMid = {.x = 470, .y = 127},
                       },
               }};
};