#pragma once

#include "SDL3/SDL_rect.h"
#include <cstdint>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>
struct TownCfg {
  const static inline std::vector<std::vector<std::string>> creatureBackground =
      {{"TPCASCAS.pcx", "CRBKGCAS.pcx"}};

  const static inline std::vector<std::string> musicThemeStr = {
      "CstleTown", "Rampart", "TowerTown",  "InfernoTown",
      "NecroTown", "Dungeon", "Stronghold", "FortressTown"};

  const static inline std::string tavernVideoStr = "TAVERN.BIK";

  const static inline std::string guildBackgroundStr = "TPMAGE.pcx";

  const static inline std::vector<std::string> guildWindowStr = {
      "TPMAGECS.pcx", "TPMAGERM.pcx", "TPMAGEIN.pcx", "TPMAGEIN.pcx",
      "TPMAGENC.pcx", "TPMAGEDN.pcx", "TPMAGEST.pcx", "TPMAGEFR.pcx"};

  const static inline std::vector<std::string> backGroundsStr = {
      "TBCSBACK.pcx", "TBRMBACK.pcx", "TBTWBACK.pcx", "TBINBACK.pcx",
      "TBNCBACK.pcx", "TBDNBACK.pcx", "TBSTBACK.pcx", "TBFRBACK.pcx"};
  const static inline std::vector<std::string> hallBackgroundStr = {
      "TPTHBKCS.pcx", "TPTHBKRM.pcx", "TPTHBKTW.pcx", "TBINBACK.pcx",
      "TPTHBKNC.pcx", "TPTHBKDG.pcx", "TPTHBKTW.pcx", "TPTHBKFR.pcx"};
  const static inline std::vector<std::string> buildingsIconsStr = {
      "HALLCSTL.DEF", "HALLRAMP.DEF", "HALLTOWR.DEF", "HALLINFR.DEF",
      "HALLNECR.DEF", "HALLDUNG.DEF", "HALLSTRN.DEF", "HALLFORT.DEF"};

  enum class Building : uint8_t {
    // 通用建筑
    TOWN_HALL = 0,
    CITY_HALL = 1,
    CAPITOL = 2,
    FORT = 3,
    CITADEL = 4,
    CASTLE = 5,
    TAVERN = 6,
    BLACKSMITH = 7,
    MARKETPLACE = 8,
    RESOURCE_SILO = 9,

    // 魔法行会
    MAGE_GUILD_1 = 11,
    MAGE_GUILD_2 = 12,
    MAGE_GUILD_3 = 13,
    MAGE_GUILD_4 = 14,
    MAGE_GUILD_5 = 15,

    SHIPYARD = 16,
    GRAIL = 17,

    // 特殊建筑编号（根据城镇不同而意义不同）
    SPECIAL_10 = 10,
    SPECIAL_18 = 18,
    SPECIAL_19 = 19,
    SPECIAL_20 = 20,
    SPECIAL_21 = 21,

    // 生物巢穴
    DWELLING_LEVEL_1 = 22,
    DWELLING_UPGRADE_LEVEL_1 = 23,
    HORDE_1 = 24,
    DWELLING_LEVEL_2 = 25,
    DWELLING_UPGRADE_LEVEL_2 = 26,
    HORDE_2 = 27,
    DWELLING_LEVEL_3 = 28,
    DWELLING_UPGRADE_LEVEL_3 = 29,
    HORDE_3 = 30,
    DWELLING_LEVEL_4 = 31,
    DWELLING_UPGRADE_LEVEL_4 = 32,
    HORDE_4 = 33,
    DWELLING_LEVEL_5 = 34,
    DWELLING_UPGRADE_LEVEL_5 = 35,
    HORDE_5 = 36,
    DWELLING_LEVEL_6 = 37,
    DWELLING_UPGRADE_LEVEL_6 = 38,
    DWELLING_LEVEL_7 = 39,
    DWELLING_UPGRADE_LEVEL_7 = 40,

    VILLAGE_HALL = 255,

    // 新增特殊建筑（从 townZ 中发现的新字符串）
    EXTRA_ANIMATION = 200,
    SHIP = 201,
    EXTRA_TOWN_HALL = 202,
    EXTRA_CAPITOL = 203,
    EXTRA_CITY_HALL = 204,

    // Horde 升级版本
    HORDE_1_UPGR = 241,
    HORDE_2_UPGR = 242,
  };

  const static inline std::unordered_map<Building, std::string> townBorder[] = {
      {// 城堡 (0)
       {Building::MAGE_GUILD_1, "TOCSMAG1.pcx"},
       {Building::MAGE_GUILD_2, "TOCSMAG2.pcx"},
       {Building::MAGE_GUILD_3, "TOCSM301.pcx"},
       {Building::MAGE_GUILD_4, "TOCSM401.pcx"},
       {Building::TAVERN, "TOCSTAV1.pcx"},
       {Building::SHIPYARD, "TOCSDKMS.pcx"},
       {Building::FORT, "TOCSCAS1.pcx"},
       {Building::CITADEL, "TOCSCAS2.pcx"},
       {Building::CASTLE, "TOCSCAS3.pcx"},
       {Building::VILLAGE_HALL, "TOCSH101.pcx"},
       {Building::TOWN_HALL, "TOCSH201.pcx"},
       {Building::CITY_HALL, "TOCSH301.pcx"},
       {Building::CAPITOL, "TOCSH401.pcx"},
       {Building::MARKETPLACE, "TOCSMRK1.pcx"},
       {Building::RESOURCE_SILO, "TOCSMRK2.pcx"},
       {Building::BLACKSMITH, "TOCSBLAK.pcx"},
       {Building::SPECIAL_18, "TOCSLT01.pcx"}, // special1 for castle
       {Building::HORDE_1, "TOCSGR1H.pcx"},
       {Building::HORDE_1_UPGR, "TOCSGR2H.pcx"},
       {Building::SHIP, "TOCSDKMN.pcx"},
       {Building::SPECIAL_20, "TOCSCAVM.pcx"}, // special2 for castle
       {Building::SPECIAL_19, "TOCSTAV2.pcx"}, // special3 for castle
       {Building::GRAIL, "TOCSHOLY.pcx"},
       {Building::DWELLING_LEVEL_1, "TOCSPIK1.pcx"},
       {Building::DWELLING_LEVEL_2, "TOCSCRS1.pcx"},
       {Building::DWELLING_LEVEL_3, "TOCSGR1N.pcx"},
       {Building::DWELLING_LEVEL_4, "TOCSSWD1.pcx"},
       {Building::DWELLING_LEVEL_5, "TOCSMON1.pcx"},
       {Building::DWELLING_LEVEL_6, "TOCSC101.pcx"},
       {Building::DWELLING_LEVEL_7, "TOCSANG1.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_1, "TOCSPIK2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_2, "TOCSCRS2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_3, "TOCSGR2N.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_4, "TOCSSWD2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_5, "TOCSMON2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_6, "TOCSCAV2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_7, "TOCSANG2.pcx"}},
      {// 壁垒 (1)
       {Building::MAGE_GUILD_1, "TORMAG1.pcx"},
       {Building::MAGE_GUILD_2, "TORMAG2.pcx"},
       {Building::MAGE_GUILD_3, "TORMAG3.pcx"},
       {Building::MAGE_GUILD_4, "TORMAG4.pcx"},
       {Building::MAGE_GUILD_5, "TORMAG5.pcx"},
       {Building::TAVERN, "TORTAV.pcx"},
       {Building::FORT, "TORCAS1.pcx"},
       {Building::CITADEL, "TORCAS3.pcx"},
       {Building::CASTLE, "TORCAS2.pcx"},
       {Building::VILLAGE_HALL, "TORHAL1.pcx"},
       {Building::TOWN_HALL, "TORHAL2.pcx"},
       {Building::CITY_HALL, "TORHAL3.pcx"},
       {Building::CAPITOL, "TORHAL4.pcx"},
       {Building::MARKETPLACE, "TORMRK1.pcx"},
       {Building::RESOURCE_SILO, "TORMRK2.pcx"},
       {Building::BLACKSMITH, "TORAID.pcx"},
       {Building::SPECIAL_18, "TORGAR1A.pcx"}, // special1 for rampart
       {Building::HORDE_1, "TORDWF1H.pcx"},
       {Building::HORDE_1_UPGR, "TORDWF2H.pcx"},
       {Building::SPECIAL_19, "TORGAR2A.pcx"}, // special2 for rampart
       {Building::SPECIAL_20, "TORDWFT.pcx"},  // special3 for rampart
       {Building::HORDE_2, "TORTRE1H.pcx"},
       {Building::HORDE_2_UPGR, "TORTRE2H.pcx"},
       {Building::GRAIL, "TORHOLY.pcx"},
       {Building::DWELLING_LEVEL_1, "TORCEN1A.pcx"},
       {Building::DWELLING_LEVEL_2, "TORDWF1.pcx"},
       {Building::DWELLING_LEVEL_3, "TORELF1.pcx"},
       {Building::DWELLING_LEVEL_4, "TORPEG1A.pcx"},
       {Building::DWELLING_LEVEL_5, "TORTRE1.pcx"},
       {Building::DWELLING_LEVEL_6, "TORUNI1.pcx"},
       {Building::DWELLING_LEVEL_7, "TORDR1AA.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_1, "TORCEN2A.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_2, "TORDWF2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_3, "TORELF2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_4, "TORPEG2A.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_5, "TORTRE2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_6, "TORUNI2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_7, "TORDR2AA.pcx"}},
      {// 塔楼 (2)
       {Building::MAGE_GUILD_1, "TOTGLD1.pcx"},
       {Building::MAGE_GUILD_2, "TOTGLD2.pcx"},
       {Building::MAGE_GUILD_3, "TOTGLD3.pcx"},
       {Building::MAGE_GUILD_4, "TOTGLD4.pcx"},
       {Building::MAGE_GUILD_5, "TOTGLD5.pcx"},
       {Building::TAVERN, "TOTTAV.pcx"},
       {Building::FORT, "TOTCAS1.pcx"},
       {Building::CITADEL, "TOTCAS2.pcx"},
       {Building::CASTLE, "TOTCAS3.pcx"},
       {Building::VILLAGE_HALL, "TOTHAL1.pcx"},
       {Building::TOWN_HALL, "TOTHAL2.pcx"},
       {Building::CITY_HALL, "TOTHAL3.pcx"},
       {Building::CAPITOL, "TOTHAL4.pcx"},
       {Building::MARKETPLACE, "TOTMRK.pcx"},
       {Building::RESOURCE_SILO, "TOTMRKS.pcx"},
       {Building::BLACKSMITH, "TOTBLKA.pcx"},
       {Building::SPECIAL_10, "TOTMRKA.pcx"}, // special1 for tower
       {Building::SPECIAL_20, "TOTCASW.pcx"}, // special2 for tower
       {Building::SPECIAL_18, "TOTGLDL.pcx"}, // special3 for tower
       {Building::SPECIAL_19, "TOTGLDW.pcx"}, // special4 for tower
       {Building::HORDE_1, "TOTGAR1H.pcx"},
       {Building::HORDE_1_UPGR, "TOTGAR2H.pcx"},
       {Building::GRAIL, "TOTHOLYA.pcx"},
       {Building::DWELLING_LEVEL_1, "TOTGRM1A.pcx"},
       {Building::DWELLING_LEVEL_2, "TOTGAR1.pcx"},
       {Building::DWELLING_LEVEL_3, "TOTGOL1A.pcx"},
       {Building::DWELLING_LEVEL_4, "TOTMAG1.pcx"},
       {Building::DWELLING_LEVEL_5, "TOTGEN1.pcx"},
       {Building::DWELLING_LEVEL_6, "TOTNAG1.pcx"},
       {Building::DWELLING_LEVEL_7, "TOTTIT1.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_1, "TOTGRM2A.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_2, "TOTGAR2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_3, "TOTGOL2A.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_4, "TOTMAG2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_5, "TOTGEN2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_6, "TOTNAG2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_7, "TOTTIT2.pcx"}},
      {// 地狱 (3)
       {Building::MAGE_GUILD_1, "TOIMAG1A.pcx"},
       {Building::MAGE_GUILD_2, "TOIMAG2A.pcx"},
       {Building::MAGE_GUILD_3, "TOIMAG3A.pcx"},
       {Building::MAGE_GUILD_4, "TOIMAG4A.pcx"},
       {Building::MAGE_GUILD_5, "TOIMAG5A.pcx"},
       {Building::TAVERN, "TOITAV.pcx"},
       {Building::FORT, "TOICAS2A.pcx"},
       {Building::CITADEL, "TOICAS1A.pcx"},
       {Building::CASTLE, "TOICAS3A.pcx"},
       {Building::VILLAGE_HALL, "TOIHAL1.pcx"},
       {Building::TOWN_HALL, "TOIHAL2.pcx"},
       {Building::CITY_HALL, "TOIHAL3.pcx"},
       {Building::CAPITOL, "TOIHAL4.pcx"},
       {Building::MARKETPLACE, "TOIMAR1.pcx"},
       {Building::RESOURCE_SILO, "TOIMAR2.pcx"},
       {Building::BLACKSMITH, "TOIBLKA.pcx"},
       {Building::SPECIAL_18, "TOICAB1A.pcx"}, // special2 for inferno
       {Building::SPECIAL_19, "TOICASGA.pcx"}, // special3 for inferno
       {Building::SPECIAL_20, "TOIPAIN.pcx"},  // special4 for inferno
       {Building::HORDE_1, "TOIMP1HA.pcx"},
       {Building::HORDE_1_UPGR, "TOIMP2HA.pcx"},
       {Building::HORDE_2, "TOIHND1H.pcx"},
       {Building::HORDE_2_UPGR, "TOIHND2H.pcx"},
       {Building::GRAIL, "TOIHOLY.pcx"},
       {Building::DWELLING_LEVEL_1, "TOIMP1A.pcx"},
       {Building::DWELLING_LEVEL_2, "TOIGOG1A.pcx"},
       {Building::DWELLING_LEVEL_3, "TOIHND1.pcx"},
       {Building::DWELLING_LEVEL_4, "TOIDMN1.pcx"},
       {Building::DWELLING_LEVEL_5, "TOIPIT1.pcx"},
       {Building::DWELLING_LEVEL_6, "TOIEFR1.pcx"},
       {Building::DWELLING_LEVEL_7, "TOIDVL1.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_1, "TOIMP2A.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_2, "TOIGOG2A.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_3, "TOIHND2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_4, "TOIDMN2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_5, "TOIPIT2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_6, "TOIEFR2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_7, "TOIDVL2.pcx"}},
      {// 墓园 (4)
       {Building::MAGE_GUILD_1, "TONMAG1.pcx"},
       {Building::MAGE_GUILD_2, "TONMAG2.pcx"},
       {Building::MAGE_GUILD_3, "TONMAG3.pcx"},
       {Building::MAGE_GUILD_4, "TONMAG4.pcx"},
       {Building::MAGE_GUILD_5, "TONMAG5.pcx"},
       {Building::TAVERN, "TONTAV.pcx"},
       {Building::SHIPYARD, "TONSHPBA.pcx"},
       {Building::FORT, "TONCAS1.pcx"},
       {Building::CITADEL, "TONCAS2.pcx"},
       {Building::CASTLE, "TONCAS3.pcx"},
       {Building::VILLAGE_HALL, "TONHAL1.pcx"},
       {Building::TOWN_HALL, "TONHAL2.pcx"},
       {Building::CITY_HALL, "TONHAL3.pcx"},
       {Building::CAPITOL, "TONHAL4.pcx"},
       {Building::MARKETPLACE, "TONMRK1.pcx"},
       {Building::RESOURCE_SILO, "TONMRK2.pcx"},
       {Building::BLACKSMITH, "TONSMITA.pcx"},
       {Building::SPECIAL_18, "TONSHRDA.pcx"}, // special1 for necropolis
       {Building::HORDE_1, "TONSKE1H.pcx"},
       {Building::HORDE_1_UPGR, "TONSKE2H.pcx"},
       {Building::SHIP, "TONSHPNA.pcx"},
       {Building::SPECIAL_19, "TONNECRA.pcx"}, // special2 for necropolis
       {Building::SPECIAL_20, "TONSKELT.pcx"}, // special3 for necropolis
       {Building::GRAIL, "TONHOLYA.pcx"},
       {Building::DWELLING_LEVEL_1, "TONSKEL1.pcx"},
       {Building::DWELLING_LEVEL_2, "TONZOMB1.pcx"},
       {Building::DWELLING_LEVEL_3, "TONWIGH1.pcx"},
       {Building::DWELLING_LEVEL_4, "TONVAM1.pcx"},
       {Building::DWELLING_LEVEL_5, "TONLICH1.pcx"},
       {Building::DWELLING_LEVEL_6, "TONBKN1.pcx"},
       {Building::DWELLING_LEVEL_7, "TONBON1.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_1, "TONSKEL2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_2, "TONZOMB2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_3, "TONWIGH2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_4, "TONVAM2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_5, "TONLICH2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_6, "TONBKN2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_7, "TONBON2.pcx"}},
      {// 地牢 (5)
       {Building::MAGE_GUILD_1, "TODMAG1.pcx"},
       {Building::MAGE_GUILD_2, "TODMAG2.pcx"},
       {Building::MAGE_GUILD_3, "TODMAG3.pcx"},
       {Building::MAGE_GUILD_4, "TODMAG4.pcx"},
       {Building::MAGE_GUILD_5, "TODMAG5.pcx"},
       {Building::TAVERN, "TODTAV.pcx"},
       {Building::FORT, "TODCAS1.pcx"},
       {Building::CITADEL, "TODCAS2.pcx"},
       {Building::CASTLE, "TODCAS3.pcx"},
       {Building::VILLAGE_HALL, "TODHALL1.pcx"},
       {Building::TOWN_HALL, "TODHALL2.pcx"},
       {Building::CITY_HALL, "TODHALL3.pcx"},
       {Building::CAPITOL, "TODHALL4.pcx"},
       {Building::MARKETPLACE, "TODMARK.pcx"},
       {Building::RESOURCE_SILO, "TODSILO.pcx"},
       {Building::BLACKSMITH, "TODSMITH.pcx"},
       {Building::SPECIAL_10, "TODART.pcx"}, // special1 for dungeon
       {Building::HORDE_1, "TODTR1HA.pcx"},
       {Building::HORDE_1_UPGR, "TODTR2HA.pcx"},
       {Building::SPECIAL_18, "TODVOR1A.pcx"}, // special2 for dungeon
       {Building::SPECIAL_19, "TODPORTA.pcx"}, // special3 for dungeon
       {Building::SPECIAL_20, "TODACAD.pcx"},  // special4 for dungeon
       {Building::GRAIL, "TODHOLY.pcx"},
       {Building::DWELLING_LEVEL_1, "TODTRG1A.pcx"},
       {Building::DWELLING_LEVEL_2, "TODHAR1.pcx"},
       {Building::DWELLING_LEVEL_3, "TODBEH1A.pcx"},
       {Building::DWELLING_LEVEL_4, "TODMED1.pcx"},
       {Building::DWELLING_LEVEL_5, "TODMIN1.pcx"},
       {Building::DWELLING_LEVEL_6, "TODMAN1.pcx"},
       {Building::DWELLING_LEVEL_7, "TODDRA1A.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_1, "TODTRG2A.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_2, "TODHAR2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_3, "TODBEH2A.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_4, "TODMED2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_5, "TODMIN2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_6, "TODMAN2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_7, "TODDRA2A.pcx"}},
      {// 据点 (6)
       {Building::MAGE_GUILD_1, "TOSMAG1.pcx"},
       {Building::MAGE_GUILD_2, "TOSMAG2.pcx"},
       {Building::MAGE_GUILD_3, "TOSMAG3.pcx"},
       {Building::TAVERN, "TOSTAV.pcx"},
       {Building::FORT, "TOSCA1.pcx"},
       {Building::CITADEL, "TOSCA2.pcx"},
       {Building::CASTLE, "TOSCA3.pcx"},
       {Building::VILLAGE_HALL, "TOSHAL1A.pcx"},
       {Building::TOWN_HALL, "TOSHAL2A.pcx"},
       {Building::CITY_HALL, "TOSHAL3A.pcx"},
       {Building::CAPITOL, "TOSHAL4A.pcx"},
       {Building::MARKETPLACE, "TOSMRK1.pcx"},
       {Building::RESOURCE_SILO, "TOSMRK2.pcx"},
       {Building::BLACKSMITH, "TOSBLK1.pcx"},
       {Building::SPECIAL_18, "TOSCA1EA.pcx"}, // special1 for stronghold
       {Building::HORDE_1, "TOSGOB1H.pcx"},
       {Building::HORDE_1_UPGR, "TOSGOB2H.pcx"},
       {Building::SPECIAL_21, "TOSMRK1C.pcx"}, // special2 for stronghold
       {Building::SPECIAL_19, "TOSBLK2.pcx"},  // special3 for stronghold
       {Building::SPECIAL_20, "TOSVAH.pcx"},   // special4 for stronghold
       {Building::GRAIL, "TOSHOLYA.pcx"},
       {Building::DWELLING_LEVEL_1, "TOSGOB1.pcx"},
       {Building::DWELLING_LEVEL_2, "TOSWOL1.pcx"},
       {Building::DWELLING_LEVEL_3, "TOSORC1.pcx"},
       {Building::DWELLING_LEVEL_4, "TOSOGR1.pcx"},
       {Building::DWELLING_LEVEL_5, "TOSROC1.pcx"},
       {Building::DWELLING_LEVEL_6, "TOSCYC1.pcx"},
       {Building::DWELLING_LEVEL_7, "TOSBEH1A.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_1, "TOSGOB2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_2, "TOSWOL2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_3, "TOSORC2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_4, "TOSOGR2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_5, "TOSROC2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_6, "TOSCYC2A.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_7, "TOSBEH2A.pcx"}},
      {// 要塞 (7)
       {Building::MAGE_GUILD_1, "TOFMAG1A.pcx"},
       {Building::MAGE_GUILD_2, "TOFMAG2A.pcx"},
       {Building::MAGE_GUILD_3, "TOFMAG3A.pcx"},
       {Building::TAVERN, "TOFTAVA.pcx"},
       {Building::SHIPYARD, "TOFDCK2.pcx"},
       {Building::FORT, "TOFCAS1.pcx"},
       {Building::CITADEL, "TOFCAS2.pcx"},
       {Building::CASTLE, "TOFCAS3.pcx"},
       {Building::VILLAGE_HALL, "TOFHAL1.pcx"},
       {Building::TOWN_HALL, "TOFHAL2.pcx"},
       {Building::CITY_HALL, "TOFHAL3.pcx"},
       {Building::CAPITOL, "TOFHAL4.pcx"},
       {Building::MARKETPLACE, "TOFMRKAA.pcx"},
       {Building::RESOURCE_SILO, "TOFMRK2A.pcx"},
       {Building::BLACKSMITH, "TOFAIDA.pcx"},
       {Building::SPECIAL_20, "TOFCAGE.pcx"}, // special1 for fortress
       {Building::HORDE_1, "TOFGNL1H.pcx"},
       {Building::HORDE_1_UPGR, "TOFGNL2H.pcx"},
       {Building::SHIP, "TOFDCK1.pcx"},
       {Building::SPECIAL_19, "TOFCASD.pcx"}, // special2 for fortress
       {Building::SPECIAL_18, "TOFCASA.pcx"}, // special3 for fortress
       {Building::GRAIL, "TOFHLYAA.pcx"},
       {Building::DWELLING_LEVEL_1, "TOFGNL1.pcx"},
       {Building::DWELLING_LEVEL_2, "TOFLIZ1.pcx"},
       {Building::DWELLING_LEVEL_3, "TOFFLY1A.pcx"},
       {Building::DWELLING_LEVEL_4, "TOFBAS1.pcx"},
       {Building::DWELLING_LEVEL_5, "TOFGOR1.pcx"},
       {Building::DWELLING_LEVEL_6, "TOFWYV1.pcx"},
       {Building::DWELLING_LEVEL_7, "TOFHYD1A.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_1, "TOFGNL2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_2, "TOFLIZ2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_3, "TOFFLY2A.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_4, "TOFBAS2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_5, "TOFGOR2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_6, "TOFWYV2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_7, "TOFHYD2A.pcx"}}};

  const static inline std::unordered_map<Building, std::string> townBuilds[] = {
      {// 城堡 (0)
       {Building::EXTRA_ANIMATION, "TBCSEXT2.def"},
       {Building::MAGE_GUILD_1, "TBCSMAGE.def"},
       {Building::MAGE_GUILD_2, "TBCSMAG2.def"},
       {Building::MAGE_GUILD_3, "TBCSMAG3.def"},
       {Building::MAGE_GUILD_4, "TBCSMAG4.def"},
       {Building::TAVERN, "TBCSTVRN.def"},
       {Building::SHIPYARD, "TBCSDOCK.def"},
       {Building::FORT, "TBCSCSTL.def"},
       {Building::CITADEL, "TBCSCAS2.def"},
       {Building::CASTLE, "TBCSCAS3.def"},
       {Building::VILLAGE_HALL, "TBCSHALL.def"},
       {Building::TOWN_HALL, "TBCSHAL2.def"},
       {Building::CITY_HALL, "TBCSHAL3.def"},
       {Building::CAPITOL, "TBCSHAL4.def"},
       {Building::MARKETPLACE, "TBCSMARK.def"},
       {Building::RESOURCE_SILO, "TBCSSILO.def"},
       {Building::BLACKSMITH, "TBCSBLAK.def"},
       {Building::SPECIAL_18, "TBCSSPEC.def"}, // special1 for castle
       {Building::HORDE_1, "TBCSHRD1.def"},
       {Building::HORDE_1_UPGR, "TBCSHRD2.def"},
       {Building::SHIP, "TBCSBOAT.def"},
       {Building::SPECIAL_20, "TBCSEXT0.def"}, // special2 for castle
       {Building::SPECIAL_19, "TBCSEXT1.def"}, // special3 for castle
       {Building::GRAIL, "TBCSHOLY.def"},
       {Building::DWELLING_LEVEL_1, "TBCSDW_0.def"},
       {Building::DWELLING_LEVEL_2, "TBCSDW_1.def"},
       {Building::DWELLING_LEVEL_3, "TBCSDW_2.def"},
       {Building::DWELLING_LEVEL_4, "TBCSDW_3.def"},
       {Building::DWELLING_LEVEL_5, "TBCSDW_4.def"},
       {Building::DWELLING_LEVEL_6, "TBCSDW_5.def"},
       {Building::DWELLING_LEVEL_7, "TBCSDW_6.def"},
       {Building::DWELLING_UPGRADE_LEVEL_1, "TBCSUP_0.def"},
       {Building::DWELLING_UPGRADE_LEVEL_2, "TBCSUP_1.def"},
       {Building::DWELLING_UPGRADE_LEVEL_3, "TBCSUP_2.def"},
       {Building::DWELLING_UPGRADE_LEVEL_4, "TBCSUP_3.def"},
       {Building::DWELLING_UPGRADE_LEVEL_5, "TBCSUP_4.def"},
       {Building::DWELLING_UPGRADE_LEVEL_6, "TBCSUP_5.def"},
       {Building::DWELLING_UPGRADE_LEVEL_7, "TBCSUP_6.def"}},
      {// 壁垒 (1)
       {Building::EXTRA_ANIMATION, "TBRMEXT2.def"},
       {Building::MAGE_GUILD_1, "TBRMMAGE.def"},
       {Building::MAGE_GUILD_2, "TBRMMAG2.def"},
       {Building::MAGE_GUILD_3, "TBRMMAG3.def"},
       {Building::MAGE_GUILD_4, "TBRMMAG4.def"},
       {Building::MAGE_GUILD_5, "TBRMMAG5.def"},
       {Building::TAVERN, "TBRMTVRN.def"},
       {Building::FORT, "TBRMCSTL.def"},
       {Building::CITADEL, "TBRMCAS2.def"},
       {Building::CASTLE, "TBRMCAS3.def"},
       {Building::VILLAGE_HALL, "TBRMHALL.def"},
       {Building::TOWN_HALL, "TBRMHAL2.def"},
       {Building::CITY_HALL, "TBRMHAL3.def"},
       {Building::CAPITOL, "TBRMHAL4.def"},
       {Building::MARKETPLACE, "TBRMMARK.def"},
       {Building::RESOURCE_SILO, "TBRMSILO.def"},
       {Building::BLACKSMITH, "TBRMBLAK.def"},
       {Building::SPECIAL_18, "TBRMSPEC.def"}, // special1 for rampart
       {Building::SPECIAL_20, "TBRMEXT0.def"}, // special2 for rampart
       {Building::SPECIAL_19, "TBRMEXT1.def"}, // special3 for rampart
       {Building::GRAIL, "TBRMHOLY.def"},
       {Building::EXTRA_TOWN_HALL, "TBRMEXT3.def"},
       {Building::EXTRA_CITY_HALL, "TBRMEXT4.def"},
       {Building::EXTRA_CAPITOL, "TBRMEXT5.def"},
       {Building::HORDE_1, "TBRMHRD1.def"},
       {Building::HORDE_1_UPGR, "TBRMHRD2.def"},
       {Building::HORDE_2, "TBRMHRD3.def"},
       {Building::HORDE_2_UPGR, "TBRMHRD4.def"},
       {Building::DWELLING_LEVEL_1, "TBRMDW_0.def"},
       {Building::DWELLING_LEVEL_2, "TBRMDW_1.def"},
       {Building::DWELLING_LEVEL_3, "TBRMDW_2.def"},
       {Building::DWELLING_LEVEL_4, "TBRMDW_3.def"},
       {Building::DWELLING_LEVEL_5, "TBRMDW_4.def"},
       {Building::DWELLING_LEVEL_6, "TBRMDW_5.def"},
       {Building::DWELLING_LEVEL_7, "TBRMDW_6.def"},
       {Building::DWELLING_UPGRADE_LEVEL_1, "TBRMUP_0.def"},
       {Building::DWELLING_UPGRADE_LEVEL_2, "TBRMUP_1.def"},
       {Building::DWELLING_UPGRADE_LEVEL_3, "TBRMUP_2.def"},
       {Building::DWELLING_UPGRADE_LEVEL_4, "TBRMUP_3.def"},
       {Building::DWELLING_UPGRADE_LEVEL_5, "TBRMUP_4.def"},
       {Building::DWELLING_UPGRADE_LEVEL_6, "TBRMUP_5.def"},
       {Building::DWELLING_UPGRADE_LEVEL_7, "TBRMUP_6.def"}},
      {// 塔楼 (2)
       {Building::MAGE_GUILD_1, "TBTWMAGE.def"},
       {Building::MAGE_GUILD_2, "TBTWMAG2.def"},
       {Building::MAGE_GUILD_3, "TBTWMAG3.def"},
       {Building::MAGE_GUILD_4, "TBTWMAG4.def"},
       {Building::MAGE_GUILD_5, "TBTWMAG5.def"},
       {Building::TAVERN, "TBTWTVRN.def"},
       {Building::FORT, "TBTWCSTL.def"},
       {Building::CITADEL, "TBTWCAS2.def"},
       {Building::CASTLE, "TBTWCAS3.def"},
       {Building::VILLAGE_HALL, "TBTWHALL.def"},
       {Building::TOWN_HALL, "TBTWHAL2.def"},
       {Building::CITY_HALL, "TBTWHAL3.def"},
       {Building::CAPITOL, "TBTWHAL4.def"},
       {Building::MARKETPLACE, "TBTWMARK.def"},
       {Building::RESOURCE_SILO, "TBTWSILO.def"},
       {Building::BLACKSMITH, "TBTWBLAK.def"},
       {Building::SPECIAL_10, "TBTWSPEC.def"}, // special1 for tower
       {Building::HORDE_1, "TBTWHRD1.def"},
       {Building::HORDE_1_UPGR, "TBTWHRD2.def"},
       {Building::SPECIAL_20, "TBTWEXT0.def"}, // special2 for tower
       {Building::SPECIAL_18, "TBTWEXT1.def"}, // special3 for tower
       {Building::SPECIAL_19, "TBTWEXT2.def"}, // special4 for tower
       {Building::GRAIL, "TBTWHOLY.def"},
       {Building::DWELLING_LEVEL_1, "TBTWDW_0.def"},
       {Building::DWELLING_LEVEL_2, "TBTWDW_1.def"},
       {Building::DWELLING_LEVEL_3, "TBTWDW_2.def"},
       {Building::DWELLING_LEVEL_4, "TBTWDW_3.def"},
       {Building::DWELLING_LEVEL_5, "TBTWDW_4.def"},
       {Building::DWELLING_LEVEL_6, "TBTWDW_5.def"},
       {Building::DWELLING_LEVEL_7, "TBTWDW_6.def"},
       {Building::DWELLING_UPGRADE_LEVEL_1, "TBTWUP_0.def"},
       {Building::DWELLING_UPGRADE_LEVEL_2, "TBTWUP_1.def"},
       {Building::DWELLING_UPGRADE_LEVEL_3, "TBTWUP_2.def"},
       {Building::DWELLING_UPGRADE_LEVEL_4, "TBTWUP_3.def"},
       {Building::DWELLING_UPGRADE_LEVEL_5, "TBTWUP_4.def"},
       {Building::DWELLING_UPGRADE_LEVEL_6, "TBTWUP_5.def"},
       {Building::DWELLING_UPGRADE_LEVEL_7, "TBTWUP_6.def"}},
      {// 地狱 (3)
       {Building::MAGE_GUILD_1, "TBINMAGE.def"},
       {Building::MAGE_GUILD_2, "TBINMAG2.def"},
       {Building::MAGE_GUILD_3, "TBINMAG3.def"},
       {Building::MAGE_GUILD_4, "TBINMAG4.def"},
       {Building::MAGE_GUILD_5, "TBINMAG5.def"},
       {Building::TAVERN, "TBINTVRN.def"},
       {Building::FORT, "TBINCSTL.def"},
       {Building::CITADEL, "TBINCAS2.def"},
       {Building::CASTLE, "TBINCAS3.def"},
       {Building::VILLAGE_HALL, "TBINHALL.def"},
       {Building::TOWN_HALL, "TBINHAL2.def"},
       {Building::CITY_HALL, "TBINHAL3.def"},
       {Building::CAPITOL, "TBINHAL4.def"},
       {Building::MARKETPLACE, "TBINMARK.def"},
       {Building::RESOURCE_SILO, "TBINSILO.def"},
       {Building::BLACKSMITH, "TBINBLAK.def"},
       {Building::SPECIAL_18, "TBINEXT0.def"}, // special2 for inferno
       {Building::SPECIAL_19, "TBINEXT1.def"}, // special3 for inferno
       {Building::SPECIAL_20, "TBINEXT2.def"}, // special4 for inferno
       {Building::HORDE_1, "TBINHRD1.def"},
       {Building::HORDE_1_UPGR, "TBINHRD2.def"},
       {Building::HORDE_2, "TBINHRD3.def"},
       {Building::HORDE_2_UPGR, "TBINHRD4.def"},
       {Building::GRAIL, "TBINHOLY.def"},
       {Building::DWELLING_LEVEL_1, "TBINDW_0.def"},
       {Building::DWELLING_LEVEL_2, "TBINDW_1.def"},
       {Building::DWELLING_LEVEL_3, "TBINDW_2.def"},
       {Building::DWELLING_LEVEL_4, "TBINDW_3.def"},
       {Building::DWELLING_LEVEL_5, "TBINDW_4.def"},
       {Building::DWELLING_LEVEL_6, "TBINDW_5.def"},
       {Building::DWELLING_LEVEL_7, "TBINDW_6.def"},
       {Building::DWELLING_UPGRADE_LEVEL_1, "TBINUP_0.def"},
       {Building::DWELLING_UPGRADE_LEVEL_2, "TBINUP_1.def"},
       {Building::DWELLING_UPGRADE_LEVEL_3, "TBINUP_2.def"},
       {Building::DWELLING_UPGRADE_LEVEL_4, "TBINUP_3.def"},
       {Building::DWELLING_UPGRADE_LEVEL_5, "TBINUP_4.def"},
       {Building::DWELLING_UPGRADE_LEVEL_6, "TBINUP_5.def"},
       {Building::DWELLING_UPGRADE_LEVEL_7, "TBINUP_6.def"}},
      {// 墓园 (4)
       {Building::EXTRA_ANIMATION, "TBNCEXT2.def"},
       {Building::MAGE_GUILD_1, "TBNCMAGE.def"},
       {Building::MAGE_GUILD_2, "TBNCMAG2.def"},
       {Building::MAGE_GUILD_3, "TBNCMAG3.def"},
       {Building::MAGE_GUILD_4, "TBNCMAG4.def"},
       {Building::MAGE_GUILD_5, "TBNCMAG5.def"},
       {Building::TAVERN, "TBNCTVRN.def"},
       {Building::SHIPYARD, "TBNCDOCK.def"},
       {Building::FORT, "TBNCCSTL.def"},
       {Building::CITADEL, "TBNCCAS2.def"},
       {Building::CASTLE, "TBNCCAS3.def"},
       {Building::VILLAGE_HALL, "TBNCHALL.def"},
       {Building::TOWN_HALL, "TBNCHAL2.def"},
       {Building::CITY_HALL, "TBNCHAL3.def"},
       {Building::CAPITOL, "TBNCHAL4.def"},
       {Building::MARKETPLACE, "TBNCMARK.def"},
       {Building::RESOURCE_SILO, "TBNCSILO.def"},
       {Building::BLACKSMITH, "TBNCBLAK.def"},
       {Building::SPECIAL_18, "TBNCSPEC.def"}, // special1 for necropolis
       {Building::HORDE_1, "TBNCHRD1.def"},
       {Building::HORDE_1_UPGR, "TBNCHRD2.def"},
       {Building::SHIP, "TBNCBOAT.def"},
       {Building::SPECIAL_19, "TBNCEXT0.def"}, // special2 for necropolis
       {Building::SPECIAL_20, "TBNCEXT1.def"}, // special3 for necropolis
       {Building::GRAIL, "TBNCHOLY.def"},
       {Building::EXTRA_TOWN_HALL, "TBNCEXT3.def"},
       {Building::EXTRA_CITY_HALL, "TBNCEXT4.def"},
       {Building::EXTRA_CAPITOL, "TBNCEXT5.def"},
       {Building::DWELLING_LEVEL_1, "TBNCDW_0.def"},
       {Building::DWELLING_LEVEL_2, "TBNCDW_1.def"},
       {Building::DWELLING_LEVEL_3, "TBNCDW_2.def"},
       {Building::DWELLING_LEVEL_4, "TBNCDW_3.def"},
       {Building::DWELLING_LEVEL_5, "TBNCDW_4.def"},
       {Building::DWELLING_LEVEL_6, "TBNCDW_5.def"},
       {Building::DWELLING_LEVEL_7, "TBNCDW_6.def"},
       {Building::DWELLING_UPGRADE_LEVEL_1, "TBNCUP_0.def"},
       {Building::DWELLING_UPGRADE_LEVEL_2, "TBNCUP_1.def"},
       {Building::DWELLING_UPGRADE_LEVEL_3, "TBNCUP_2.def"},
       {Building::DWELLING_UPGRADE_LEVEL_4, "TBNCUP_3.def"},
       {Building::DWELLING_UPGRADE_LEVEL_5, "TBNCUP_4.def"},
       {Building::DWELLING_UPGRADE_LEVEL_6, "TBNCUP_5.def"},
       {Building::DWELLING_UPGRADE_LEVEL_7, "TBNCUP_6.def"}},
      {// 地牢 (5)
       {Building::MAGE_GUILD_1, "TBDNMAGE.def"},
       {Building::MAGE_GUILD_2, "TBDNMAG2.def"},
       {Building::MAGE_GUILD_3, "TBDNMAG3.def"},
       {Building::MAGE_GUILD_4, "TBDNMAG4.def"},
       {Building::MAGE_GUILD_5, "TBDNMAG5.def"},
       {Building::TAVERN, "TBDNTVRN.def"},
       {Building::FORT, "TBDNCSTL.def"},
       {Building::CITADEL, "TBDNCAS2.def"},
       {Building::CASTLE, "TBDNCAS3.def"},
       {Building::VILLAGE_HALL, "TBDNHALL.def"},
       {Building::TOWN_HALL, "TBDNHAL2.def"},
       {Building::CITY_HALL, "TBDNHAL3.def"},
       {Building::CAPITOL, "TBDNHAL4.def"},
       {Building::MARKETPLACE, "TBDNMARK.def"},
       {Building::RESOURCE_SILO, "TBDNSILO.def"},
       {Building::BLACKSMITH, "TBDNBLAK.def"},
       {Building::SPECIAL_10, "TBDNSPEC.def"}, // special1 for dungeon
       {Building::HORDE_1, "TBDNHRD1.def"},
       {Building::HORDE_1_UPGR, "TBDNHRD2.def"},
       {Building::SPECIAL_18, "TBDNEXT0.def"}, // special2 for dungeon
       {Building::SPECIAL_19, "TBDNEXT1.def"}, // special3 for dungeon
       {Building::SPECIAL_20, "TBDNEXT2.def"}, // special4 for dungeon
       {Building::GRAIL, "TBDNHOLY.def"},
       {Building::DWELLING_LEVEL_1, "TBDNDW_0.def"},
       {Building::DWELLING_LEVEL_2, "TBDNDW_1.def"},
       {Building::DWELLING_LEVEL_3, "TBDNDW_2.def"},
       {Building::DWELLING_LEVEL_4, "TBDNDW_3.def"},
       {Building::DWELLING_LEVEL_5, "TBDNDW_4.def"},
       {Building::DWELLING_LEVEL_6, "TBDNDW_5.def"},
       {Building::DWELLING_LEVEL_7, "TBDNDW_6.def"},
       {Building::DWELLING_UPGRADE_LEVEL_1, "TBDNUP_0.def"},
       {Building::DWELLING_UPGRADE_LEVEL_2, "TBDNUP_1.def"},
       {Building::DWELLING_UPGRADE_LEVEL_3, "TBDNUP_2.def"},
       {Building::DWELLING_UPGRADE_LEVEL_4, "TBDNUP_3.def"},
       {Building::DWELLING_UPGRADE_LEVEL_5, "TBDNUP_4.def"},
       {Building::DWELLING_UPGRADE_LEVEL_6, "TBDNUP_5.def"},
       {Building::DWELLING_UPGRADE_LEVEL_7, "TBDNUP_6.def"}},
      {// 据点 (6)
       {Building::EXTRA_ANIMATION, "TBSTEXT3.def"},
       {Building::MAGE_GUILD_1, "TBSTMAGE.def"},
       {Building::MAGE_GUILD_2, "TBSTMAG2.def"},
       {Building::MAGE_GUILD_3, "TBSTMAG3.def"},
       {Building::TAVERN, "TBSTTVRN.def"},
       {Building::FORT, "TBSTCSTL.def"},
       {Building::CITADEL, "TBSTCAS2.def"},
       {Building::CASTLE, "TBSTCAS3.def"},
       {Building::VILLAGE_HALL, "TBSTHALL.def"},
       {Building::TOWN_HALL, "TBSTHAL2.def"},
       {Building::CITY_HALL, "TBSTHAL3.def"},
       {Building::CAPITOL, "TBSTHAL4.def"},
       {Building::MARKETPLACE, "TBSTMARK.def"},
       {Building::RESOURCE_SILO, "TBSTSILO.def"},
       {Building::BLACKSMITH, "TBSTBLAK.def"},
       {Building::SPECIAL_18, "TBSTSPEC.def"}, // special1 for stronghold
       {Building::HORDE_1, "TBSTHRD1.def"},
       {Building::HORDE_1_UPGR, "TBSTHRD2.def"},
       {Building::SPECIAL_21, "TBSTEXT0.def"}, // special2 for stronghold
       {Building::SPECIAL_19, "TBSTEXT1.def"}, // special3 for stronghold
       {Building::SPECIAL_20, "TBSTEXT2.def"}, // special4 for stronghold
       {Building::GRAIL, "TBSTHOLY.def"},
       {Building::DWELLING_LEVEL_1, "TBSTDW_0.def"},
       {Building::DWELLING_LEVEL_2, "TBSTDW_1.def"},
       {Building::DWELLING_LEVEL_3, "TBSTDW_2.def"},
       {Building::DWELLING_LEVEL_4, "TBSTDW_3.def"},
       {Building::DWELLING_LEVEL_5, "TBSTDW_4.def"},
       {Building::DWELLING_LEVEL_6, "TBSTDW_5.def"},
       {Building::DWELLING_LEVEL_7, "TBSTDW_6.def"},
       {Building::DWELLING_UPGRADE_LEVEL_1, "TBSTUP_0.def"},
       {Building::DWELLING_UPGRADE_LEVEL_2, "TBSTUP_1.def"},
       {Building::DWELLING_UPGRADE_LEVEL_3, "TBSTUP_2.def"},
       {Building::DWELLING_UPGRADE_LEVEL_4, "TBSTUP_3.def"},
       {Building::DWELLING_UPGRADE_LEVEL_5, "TBSTUP_4.def"},
       {Building::DWELLING_UPGRADE_LEVEL_6, "TBSTUP_5.def"},
       {Building::DWELLING_UPGRADE_LEVEL_7, "TBSTUP_6.def"}},
      {// 要塞 (7)
       {Building::EXTRA_ANIMATION, "TBFREXT2.def"},
       {Building::MAGE_GUILD_1, "TBFRMAGE.def"},
       {Building::MAGE_GUILD_2, "TBFRMAG2.def"},
       {Building::MAGE_GUILD_3, "TBFRMAG3.def"},
       {Building::TAVERN, "TBFRTVRN.def"},
       {Building::SHIPYARD, "TBFRDOCK.def"},
       {Building::FORT, "TBFRCSTL.def"},
       {Building::CITADEL, "TBFRCAS2.def"},
       {Building::CASTLE, "TBFRCAS3.def"},
       {Building::VILLAGE_HALL, "TBFRHALL.def"},
       {Building::TOWN_HALL, "TBFRHAL2.def"},
       {Building::CITY_HALL, "TBFRHAL3.def"},
       {Building::CAPITOL, "TBFRHAL4.def"},
       {Building::MARKETPLACE, "TBFRMARK.def"},
       {Building::RESOURCE_SILO, "TBFRSILO.def"},
       {Building::BLACKSMITH, "TBFRBLAK.def"},
       {Building::SPECIAL_20, "TBFRSPEC.def"}, // special1 for fortress
       {Building::HORDE_1, "TBFRHRD1.def"},
       {Building::HORDE_1_UPGR, "TBFRHRD2.def"},
       {Building::SHIP, "TBFRBOAT.def"},
       {Building::SPECIAL_19, "TBFREXT0.def"}, // special2 for fortress
       {Building::SPECIAL_18, "TBFREXT1.def"}, // special3 for fortress
       {Building::GRAIL, "TBFRHOLY.def"},
       {Building::EXTRA_CAPITOL, "TBFRWTRW.def"},
       {Building::DWELLING_LEVEL_1, "TBFRDW_0.def"},
       {Building::DWELLING_LEVEL_2, "TBFRDW_1.def"},
       {Building::DWELLING_LEVEL_3, "TBFRDW_3.def"},
       {Building::DWELLING_LEVEL_4, "TBFRDW_4.def"},
       {Building::DWELLING_LEVEL_5, "TBFRDW_2.def"},
       {Building::DWELLING_LEVEL_6, "TBFRDW_5.def"},
       {Building::DWELLING_LEVEL_7, "TBFRDW_6.def"},
       {Building::DWELLING_UPGRADE_LEVEL_1, "TBFRUP_0.def"},
       {Building::DWELLING_UPGRADE_LEVEL_2, "TBFRUP_1.def"},
       {Building::DWELLING_UPGRADE_LEVEL_3, "TBFRUP_3.def"},
       {Building::DWELLING_UPGRADE_LEVEL_4, "TBFRUP_4.def"},
       {Building::DWELLING_UPGRADE_LEVEL_5, "TBFRUP_2.def"},
       {Building::DWELLING_UPGRADE_LEVEL_6, "TBFRUP_5.def"},
       {Building::DWELLING_UPGRADE_LEVEL_7, "TBFRUP_6.def"}}};

  const static inline std::unordered_set<uint8_t> townDefaultAni[] = {
      {(uint8_t)Building::EXTRA_ANIMATION}, // 0
      {(uint8_t)Building::EXTRA_ANIMATION}, // 1
      {},                          // 2
      {},                          // 3
      {(uint8_t)Building::EXTRA_ANIMATION}, // 4
      {},                          // 5
      {},                          // 6
      {(uint8_t)Building::EXTRA_ANIMATION}  // 7
  };

  const static inline std::vector<std::vector<std::vector<uint8_t>>>
      townHallSlots[] = {
          {// Castle (0)
           {{(uint8_t)Building::VILLAGE_HALL, (uint8_t)Building::TOWN_HALL,
             (uint8_t)Building::CITY_HALL, (uint8_t)Building::CAPITOL},
            {(uint8_t)Building::FORT, (uint8_t)Building::CITADEL,
             (uint8_t)Building::CASTLE},
            {(uint8_t)Building::TAVERN,
             (uint8_t)Building::SPECIAL_19}, // special3 for castle
            {(uint8_t)Building::BLACKSMITH}},
           {
               {(uint8_t)Building::MARKETPLACE,
                (uint8_t)Building::RESOURCE_SILO},
               {(uint8_t)Building::MAGE_GUILD_1,
                (uint8_t)Building::MAGE_GUILD_2,
                (uint8_t)Building::MAGE_GUILD_3,
                (uint8_t)Building::MAGE_GUILD_4},
               {(uint8_t)Building::SHIPYARD,
                (uint8_t)Building::SPECIAL_18} // special1 for castle
           },
           {{(uint8_t)Building::SPECIAL_20}, // special2 for castle
            {(uint8_t)Building::HORDE_1}},
           {{(uint8_t)Building::DWELLING_LEVEL_1,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_1},
            {(uint8_t)Building::DWELLING_LEVEL_2,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_2},
            {(uint8_t)Building::DWELLING_LEVEL_3,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_3},
            {(uint8_t)Building::DWELLING_LEVEL_4,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_4}},
           {{(uint8_t)Building::DWELLING_LEVEL_5,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_5},
            {(uint8_t)Building::DWELLING_LEVEL_6,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_6},
            {(uint8_t)Building::DWELLING_LEVEL_7,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_7}}},
          {// Rampart (1)
           {{(uint8_t)Building::VILLAGE_HALL, (uint8_t)Building::TOWN_HALL,
             (uint8_t)Building::CITY_HALL, (uint8_t)Building::CAPITOL},
            {(uint8_t)Building::FORT, (uint8_t)Building::CITADEL,
             (uint8_t)Building::CASTLE},
            {(uint8_t)Building::TAVERN},
            {(uint8_t)Building::BLACKSMITH}},
           {
               {(uint8_t)Building::MARKETPLACE,
                (uint8_t)Building::RESOURCE_SILO},
               {(uint8_t)Building::MAGE_GUILD_1,
                (uint8_t)Building::MAGE_GUILD_2,
                (uint8_t)Building::MAGE_GUILD_3,
                (uint8_t)Building::MAGE_GUILD_4,
                (uint8_t)Building::MAGE_GUILD_5},
               {(uint8_t)Building::SPECIAL_18,
                (uint8_t)Building::SPECIAL_20} // special1, special2 for rampart
           },
           {{(uint8_t)Building::SPECIAL_19}, // special3 for rampart
            {(uint8_t)Building::HORDE_2},
            {(uint8_t)Building::HORDE_1}},
           {{(uint8_t)Building::DWELLING_LEVEL_1,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_1},
            {(uint8_t)Building::DWELLING_LEVEL_2,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_2},
            {(uint8_t)Building::DWELLING_LEVEL_3,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_3},
            {(uint8_t)Building::DWELLING_LEVEL_4,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_4}},
           {{(uint8_t)Building::DWELLING_LEVEL_5,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_5},
            {(uint8_t)Building::DWELLING_LEVEL_6,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_6},
            {(uint8_t)Building::DWELLING_LEVEL_7,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_7}}},
          {// Tower (2)
           {{(uint8_t)Building::VILLAGE_HALL, (uint8_t)Building::TOWN_HALL,
             (uint8_t)Building::CITY_HALL, (uint8_t)Building::CAPITOL},
            {(uint8_t)Building::FORT, (uint8_t)Building::CITADEL,
             (uint8_t)Building::CASTLE},
            {(uint8_t)Building::TAVERN},
            {(uint8_t)Building::BLACKSMITH}},
           {
               {(uint8_t)Building::MARKETPLACE,
                (uint8_t)Building::RESOURCE_SILO},
               {(uint8_t)Building::MAGE_GUILD_1,
                (uint8_t)Building::MAGE_GUILD_2,
                (uint8_t)Building::MAGE_GUILD_3,
                (uint8_t)Building::MAGE_GUILD_4,
                (uint8_t)Building::MAGE_GUILD_5},
               {(uint8_t)Building::SPECIAL_19}, // special3 for tower
               {(uint8_t)Building::SPECIAL_20}  // special4 for tower
           },
           {{(uint8_t)Building::SPECIAL_10}, // special1 for tower
            {(uint8_t)Building::SPECIAL_18}, // special2 for tower
            {(uint8_t)Building::HORDE_1}},
           {{(uint8_t)Building::DWELLING_LEVEL_1,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_1},
            {(uint8_t)Building::DWELLING_LEVEL_2,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_2},
            {(uint8_t)Building::DWELLING_LEVEL_3,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_3},
            {(uint8_t)Building::DWELLING_LEVEL_4,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_4}},
           {{(uint8_t)Building::DWELLING_LEVEL_5,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_5},
            {(uint8_t)Building::DWELLING_LEVEL_6,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_6},
            {(uint8_t)Building::DWELLING_LEVEL_7,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_7}}},
          {// Inferno (3)
           {{(uint8_t)Building::VILLAGE_HALL, (uint8_t)Building::TOWN_HALL,
             (uint8_t)Building::CITY_HALL, (uint8_t)Building::CAPITOL},
            {(uint8_t)Building::FORT, (uint8_t)Building::CITADEL,
             (uint8_t)Building::CASTLE},
            {(uint8_t)Building::TAVERN},
            {(uint8_t)Building::BLACKSMITH}},
           {
               {(uint8_t)Building::MARKETPLACE,
                (uint8_t)Building::RESOURCE_SILO},
               {(uint8_t)Building::MAGE_GUILD_1,
                (uint8_t)Building::MAGE_GUILD_2,
                (uint8_t)Building::MAGE_GUILD_3,
                (uint8_t)Building::MAGE_GUILD_4,
                (uint8_t)Building::MAGE_GUILD_5},
               {(uint8_t)Building::SPECIAL_20}, // special4 for inferno
               {(uint8_t)Building::SPECIAL_18}  // special2 for inferno
           },
           {{(uint8_t)Building::SPECIAL_19}, // special3 for inferno
            {(uint8_t)Building::HORDE_1},
            {(uint8_t)Building::HORDE_2}},
           {{(uint8_t)Building::DWELLING_LEVEL_1,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_1},
            {(uint8_t)Building::DWELLING_LEVEL_2,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_2},
            {(uint8_t)Building::DWELLING_LEVEL_3,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_3},
            {(uint8_t)Building::DWELLING_LEVEL_4,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_4}},
           {{(uint8_t)Building::DWELLING_LEVEL_5,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_5},
            {(uint8_t)Building::DWELLING_LEVEL_6,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_6},
            {(uint8_t)Building::DWELLING_LEVEL_7,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_7}}},
          {// Necropolis (4)
           {{(uint8_t)Building::VILLAGE_HALL, (uint8_t)Building::TOWN_HALL,
             (uint8_t)Building::CITY_HALL, (uint8_t)Building::CAPITOL},
            {(uint8_t)Building::FORT, (uint8_t)Building::CITADEL,
             (uint8_t)Building::CASTLE},
            {(uint8_t)Building::TAVERN},
            {(uint8_t)Building::BLACKSMITH}},
           {{(uint8_t)Building::MARKETPLACE, (uint8_t)Building::RESOURCE_SILO},
            {(uint8_t)Building::MAGE_GUILD_1, (uint8_t)Building::MAGE_GUILD_2,
             (uint8_t)Building::MAGE_GUILD_3, (uint8_t)Building::MAGE_GUILD_4,
             (uint8_t)Building::MAGE_GUILD_5},
            {(uint8_t)Building::SPECIAL_18}, // special2 for necropolis
            {(uint8_t)Building::SHIPYARD}},
           {{(uint8_t)Building::SPECIAL_10}, // special1 for necropolis
            {(uint8_t)Building::SPECIAL_19}, // special3 for necropolis
            {(uint8_t)Building::HORDE_1}},
           {{(uint8_t)Building::DWELLING_LEVEL_1,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_1},
            {(uint8_t)Building::DWELLING_LEVEL_2,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_2},
            {(uint8_t)Building::DWELLING_LEVEL_3,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_3},
            {(uint8_t)Building::DWELLING_LEVEL_4,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_4}},
           {{(uint8_t)Building::DWELLING_LEVEL_5,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_5},
            {(uint8_t)Building::DWELLING_LEVEL_6,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_6},
            {(uint8_t)Building::DWELLING_LEVEL_7,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_7}}},
          {// Dungeon (5)
           {{(uint8_t)Building::VILLAGE_HALL, (uint8_t)Building::TOWN_HALL,
             (uint8_t)Building::CITY_HALL, (uint8_t)Building::CAPITOL},
            {(uint8_t)Building::FORT, (uint8_t)Building::CITADEL,
             (uint8_t)Building::CASTLE},
            {(uint8_t)Building::TAVERN},
            {(uint8_t)Building::BLACKSMITH}},
           {
               {(uint8_t)Building::MARKETPLACE,
                (uint8_t)Building::RESOURCE_SILO},
               {(uint8_t)Building::MAGE_GUILD_1,
                (uint8_t)Building::MAGE_GUILD_2,
                (uint8_t)Building::MAGE_GUILD_3,
                (uint8_t)Building::MAGE_GUILD_4,
                (uint8_t)Building::MAGE_GUILD_5},
               {(uint8_t)Building::SPECIAL_18}, // special2 for dungeon
               {(uint8_t)Building::SPECIAL_19}  // special3 for dungeon
           },
           {{(uint8_t)Building::SPECIAL_10}, // special1 for dungeon
            {(uint8_t)Building::SPECIAL_20}, // special4 for dungeon
            {(uint8_t)Building::HORDE_1}},
           {{(uint8_t)Building::DWELLING_LEVEL_1,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_1},
            {(uint8_t)Building::DWELLING_LEVEL_2,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_2},
            {(uint8_t)Building::DWELLING_LEVEL_3,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_3},
            {(uint8_t)Building::DWELLING_LEVEL_4,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_4}},
           {{(uint8_t)Building::DWELLING_LEVEL_5,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_5},
            {(uint8_t)Building::DWELLING_LEVEL_6,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_6},
            {(uint8_t)Building::DWELLING_LEVEL_7,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_7}}},
          {// Stronghold (6)
           {{(uint8_t)Building::VILLAGE_HALL, (uint8_t)Building::TOWN_HALL,
             (uint8_t)Building::CITY_HALL, (uint8_t)Building::CAPITOL},
            {(uint8_t)Building::FORT, (uint8_t)Building::CITADEL,
             (uint8_t)Building::CASTLE},
            {(uint8_t)Building::TAVERN},
            {(uint8_t)Building::BLACKSMITH}},
           {
               {(uint8_t)Building::MARKETPLACE,
                (uint8_t)Building::RESOURCE_SILO},
               {(uint8_t)Building::MAGE_GUILD_1,
                (uint8_t)Building::MAGE_GUILD_2,
                (uint8_t)Building::MAGE_GUILD_3},
               {(uint8_t)Building::SPECIAL_20}, // special4 for stronghold
               {(uint8_t)Building::SPECIAL_18}  // special1 for stronghold
           },
           {{(uint8_t)Building::SPECIAL_19}, // special2 for stronghold
            {(uint8_t)Building::SPECIAL_21}, // special3 for stronghold
            {(uint8_t)Building::HORDE_1}},
           {{(uint8_t)Building::DWELLING_LEVEL_1,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_1},
            {(uint8_t)Building::DWELLING_LEVEL_2,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_2},
            {(uint8_t)Building::DWELLING_LEVEL_3,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_3},
            {(uint8_t)Building::DWELLING_LEVEL_4,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_4}},
           {{(uint8_t)Building::DWELLING_LEVEL_5,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_5},
            {(uint8_t)Building::DWELLING_LEVEL_6,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_6},
            {(uint8_t)Building::DWELLING_LEVEL_7,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_7}}},
          {// Fortress (7)
           {{(uint8_t)Building::VILLAGE_HALL, (uint8_t)Building::TOWN_HALL,
             (uint8_t)Building::CITY_HALL, (uint8_t)Building::CAPITOL},
            {(uint8_t)Building::FORT, (uint8_t)Building::CITADEL,
             (uint8_t)Building::CASTLE},
            {(uint8_t)Building::TAVERN},
            {(uint8_t)Building::BLACKSMITH}},
           {{(uint8_t)Building::MARKETPLACE, (uint8_t)Building::RESOURCE_SILO},
            {(uint8_t)Building::MAGE_GUILD_1, (uint8_t)Building::MAGE_GUILD_2,
             (uint8_t)Building::MAGE_GUILD_3},
            {(uint8_t)Building::SHIPYARD}},
           {{(uint8_t)Building::SPECIAL_20}, // special1 for fortress
            {(uint8_t)Building::SPECIAL_19,
             (uint8_t)Building::SPECIAL_18}, // special2, special3 for fortress
            {(uint8_t)Building::HORDE_1}},
           {{(uint8_t)Building::DWELLING_LEVEL_1,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_1},
            {(uint8_t)Building::DWELLING_LEVEL_2,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_2},
            {(uint8_t)Building::DWELLING_LEVEL_3,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_3},
            {(uint8_t)Building::DWELLING_LEVEL_4,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_4}},
           {{(uint8_t)Building::DWELLING_LEVEL_5,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_5},
            {(uint8_t)Building::DWELLING_LEVEL_6,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_6},
            {(uint8_t)Building::DWELLING_LEVEL_7,
             (uint8_t)Building::DWELLING_UPGRADE_LEVEL_7}}}};

  const static inline std::vector<Building> townZ[] = {
      {
          // 城堡 (0)
          Building::GRAIL,
          Building::FORT,
          Building::CITADEL,
          Building::CASTLE,
          Building::SPECIAL_18, // special1 (18 -> special1)
          Building::SHIPYARD,
          Building::SHIP,
          Building::SPECIAL_20, // special2 (20 -> special2)
          Building::DWELLING_LEVEL_7,
          Building::DWELLING_UPGRADE_LEVEL_7,
          Building::HORDE_1,
          Building::HORDE_1_UPGR,
          Building::DWELLING_LEVEL_1,
          Building::DWELLING_LEVEL_3,
          Building::DWELLING_LEVEL_6,
          Building::DWELLING_UPGRADE_LEVEL_1,
          Building::DWELLING_UPGRADE_LEVEL_3,
          Building::DWELLING_UPGRADE_LEVEL_6,
          Building::MARKETPLACE,
          Building::BLACKSMITH,
          Building::DWELLING_LEVEL_2,
          Building::DWELLING_LEVEL_4,
          Building::DWELLING_UPGRADE_LEVEL_2,
          Building::DWELLING_UPGRADE_LEVEL_4,
          Building::EXTRA_ANIMATION,
          Building::MAGE_GUILD_1,
          Building::MAGE_GUILD_2,
          Building::MAGE_GUILD_3,
          Building::MAGE_GUILD_4,
          Building::VILLAGE_HALL,
          Building::TOWN_HALL,
          Building::CITY_HALL,
          Building::CAPITOL,
          Building::RESOURCE_SILO,
          Building::DWELLING_LEVEL_5,
          Building::DWELLING_UPGRADE_LEVEL_5,
          Building::TAVERN,
          Building::SPECIAL_19 // special3 (19 -> special3)
      },
      {// 壁垒 (1)
       Building::DWELLING_LEVEL_7,
       Building::DWELLING_UPGRADE_LEVEL_7,
       Building::FORT,
       Building::CITADEL,
       Building::CASTLE,
       Building::BLACKSMITH,
       Building::GRAIL,
       Building::HORDE_1,
       Building::HORDE_1_UPGR,
       Building::DWELLING_LEVEL_2,
       Building::DWELLING_UPGRADE_LEVEL_2,
       Building::DWELLING_LEVEL_6,
       Building::DWELLING_UPGRADE_LEVEL_6,
       Building::MAGE_GUILD_1,
       Building::MAGE_GUILD_2,
       Building::MAGE_GUILD_3,
       Building::MAGE_GUILD_4,
       Building::MAGE_GUILD_5,
       Building::HORDE_2,
       Building::HORDE_2_UPGR,
       Building::DWELLING_LEVEL_5,
       Building::DWELLING_UPGRADE_LEVEL_5,
       Building::DWELLING_LEVEL_3,
       Building::DWELLING_UPGRADE_LEVEL_3,
       Building::DWELLING_LEVEL_4,
       Building::DWELLING_UPGRADE_LEVEL_4,
       Building::SPECIAL_19, // special3 (19 -> special3)
       Building::TAVERN,
       Building::EXTRA_ANIMATION,
       Building::SPECIAL_18, // special1 (18 -> special1)
       Building::SPECIAL_20, // special2 (20 -> special2)
       Building::DWELLING_LEVEL_1,
       Building::DWELLING_UPGRADE_LEVEL_1,
       Building::EXTRA_TOWN_HALL,
       Building::MARKETPLACE,
       Building::EXTRA_CAPITOL,
       Building::RESOURCE_SILO},
      {// 塔楼 (2)
       Building::GRAIL,
       Building::FORT,
       Building::CITADEL,
       Building::CASTLE,
       Building::DWELLING_LEVEL_7,
       Building::DWELLING_UPGRADE_LEVEL_7,
       Building::SPECIAL_10, // special1 (10 -> special1)
       Building::SPECIAL_19, // special4 (19 -> special4)
       Building::TAVERN,
       Building::DWELLING_LEVEL_1,
       Building::DWELLING_LEVEL_3,
       Building::DWELLING_UPGRADE_LEVEL_1,
       Building::DWELLING_UPGRADE_LEVEL_3,
       Building::DWELLING_LEVEL_6,
       Building::DWELLING_UPGRADE_LEVEL_6,
       Building::RESOURCE_SILO,
       Building::MAGE_GUILD_1,
       Building::MAGE_GUILD_2,
       Building::MAGE_GUILD_3,
       Building::MAGE_GUILD_4,
       Building::MAGE_GUILD_5,
       Building::VILLAGE_HALL,
       Building::TOWN_HALL,
       Building::CITY_HALL,
       Building::CAPITOL,
       Building::MARKETPLACE,
       Building::BLACKSMITH,
       Building::DWELLING_LEVEL_2,
       Building::DWELLING_LEVEL_4,
       Building::DWELLING_UPGRADE_LEVEL_2,
       Building::DWELLING_UPGRADE_LEVEL_4,
       Building::DWELLING_LEVEL_5,
       Building::DWELLING_UPGRADE_LEVEL_5,
       Building::SPECIAL_20, // special2 (20 -> special2)
       Building::SPECIAL_18, // special3 (18 -> special3)
       Building::HORDE_1,
       Building::HORDE_1_UPGR},
      {
          // 地狱 (3)
          Building::SPECIAL_18, // special2 (18 -> special2)
          Building::DWELLING_LEVEL_7,
          Building::DWELLING_UPGRADE_LEVEL_7,
          Building::FORT,
          Building::CITADEL,
          Building::CASTLE,
          Building::SPECIAL_19, // special3 (19 -> special3)
          Building::GRAIL,
          Building::DWELLING_LEVEL_4,
          Building::DWELLING_UPGRADE_LEVEL_4,
          Building::DWELLING_LEVEL_5,
          Building::DWELLING_UPGRADE_LEVEL_5,
          Building::DWELLING_LEVEL_2,
          Building::DWELLING_UPGRADE_LEVEL_2,
          Building::MARKETPLACE,
          Building::DWELLING_LEVEL_6,
          Building::DWELLING_UPGRADE_LEVEL_6,
          Building::RESOURCE_SILO,
          Building::TAVERN,
          Building::BLACKSMITH,
          Building::HORDE_1,
          Building::HORDE_1_UPGR,
          Building::HORDE_2,
          Building::HORDE_2_UPGR,
          Building::DWELLING_LEVEL_1,
          Building::DWELLING_LEVEL_3,
          Building::DWELLING_UPGRADE_LEVEL_1,
          Building::DWELLING_UPGRADE_LEVEL_3,
          Building::MAGE_GUILD_1,
          Building::MAGE_GUILD_2,
          Building::MAGE_GUILD_3,
          Building::MAGE_GUILD_4,
          Building::MAGE_GUILD_5,
          Building::VILLAGE_HALL,
          Building::TOWN_HALL,
          Building::CITY_HALL,
          Building::CAPITOL,
          Building::SPECIAL_20 // special4 (20 -> special4)
      },
      {// 墓园 (4)
       Building::DWELLING_LEVEL_3,
       Building::DWELLING_UPGRADE_LEVEL_3,
       Building::EXTRA_ANIMATION,
       Building::SPECIAL_18, // special1 (18 -> special1)
       Building::MAGE_GUILD_1,
       Building::MAGE_GUILD_2,
       Building::MAGE_GUILD_3,
       Building::MAGE_GUILD_4,
       Building::MAGE_GUILD_5,
       Building::SHIPYARD,
       Building::SHIP,
       Building::SPECIAL_19, // special2 (19 -> special2)
       Building::VILLAGE_HALL,
       Building::TOWN_HALL,
       Building::CITY_HALL,
       Building::CAPITOL,
       Building::DWELLING_LEVEL_6,
       Building::DWELLING_UPGRADE_LEVEL_6,
       Building::RESOURCE_SILO,
       Building::DWELLING_LEVEL_2,
       Building::DWELLING_UPGRADE_LEVEL_2,
       Building::DWELLING_LEVEL_4,
       Building::DWELLING_UPGRADE_LEVEL_4,
       Building::MARKETPLACE,
       Building::DWELLING_LEVEL_5,
       Building::DWELLING_UPGRADE_LEVEL_5,
       Building::SPECIAL_20, // special3 (20 -> special3)
       Building::HORDE_1,
       Building::HORDE_1_UPGR,
       Building::DWELLING_LEVEL_1,
       Building::DWELLING_UPGRADE_LEVEL_1,
       Building::EXTRA_TOWN_HALL,
       Building::EXTRA_CITY_HALL,
       Building::EXTRA_CAPITOL,
       Building::BLACKSMITH,
       Building::FORT,
       Building::CITADEL,
       Building::CASTLE,
       Building::TAVERN,
       Building::GRAIL,
       Building::DWELLING_LEVEL_7,
       Building::DWELLING_UPGRADE_LEVEL_7},
      {// 地牢 (5)
       Building::BLACKSMITH,
       Building::DWELLING_LEVEL_4,
       Building::DWELLING_UPGRADE_LEVEL_4,
       Building::DWELLING_LEVEL_6,
       Building::DWELLING_UPGRADE_LEVEL_6,
       Building::DWELLING_LEVEL_7,
       Building::DWELLING_UPGRADE_LEVEL_7,
       Building::MAGE_GUILD_1,
       Building::MAGE_GUILD_2,
       Building::MAGE_GUILD_3,
       Building::MAGE_GUILD_4,
       Building::MAGE_GUILD_5,
       Building::MARKETPLACE,
       Building::SPECIAL_10, // special1 (10 -> special1)
       Building::DWELLING_LEVEL_3,
       Building::DWELLING_UPGRADE_LEVEL_3,
       Building::DWELLING_LEVEL_5,
       Building::DWELLING_UPGRADE_LEVEL_5,
       Building::GRAIL,
       Building::RESOURCE_SILO,
       Building::FORT,
       Building::CITADEL,
       Building::CASTLE,
       Building::HORDE_1,
       Building::HORDE_1_UPGR,
       Building::DWELLING_LEVEL_1,
       Building::DWELLING_UPGRADE_LEVEL_1,
       Building::TAVERN,
       Building::VILLAGE_HALL,
       Building::TOWN_HALL,
       Building::CITY_HALL,
       Building::CAPITOL,
       Building::SPECIAL_18, // special2 (18 -> special2)
       Building::SPECIAL_19, // special3 (19 -> special3)
       Building::SPECIAL_20, // special4 (20 -> special4)
       Building::DWELLING_LEVEL_2,
       Building::DWELLING_UPGRADE_LEVEL_2},
      {// 据点 (6)
       Building::DWELLING_LEVEL_6,
       Building::DWELLING_UPGRADE_LEVEL_6,
       Building::MAGE_GUILD_1,
       Building::MAGE_GUILD_2,
       Building::MAGE_GUILD_3,
       Building::SPECIAL_21, // special4 (21 -> special4)
       Building::FORT,
       Building::CITADEL,
       Building::CASTLE,
       Building::DWELLING_LEVEL_5,
       Building::DWELLING_UPGRADE_LEVEL_5,
       Building::MARKETPLACE,
       Building::SPECIAL_18, // special1 (18 -> special1)
       Building::DWELLING_LEVEL_2,
       Building::DWELLING_UPGRADE_LEVEL_2,
       Building::DWELLING_LEVEL_3,
       Building::DWELLING_UPGRADE_LEVEL_3,
       Building::RESOURCE_SILO,
       Building::SPECIAL_19, // special3 (19 -> special3)
       Building::TAVERN,
       Building::GRAIL,
       Building::SPECIAL_20, // special2 (20 -> special2)
       Building::HORDE_1,
       Building::HORDE_1_UPGR,
       Building::DWELLING_LEVEL_1,
       Building::DWELLING_UPGRADE_LEVEL_1,
       Building::VILLAGE_HALL,
       Building::TOWN_HALL,
       Building::CITY_HALL,
       Building::CAPITOL,
       Building::BLACKSMITH,
       Building::DWELLING_LEVEL_4,
       Building::DWELLING_UPGRADE_LEVEL_4,
       Building::DWELLING_LEVEL_7,
       Building::DWELLING_UPGRADE_LEVEL_7,
       Building::EXTRA_ANIMATION},
      {                      // 要塞 (7)
       Building::SPECIAL_19, // special3 (19 -> special3)
       Building::CASTLE,
       Building::CITADEL,
       Building::FORT,
       Building::DWELLING_LEVEL_5,
       Building::DWELLING_UPGRADE_LEVEL_5,
       Building::SPECIAL_20, // special2 (20 -> special2)
       Building::SHIPYARD,
       Building::SHIP,
       Building::DWELLING_LEVEL_1,
       Building::DWELLING_UPGRADE_LEVEL_1,
       Building::HORDE_1,
       Building::DWELLING_LEVEL_4,
       Building::DWELLING_UPGRADE_LEVEL_4,
       Building::BLACKSMITH,
       Building::EXTRA_CAPITOL,
       Building::TAVERN,
       Building::VILLAGE_HALL,
       Building::TOWN_HALL,
       Building::CITY_HALL,
       Building::CAPITOL,
       Building::MARKETPLACE,
       Building::GRAIL,
       Building::DWELLING_LEVEL_7,
       Building::DWELLING_UPGRADE_LEVEL_7,
       Building::EXTRA_ANIMATION,
       Building::MAGE_GUILD_1,
       Building::MAGE_GUILD_2,
       Building::MAGE_GUILD_3,
       Building::DWELLING_LEVEL_2,
       Building::DWELLING_UPGRADE_LEVEL_2,
       Building::DWELLING_LEVEL_3,
       Building::DWELLING_UPGRADE_LEVEL_3,
       Building::DWELLING_LEVEL_6,
       Building::DWELLING_UPGRADE_LEVEL_6,
       Building::HORDE_1_UPGR,
       Building::SPECIAL_18, // special1 (18 -> special1)
       Building::RESOURCE_SILO}};

  const static inline std::unordered_map<Building, SDL_Point> townPoint[] = {
      {// 城堡 (0)
       {Building::EXTRA_ANIMATION, {46, 119}},
       {Building::MAGE_GUILD_1, {707, 166}},
       {Building::MAGE_GUILD_2, {706, 135}},
       {Building::MAGE_GUILD_3, {704, 107}},
       {Building::MAGE_GUILD_4, {704, 76}},
       {Building::TAVERN, {0, 230}},
       {Building::SHIPYARD, {478, 134}},
       {Building::FORT, {595, 66}},
       {Building::CITADEL, {478, 66}},
       {Building::CASTLE, {478, 37}},
       {Building::VILLAGE_HALL, {0, 209}},
       {Building::TOWN_HALL, {0, 176}},
       {Building::CITY_HALL, {0, 164}},
       {Building::CAPITOL, {0, 154}},
       {Building::MARKETPLACE, {413, 264}},
       {Building::RESOURCE_SILO, {488, 228}},
       {Building::BLACKSMITH, {213, 251}},
       {Building::SPECIAL_18, {533, 71}}, // special1 for castle
       {Building::HORDE_1, {76, 53}},
       {Building::HORDE_1_UPGR, {76, 35}},
       {Building::SHIP, {478, 134}},
       {Building::SPECIAL_20, {384, 193}}, // special2 for castle
       {Building::SPECIAL_19, {0, 198}},   // special3 for castle
       {Building::GRAIL, {456, 109}},
       {Building::DWELLING_LEVEL_1, {304, 92}},
       {Building::DWELLING_LEVEL_2, {360, 130}},
       {Building::DWELLING_LEVEL_3, {76, 57}},
       {Building::DWELLING_LEVEL_4, {176, 101}},
       {Building::DWELLING_LEVEL_5, {563, 211}},
       {Building::DWELLING_LEVEL_6, {174, 190}},
       {Building::DWELLING_LEVEL_7, {303, 0}},
       {Building::DWELLING_UPGRADE_LEVEL_1, {304, 65}},
       {Building::DWELLING_UPGRADE_LEVEL_2, {360, 115}},
       {Building::DWELLING_UPGRADE_LEVEL_3, {76, 35}},
       {Building::DWELLING_UPGRADE_LEVEL_4, {176, 85}},
       {Building::DWELLING_UPGRADE_LEVEL_5, {563, 173}},
       {Building::DWELLING_UPGRADE_LEVEL_6, {160, 190}},
       {Building::DWELLING_UPGRADE_LEVEL_7, {303, 0}}},
      {// 壁垒 (1)
       {Building::EXTRA_ANIMATION, {327, 236}},
       {Building::MAGE_GUILD_1, {454, 200}},
       {Building::MAGE_GUILD_2, {438, 178}},
       {Building::MAGE_GUILD_3, {418, 153}},
       {Building::MAGE_GUILD_4, {406, 129}},
       {Building::MAGE_GUILD_5, {384, 104}},
       {Building::TAVERN, {181, 229}},
       {Building::FORT, {63, 25}},
       {Building::CITADEL, {79, 18}},
       {Building::CASTLE, {79, 18}},
       {Building::VILLAGE_HALL, {565, 216}},
       {Building::TOWN_HALL, {538, 187}},
       {Building::CITY_HALL, {538, 187}},
       {Building::CAPITOL, {534, 187}},
       {Building::MARKETPLACE, {129, 301}},
       {Building::RESOURCE_SILO, {245, 324}},
       {Building::BLACKSMITH, {558, 105}},
       {Building::SPECIAL_18, {555, 297}}, // special1 for rampart
       {Building::SPECIAL_20, {555, 297}}, // special2 for rampart
       {Building::SPECIAL_19, {0, 181}},   // special3 for rampart
       {Building::GRAIL, {0, 54}},
       {Building::EXTRA_TOWN_HALL, {293, 235}},
       {Building::EXTRA_CITY_HALL, {295, 191}},
       {Building::EXTRA_CAPITOL, {260, 171}},
       {Building::HORDE_1, {0, 154}},
       {Building::HORDE_1_UPGR, {0, 143}},
       {Building::HORDE_2, {47, 142}},
       {Building::HORDE_2_UPGR, {47, 142}},
       {Building::DWELLING_LEVEL_1, {0, 236}},
       {Building::DWELLING_LEVEL_2, {0, 154}},
       {Building::DWELLING_LEVEL_3, {668, 101}},
       {Building::DWELLING_LEVEL_4, {287, 73}},
       {Building::DWELLING_LEVEL_5, {68, 146}},
       {Building::DWELLING_LEVEL_6, {362, 90}},
       {Building::DWELLING_LEVEL_7, {502, 27}},
       {Building::DWELLING_UPGRADE_LEVEL_1, {0, 236}},
       {Building::DWELLING_UPGRADE_LEVEL_2, {0, 143}},
       {Building::DWELLING_UPGRADE_LEVEL_3, {665, 101}},
       {Building::DWELLING_UPGRADE_LEVEL_4, {287, 28}},
       {Building::DWELLING_UPGRADE_LEVEL_5, {63, 146}},
       {Building::DWELLING_UPGRADE_LEVEL_6, {362, 90}},
       {Building::DWELLING_UPGRADE_LEVEL_7, {502, 5}}},
      {// 塔楼 (2)
       {Building::MAGE_GUILD_1, {597, 82}},
       {Building::MAGE_GUILD_2, {593, 65}},
       {Building::MAGE_GUILD_3, {593, 48}},
       {Building::MAGE_GUILD_4, {593, 31}},
       {Building::MAGE_GUILD_5, {593, 14}},
       {Building::TAVERN, {375, 278}},
       {Building::FORT, {304, 0}},
       {Building::CITADEL, {301, 0}},
       {Building::CASTLE, {301, 0}},
       {Building::VILLAGE_HALL, {0, 259}},
       {Building::TOWN_HALL, {0, 220}},
       {Building::CITY_HALL, {0, 82}},
       {Building::CAPITOL, {0, 82}},
       {Building::MARKETPLACE, {614, 292}},
       {Building::RESOURCE_SILO, {763, 214}},
       {Building::BLACKSMITH, {478, 211}},
       {Building::SPECIAL_10, {674, 276}}, // special1 for tower
       {Building::SPECIAL_20, {409, 82}},  // special2 for tower
       {Building::SPECIAL_18, {702, 115}}, // special3 for tower
       {Building::SPECIAL_19, {592, 189}}, // special4 for tower
       {Building::GRAIL, {237, 14}},
       {Building::HORDE_1, {0, 47}},
       {Building::HORDE_1_UPGR, {0, 28}},
       {Building::DWELLING_LEVEL_1, {453, 221}},
       {Building::DWELLING_LEVEL_2, {4, 46}},
       {Building::DWELLING_LEVEL_3, {209, 177}},
       {Building::DWELLING_LEVEL_4, {613, 95}},
       {Building::DWELLING_LEVEL_5, {511, 75}},
       {Building::DWELLING_LEVEL_6, {681, 208}},
       {Building::DWELLING_LEVEL_7, {75, 144}},
       {Building::DWELLING_UPGRADE_LEVEL_1, {446, 221}},
       {Building::DWELLING_UPGRADE_LEVEL_2, {4, 28}},
       {Building::DWELLING_UPGRADE_LEVEL_3, {209, 177}},
       {Building::DWELLING_UPGRADE_LEVEL_4, {613, 74}},
       {Building::DWELLING_UPGRADE_LEVEL_5, {511, 8}},
       {Building::DWELLING_UPGRADE_LEVEL_6, {681, 157}},
       {Building::DWELLING_UPGRADE_LEVEL_7, {75, 91}}},
      {// 地狱 (3)
       {Building::MAGE_GUILD_1, {667, 127}},
       {Building::MAGE_GUILD_2, {667, 101}},
       {Building::MAGE_GUILD_3, {667, 83}},
       {Building::MAGE_GUILD_4, {667, 56}},
       {Building::MAGE_GUILD_5, {667, 35}},
       {Building::TAVERN, {105, 219}},
       {Building::FORT, {222, 44}},
       {Building::CITADEL, {222, 44}},
       {Building::CASTLE, {222, 18}},
       {Building::VILLAGE_HALL, {0, 174}},
       {Building::TOWN_HALL, {0, 174}},
       {Building::CITY_HALL, {0, 174}},
       {Building::CAPITOL, {0, 131}},
       {Building::MARKETPLACE, {511, 301}},
       {Building::RESOURCE_SILO, {497, 337}},
       {Building::BLACKSMITH, {684, 253}},
       {Building::SPECIAL_18, {297, 0}},   // special2 for inferno
       {Building::SPECIAL_19, {227, 174}}, // special3 for inferno
       {Building::SPECIAL_20, {593, 104}}, // special4 for inferno
       {Building::HORDE_1, {614, 256}},
       {Building::HORDE_1_UPGR, {614, 221}},
       {Building::HORDE_2, {10, 301}},
       {Building::HORDE_2_UPGR, {9, 273}},
       {Building::GRAIL, {24, 10}},
       {Building::DWELLING_LEVEL_1, {614, 256}},
       {Building::DWELLING_LEVEL_2, {187, 248}},
       {Building::DWELLING_LEVEL_3, {9, 325}},
       {Building::DWELLING_LEVEL_4, {414, 204}},
       {Building::DWELLING_LEVEL_5, {359, 296}},
       {Building::DWELLING_LEVEL_6, {220, 350}},
       {Building::DWELLING_LEVEL_7, {420, 153}},
       {Building::DWELLING_UPGRADE_LEVEL_1, {614, 221}},
       {Building::DWELLING_UPGRADE_LEVEL_2, {187, 212}},
       {Building::DWELLING_UPGRADE_LEVEL_3, {9, 273}},
       {Building::DWELLING_UPGRADE_LEVEL_4, {412, 197}},
       {Building::DWELLING_UPGRADE_LEVEL_5, {359, 244}},
       {Building::DWELLING_UPGRADE_LEVEL_6, {220, 282}},
       {Building::DWELLING_UPGRADE_LEVEL_7, {420, 105}}},
      {// 墓园 (4)
       {Building::EXTRA_ANIMATION, {25, 279}},
       {Building::MAGE_GUILD_1, {341, 116}},
       {Building::MAGE_GUILD_2, {341, 97}},
       {Building::MAGE_GUILD_3, {341, 78}},
       {Building::MAGE_GUILD_4, {340, 62}},
       {Building::MAGE_GUILD_5, {343, 35}},
       {Building::TAVERN, {508, 189}},
       {Building::SHIPYARD, {617, 265}},
       {Building::FORT, {138, 66}},
       {Building::CITADEL, {139, 66}},
       {Building::CASTLE, {34, 18}},
       {Building::VILLAGE_HALL, {468, 76}},
       {Building::TOWN_HALL, {482, 56}},
       {Building::CITY_HALL, {478, 26}},
       {Building::CAPITOL, {481, 26}},
       {Building::MARKETPLACE, {347, 215}},
       {Building::RESOURCE_SILO, {276, 185}},
       {Building::BLACKSMITH, {382, 252}},
       {Building::SPECIAL_18, {18, 0}}, // special1 for necropolis
       {Building::HORDE_1, {80, 222}},
       {Building::HORDE_1_UPGR, {64, 222}},
       {Building::SHIP, {617, 265}},
       {Building::SPECIAL_19, {307, 61}},  // special2 for necropolis
       {Building::SPECIAL_20, {247, 275}}, // special3 for necropolis
       {Building::GRAIL, {410, 88}},
       {Building::EXTRA_TOWN_HALL, {0, 241}},
       {Building::EXTRA_CITY_HALL, {321, 255}},
       {Building::EXTRA_CAPITOL, {475, 257}},
       {Building::DWELLING_LEVEL_1, {80, 222}},
       {Building::DWELLING_LEVEL_2, {502, 223}},
       {Building::DWELLING_LEVEL_3, {0, 187}},
       {Building::DWELLING_LEVEL_4, {607, 212}},
       {Building::DWELLING_LEVEL_5, {206, 207}},
       {Building::DWELLING_LEVEL_6, {0, 31}},
       {Building::DWELLING_LEVEL_7, {663, 25}},
       {Building::DWELLING_UPGRADE_LEVEL_1, {64, 222}},
       {Building::DWELLING_UPGRADE_LEVEL_2, {498, 224}},
       {Building::DWELLING_UPGRADE_LEVEL_3, {0, 179}},
       {Building::DWELLING_UPGRADE_LEVEL_4, {615, 193}},
       {Building::DWELLING_UPGRADE_LEVEL_5, {222, 171}},
       {Building::DWELLING_UPGRADE_LEVEL_6, {0, 30}},
       {Building::DWELLING_UPGRADE_LEVEL_7, {662, 23}}},
      {// 地牢 (5)
       {Building::MAGE_GUILD_1, {164, 119}},
       {Building::MAGE_GUILD_2, {164, 97}},
       {Building::MAGE_GUILD_3, {164, 77}},
       {Building::MAGE_GUILD_4, {164, 61}},
       {Building::MAGE_GUILD_5, {164, 15}},
       {Building::TAVERN, {211, 297}},
       {Building::FORT, {363, 87}},
       {Building::CITADEL, {363, 87}},
       {Building::CASTLE, {363, 87}},
       {Building::VILLAGE_HALL, {0, 234}},
       {Building::TOWN_HALL, {0, 223}},
       {Building::CITY_HALL, {0, 223}},
       {Building::CAPITOL, {0, 203}},
       {Building::MARKETPLACE, {590, 318}},
       {Building::RESOURCE_SILO, {624, 335}},
       {Building::BLACKSMITH, {544, 248}},
       {Building::SPECIAL_10, {746, 294}}, // special1 for dungeon
       {Building::HORDE_1, {0, 326}},
       {Building::HORDE_1_UPGR, {0, 300}},
       {Building::SPECIAL_18, {131, 26}},  // special2 for dungeon
       {Building::SPECIAL_19, {687, 177}}, // special3 for dungeon
       {Building::SPECIAL_20, {313, 298}}, // special4 for dungeon
       {Building::GRAIL, {562, 24}},
       {Building::DWELLING_LEVEL_1, {0, 326}},
       {Building::DWELLING_LEVEL_2, {0, 26}},
       {Building::DWELLING_LEVEL_3, {118, 308}},
       {Building::DWELLING_LEVEL_4, {300, 29}},
       {Building::DWELLING_LEVEL_5, {551, 186}},
       {Building::DWELLING_LEVEL_6, {270, 253}},
       {Building::DWELLING_LEVEL_7, {550, 0}},
       {Building::DWELLING_UPGRADE_LEVEL_1, {0, 300}},
       {Building::DWELLING_UPGRADE_LEVEL_2, {0, 26}},
       {Building::DWELLING_UPGRADE_LEVEL_3, {118, 256}},
       {Building::DWELLING_UPGRADE_LEVEL_4, {300, 29}},
       {Building::DWELLING_UPGRADE_LEVEL_5, {519, 172}},
       {Building::DWELLING_UPGRADE_LEVEL_6, {270, 253}},
       {Building::DWELLING_UPGRADE_LEVEL_7, {550, 0}}},
      {// 据点 (6)
       {Building::EXTRA_ANIMATION, {23, 20}},
       {Building::MAGE_GUILD_1, {473, 67}},
       {Building::MAGE_GUILD_2, {473, 37}},
       {Building::MAGE_GUILD_3, {473, 1}},
       {Building::TAVERN, {170, 280}},
       {Building::FORT, {402, 148}},
       {Building::CITADEL, {402, 114}},
       {Building::CASTLE, {402, 114}},
       {Building::VILLAGE_HALL, {0, 259}},
       {Building::TOWN_HALL, {0, 225}},
       {Building::CITY_HALL, {0, 201}},
       {Building::CAPITOL, {0, 148}},
       {Building::MARKETPLACE, {397, 308}},
       {Building::RESOURCE_SILO, {458, 248}},
       {Building::BLACKSMITH, {660, 286}},
       {Building::SPECIAL_18, {550, 229}}, // special1 for stronghold
       {Building::HORDE_1, {373, 239}},
       {Building::HORDE_1_UPGR, {373, 220}},
       {Building::SPECIAL_21, {473, 282}}, // special2 for stronghold
       {Building::SPECIAL_19, {617, 286}}, // special3 for stronghold
       {Building::SPECIAL_20, {313, 13}},  // special4 for stronghold
       {Building::GRAIL, {321, 105}},
       {Building::DWELLING_LEVEL_1, {373, 239}},
       {Building::DWELLING_LEVEL_2, {266, 246}},
       {Building::DWELLING_LEVEL_3, {566, 232}},
       {Building::DWELLING_LEVEL_4, {197, 204}},
       {Building::DWELLING_LEVEL_5, {137, 30}},
       {Building::DWELLING_LEVEL_6, {622, 160}},
       {Building::DWELLING_LEVEL_7, {604, 0}},
       {Building::DWELLING_UPGRADE_LEVEL_1, {373, 220}},
       {Building::DWELLING_UPGRADE_LEVEL_2, {266, 225}},
       {Building::DWELLING_UPGRADE_LEVEL_3, {566, 158}},
       {Building::DWELLING_UPGRADE_LEVEL_4, {197, 137}},
       {Building::DWELLING_UPGRADE_LEVEL_5, {129, 15}},
       {Building::DWELLING_UPGRADE_LEVEL_6, {616, 93}},
       {Building::DWELLING_UPGRADE_LEVEL_7, {604, 0}}},
      {// 要塞 (7)
       {Building::EXTRA_ANIMATION, {372, 227}},
       {Building::MAGE_GUILD_1, {0, 200}},
       {Building::MAGE_GUILD_2, {0, 177}},
       {Building::MAGE_GUILD_3, {0, 135}},
       {Building::TAVERN, {634, 219}},
       {Building::SHIPYARD, {197, 294}},
       {Building::FORT, {368, 118}},
       {Building::CITADEL, {368, 98}},
       {Building::CASTLE, {368, 55}},
       {Building::VILLAGE_HALL, {166, 128}},
       {Building::TOWN_HALL, {166, 97}},
       {Building::CITY_HALL, {166, 51}},
       {Building::CAPITOL, {166, 2}},
       {Building::MARKETPLACE, {382, 219}},
       {Building::RESOURCE_SILO, {448, 210}},
       {Building::BLACKSMITH, {360, 160}},
       {Building::SPECIAL_20, {703, 36}}, // special1 for fortress
       {Building::HORDE_1, {641, 121}},
       {Building::HORDE_1_UPGR, {641, 68}},
       {Building::SHIP, {197, 294}},
       {Building::SPECIAL_19, {341, 174}}, // special2 for fortress
       {Building::SPECIAL_18, {349, 79}},  // special3 for fortress
       {Building::GRAIL, {468, 260}},
       {Building::EXTRA_CAPITOL, {320, 141}},
       {Building::DWELLING_LEVEL_1, {641, 168}},
       {Building::DWELLING_LEVEL_2, {141, 178}},
       {Building::DWELLING_LEVEL_3, {192, 85}},
       {Building::DWELLING_LEVEL_4, {0, 292}},
       {Building::DWELLING_LEVEL_5, {15, 127}},
       {Building::DWELLING_LEVEL_6, {0, 4}},
       {Building::DWELLING_LEVEL_7, {612, 291}},
       {Building::DWELLING_UPGRADE_LEVEL_1, {641, 107}},
       {Building::DWELLING_UPGRADE_LEVEL_2, {125, 163}},
       {Building::DWELLING_UPGRADE_LEVEL_3, {159, 19}},
       {Building::DWELLING_UPGRADE_LEVEL_4, {0, 257}},
       {Building::DWELLING_UPGRADE_LEVEL_5, {15, 69}},
       {Building::DWELLING_UPGRADE_LEVEL_6, {0, 4}},
       {Building::DWELLING_UPGRADE_LEVEL_7, {587, 263}}}};

  const static inline std::unordered_map<Building, std::string> townArea[] = {
      {// 城堡 (0)
       {Building::MAGE_GUILD_1, "TZCSMAG1.pcx"},
       {Building::MAGE_GUILD_2, "TZCSMAG2.pcx"},
       {Building::MAGE_GUILD_3, "TZCSM301.pcx"},
       {Building::MAGE_GUILD_4, "TZCSM401.pcx"},
       {Building::TAVERN, "TZCSTAV1.pcx"},
       {Building::SHIPYARD, "TZCSDKMS.pcx"},
       {Building::FORT, "TZCSCAS1.pcx"},
       {Building::CITADEL, "TZCSCAS2.pcx"},
       {Building::CASTLE, "TZCSCAS3.pcx"},
       {Building::VILLAGE_HALL, "TZCSH101.pcx"},
       {Building::TOWN_HALL, "TZCSH201.pcx"},
       {Building::CITY_HALL, "TZCSH301.pcx"},
       {Building::CAPITOL, "TZCSH401.pcx"},
       {Building::MARKETPLACE, "TZCSMRK1.pcx"},
       {Building::RESOURCE_SILO, "TZCSMRK2.pcx"},
       {Building::BLACKSMITH, "TZCSBLAK.pcx"},
       {Building::SPECIAL_18, "TZCSLT01.pcx"}, // special1 for castle
       {Building::HORDE_1, "TZCSGR1H.pcx"},
       {Building::HORDE_1_UPGR, "TZCSGR2H.pcx"},
       {Building::SHIP, "TZCSDKMN.pcx"},
       {Building::SPECIAL_20, "TZCSCAVM.pcx"}, // special2 for castle
       {Building::SPECIAL_19, "TZCSTAV2.pcx"}, // special3 for castle
       {Building::GRAIL, "TZCSHOLY.pcx"},
       {Building::DWELLING_LEVEL_1, "TZCSPIK1.pcx"},
       {Building::DWELLING_LEVEL_2, "TZCSCRS1.pcx"},
       {Building::DWELLING_LEVEL_3, "TZCSGR1N.pcx"},
       {Building::DWELLING_LEVEL_4, "TZCSSWD1.pcx"},
       {Building::DWELLING_LEVEL_5, "TZCSMON1.pcx"},
       {Building::DWELLING_LEVEL_6, "TZCSCAV1.pcx"},
       {Building::DWELLING_LEVEL_7, "TZCSANG1.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_1, "TZCSPIK2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_2, "TZCSCRS2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_3, "TZCSGR2N.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_4, "TZCSSWD2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_5, "TZCSMON2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_6, "TZCSCAV2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_7, "TZCSANG2.pcx"}},
      {// 壁垒 (1)
       {Building::MAGE_GUILD_1, "TZRMAG1.pcx"},
       {Building::MAGE_GUILD_2, "TZRMAG2.pcx"},
       {Building::MAGE_GUILD_3, "TZRMAG3.pcx"},
       {Building::MAGE_GUILD_4, "TZRMAG4.pcx"},
       {Building::MAGE_GUILD_5, "TZRMAG5.pcx"},
       {Building::TAVERN, "TZRTAV.pcx"},
       {Building::FORT, "TZRCAS1.pcx"},
       {Building::CITADEL, "TZRCAS3.pcx"},
       {Building::CASTLE, "TZRCAS2.pcx"},
       {Building::VILLAGE_HALL, "TZRHAL1.pcx"},
       {Building::TOWN_HALL, "TZRHAL2.pcx"},
       {Building::CITY_HALL, "TZRHAL3.pcx"},
       {Building::CAPITOL, "TZRHAL4.pcx"},
       {Building::MARKETPLACE, "TZRMRK1.pcx"},
       {Building::RESOURCE_SILO, "TZRMRK2.pcx"},
       {Building::BLACKSMITH, "TZRAID.pcx"},
       {Building::SPECIAL_18, "TZRGAR1A.pcx"}, // special1 for rampart
       {Building::HORDE_1, "TZRDWF1H.pcx"},
       {Building::HORDE_1_UPGR, "TZRDWF2H.pcx"},
       {Building::SPECIAL_19, "TZRGAR2A.pcx"}, // special2 for rampart
       {Building::SPECIAL_20, "TZRDWFT.pcx"},  // special3 for rampart
       {Building::HORDE_2, "TZRTRE1H.pcx"},
       {Building::HORDE_2_UPGR, "TZRTRE2H.pcx"},
       {Building::GRAIL, "TZRHOLY.pcx"},
       {Building::DWELLING_LEVEL_1, "TZRCEN1A.pcx"},
       {Building::DWELLING_LEVEL_2, "TZRDWF1.pcx"},
       {Building::DWELLING_LEVEL_3, "TZRELF1.pcx"},
       {Building::DWELLING_LEVEL_4, "TZRPEG1A.pcx"},
       {Building::DWELLING_LEVEL_5, "TZRTRE1.pcx"},
       {Building::DWELLING_LEVEL_6, "TZRUNI1.pcx"},
       {Building::DWELLING_LEVEL_7, "TZRDR1AA.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_1, "TZRCEN2A.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_2, "TZRDWF2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_3, "TZRELF2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_4, "TZRPEG2A.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_5, "TZRTRE2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_6, "TZRUNI2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_7, "TZRDR2AA.pcx"}},
      {// 塔楼 (2)
       {Building::MAGE_GUILD_1, "TZTGLD1.pcx"},
       {Building::MAGE_GUILD_2, "TZTGLD2.pcx"},
       {Building::MAGE_GUILD_3, "TZTGLD3.pcx"},
       {Building::MAGE_GUILD_4, "TZTGLD4.pcx"},
       {Building::MAGE_GUILD_5, "TZTGLD5.pcx"},
       {Building::TAVERN, "TZTTAV.pcx"},
       {Building::FORT, "TZTCAS1.pcx"},
       {Building::CITADEL, "TZTCAS2.pcx"},
       {Building::CASTLE, "TZTCAS3.pcx"},
       {Building::VILLAGE_HALL, "TZTHAL1.pcx"},
       {Building::TOWN_HALL, "TZTHAL2.pcx"},
       {Building::CITY_HALL, "TZTHAL3.pcx"},
       {Building::CAPITOL, "TZTHAL4.pcx"},
       {Building::MARKETPLACE, "TZTMRK.pcx"},
       {Building::RESOURCE_SILO, "TZTMRKS.pcx"},
       {Building::BLACKSMITH, "TZTBLKA.pcx"},
       {Building::SPECIAL_10, "TZTMRKA.pcx"}, // special1 for tower
       {Building::SPECIAL_20, "TZTCASW.pcx"}, // special2 for tower
       {Building::SPECIAL_18, "TZTGLDL.pcx"}, // special3 for tower
       {Building::SPECIAL_19, "TZTGLDW.pcx"}, // special4 for tower
       {Building::HORDE_1, "TZTGAR1H.pcx"},
       {Building::HORDE_1_UPGR, "TZTGAR2H.pcx"},
       {Building::GRAIL, "TZTHOLYA.pcx"},
       {Building::DWELLING_LEVEL_1, "TZTGRM1A.pcx"},
       {Building::DWELLING_LEVEL_2, "TZTGAR1.pcx"},
       {Building::DWELLING_LEVEL_3, "TZTGOL1A.pcx"},
       {Building::DWELLING_LEVEL_4, "TZTMAG1.pcx"},
       {Building::DWELLING_LEVEL_5, "TZTGEN1.pcx"},
       {Building::DWELLING_LEVEL_6, "TZTNAG1.pcx"},
       {Building::DWELLING_LEVEL_7, "TZTTIT1.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_1, "TZTGRM2A.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_2, "TZTGAR2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_3, "TZTGOL2A.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_4, "TZTMAG2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_5, "TZTGEN2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_6, "TZTNAG2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_7, "TZTTIT2.pcx"}},
      {// 地狱 (3)
       {Building::MAGE_GUILD_1, "TZIMAG1A.pcx"},
       {Building::MAGE_GUILD_2, "TZIMAG2A.pcx"},
       {Building::MAGE_GUILD_3, "TZIMAG3A.pcx"},
       {Building::MAGE_GUILD_4, "TZIMAG4A.pcx"},
       {Building::MAGE_GUILD_5, "TZIMAG5A.pcx"},
       {Building::TAVERN, "TZITAV.pcx"},
       {Building::FORT, "TZICAS2A.pcx"},
       {Building::CITADEL, "TZICAS1A.pcx"},
       {Building::CASTLE, "TZICAS3A.pcx"},
       {Building::VILLAGE_HALL, "TZIHAL1.pcx"},
       {Building::TOWN_HALL, "TZIHAL2.pcx"},
       {Building::CITY_HALL, "TZIHAL3.pcx"},
       {Building::CAPITOL, "TZIHAL4.pcx"},
       {Building::MARKETPLACE, "TZIMAR1.pcx"},
       {Building::RESOURCE_SILO, "TZIMAR2.pcx"},
       {Building::BLACKSMITH, "TZIBLKA.pcx"},
       {Building::SPECIAL_18, "TZICAB1A.pcx"}, // special2 for inferno
       {Building::SPECIAL_19, "TZICASGA.pcx"}, // special3 for inferno
       {Building::SPECIAL_20, "TZIPAIN.pcx"},  // special4 for inferno
       {Building::HORDE_1, "TZIMP1HA.pcx"},
       {Building::HORDE_1_UPGR, "TZIMP2HA.pcx"},
       {Building::HORDE_2, "TZIHND1H.pcx"},
       {Building::HORDE_2_UPGR, "TZIHND2H.pcx"},
       {Building::GRAIL, "TZIHOLY.pcx"},
       {Building::DWELLING_LEVEL_1, "TZIMP1A.pcx"},
       {Building::DWELLING_LEVEL_2, "TZIGOG1A.pcx"},
       {Building::DWELLING_LEVEL_3, "TZIHND1.pcx"},
       {Building::DWELLING_LEVEL_4, "TZIDMN1.pcx"},
       {Building::DWELLING_LEVEL_5, "TZIPIT1.pcx"},
       {Building::DWELLING_LEVEL_6, "TZIEFR1.pcx"},
       {Building::DWELLING_LEVEL_7, "TZIDVL1.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_1, "TZIMP2A.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_2, "TZIGOG2A.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_3, "TZIHND2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_4, "TZIDMN2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_5, "TZIPIT2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_6, "TZIEFR2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_7, "TZIDVL2.pcx"}},
      {// 墓园 (4)
       {Building::MAGE_GUILD_1, "TZNMAG1.pcx"},
       {Building::MAGE_GUILD_2, "TZNMAG2.pcx"},
       {Building::MAGE_GUILD_3, "TZNMAG3.pcx"},
       {Building::MAGE_GUILD_4, "TZNMAG4.pcx"},
       {Building::MAGE_GUILD_5, "TZNMAG5.pcx"},
       {Building::TAVERN, "TZNTAV.pcx"},
       {Building::SHIPYARD, "TZNSHPBA.pcx"},
       {Building::FORT, "TZNCAS1.pcx"},
       {Building::CITADEL, "TZNCAS2.pcx"},
       {Building::CASTLE, "TZNCAS3.pcx"},
       {Building::VILLAGE_HALL, "TZNHAL1.pcx"},
       {Building::TOWN_HALL, "TZNHAL2.pcx"},
       {Building::CITY_HALL, "TZNHAL3.pcx"},
       {Building::CAPITOL, "TZNHAL4.pcx"},
       {Building::MARKETPLACE, "TZNMRK1.pcx"},
       {Building::RESOURCE_SILO, "TZNMRK2.pcx"},
       {Building::BLACKSMITH, "TZNSMITA.pcx"},
       {Building::SPECIAL_18, "TZNSHRDA.pcx"}, // special1 for necropolis
       {Building::HORDE_1, "TZNSKE1H.pcx"},
       {Building::HORDE_1_UPGR, "TZNSKE2H.pcx"},
       {Building::SHIP, "TZNSHPNA.pcx"},
       {Building::SPECIAL_19, "TZNNECRA.pcx"}, // special2 for necropolis
       {Building::SPECIAL_20, "TZNSKELT.pcx"}, // special3 for necropolis
       {Building::GRAIL, "TZNHOLYA.pcx"},
       {Building::DWELLING_LEVEL_1, "TZNSKEL1.pcx"},
       {Building::DWELLING_LEVEL_2, "TZNZOMB1.pcx"},
       {Building::DWELLING_LEVEL_3, "TZNWIGH1.pcx"},
       {Building::DWELLING_LEVEL_4, "TZNVAM1.pcx"},
       {Building::DWELLING_LEVEL_5, "TZNLICH1.pcx"},
       {Building::DWELLING_LEVEL_6, "TZNBKN1.pcx"},
       {Building::DWELLING_LEVEL_7, "TZNBON1.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_1, "TZNSKEL2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_2, "TZNZOMB2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_3, "TZNWIGH2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_4, "TZNVAM2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_5, "TZNLICH2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_6, "TZNBKN2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_7, "TZNBON2.pcx"}},
      {// 地牢 (5)
       {Building::MAGE_GUILD_1, "TZDMAG1.pcx"},
       {Building::MAGE_GUILD_2, "TZDMAG2.pcx"},
       {Building::MAGE_GUILD_3, "TZDMAG3.pcx"},
       {Building::MAGE_GUILD_4, "TZDMAG4.pcx"},
       {Building::MAGE_GUILD_5, "TZDMAG5.pcx"},
       {Building::TAVERN, "TZDTAV.pcx"},
       {Building::FORT, "TZDCAS1.pcx"},
       {Building::CITADEL, "TZDCAS2.pcx"},
       {Building::CASTLE, "TZDCAS3.pcx"},
       {Building::VILLAGE_HALL, "TZDHALL1.pcx"},
       {Building::TOWN_HALL, "TZDHALL2.pcx"},
       {Building::CITY_HALL, "TZDHALL3.pcx"},
       {Building::CAPITOL, "TZDHALL4.pcx"},
       {Building::MARKETPLACE, "TZDMARK.pcx"},
       {Building::RESOURCE_SILO, "TZDSILO.pcx"},
       {Building::BLACKSMITH, "TZDSMITH.pcx"},
       {Building::SPECIAL_10, "TZDART.pcx"}, // special1 for dungeon
       {Building::HORDE_1, "TZDTR1HA.pcx"},
       {Building::HORDE_1_UPGR, "TZDTR2HA.pcx"},
       {Building::SPECIAL_18, "TZDVOR1A.pcx"}, // special2 for dungeon
       {Building::SPECIAL_19, "TZDPORTA.pcx"}, // special3 for dungeon
       {Building::SPECIAL_20, "TZDACAD.pcx"},  // special4 for dungeon
       {Building::GRAIL, "TZDHOLY.pcx"},
       {Building::DWELLING_LEVEL_1, "TZDTRG1A.pcx"},
       {Building::DWELLING_LEVEL_2, "TZDHAR1.pcx"},
       {Building::DWELLING_LEVEL_3, "TZDBEH1A.pcx"},
       {Building::DWELLING_LEVEL_4, "TZDMED1.pcx"},
       {Building::DWELLING_LEVEL_5, "TZDMIN1.pcx"},
       {Building::DWELLING_LEVEL_6, "TZDMAN1.pcx"},
       {Building::DWELLING_LEVEL_7, "TZDDRA1A.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_1, "TZDTRG2A.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_2, "TZDHAR2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_3, "TZDBEH2A.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_4, "TZDMED2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_5, "TZDMIN2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_6, "TZDMAN2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_7, "TZDDRA2A.pcx"}},
      {// 据点 (6)
       {Building::MAGE_GUILD_1, "TZSMAG1.pcx"},
       {Building::MAGE_GUILD_2, "TZSMAG2.pcx"},
       {Building::MAGE_GUILD_3, "TZSMAG3.pcx"},
       {Building::TAVERN, "TZSTAV.pcx"},
       {Building::FORT, "TZSCA1.pcx"},
       {Building::CITADEL, "TZSCA2.pcx"},
       {Building::CASTLE, "TZSCA3.pcx"},
       {Building::VILLAGE_HALL, "TZSHAL1A.pcx"},
       {Building::TOWN_HALL, "TZSHAL2A.pcx"},
       {Building::CITY_HALL, "TZSHAL3A.pcx"},
       {Building::CAPITOL, "TZSHAL4A.pcx"},
       {Building::MARKETPLACE, "TZSMRK1.pcx"},
       {Building::RESOURCE_SILO, "TZSMRK2.pcx"},
       {Building::BLACKSMITH, "TZSBLK1.pcx"},
       {Building::SPECIAL_18, "TZSCA1EA.pcx"}, // special1 for stronghold
       {Building::HORDE_1, "TZSGOB1H.pcx"},
       {Building::HORDE_1_UPGR, "TZSGOB2H.pcx"},
       {Building::SPECIAL_21, "TZSMRK1C.pcx"}, // special2 for stronghold
       {Building::SPECIAL_19, "TZSBLK2.pcx"},  // special3 for stronghold
       {Building::SPECIAL_20, "TZSVAH.pcx"},   // special4 for stronghold
       {Building::GRAIL, "TZSHOLYA.pcx"},
       {Building::DWELLING_LEVEL_1, "TZSGOB1.pcx"},
       {Building::DWELLING_LEVEL_2, "TZSWOL1.pcx"},
       {Building::DWELLING_LEVEL_3, "TZSORC1.pcx"},
       {Building::DWELLING_LEVEL_4, "TZSOGR1.pcx"},
       {Building::DWELLING_LEVEL_5, "TZSROC1.pcx"},
       {Building::DWELLING_LEVEL_6, "TZSCYC1.pcx"},
       {Building::DWELLING_LEVEL_7, "TZSBEH1A.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_1, "TZSGOB2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_2, "TZSWOL2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_3, "TZSORC2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_4, "TZSOGR2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_5, "TZSROC2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_6, "TZSCYC2A.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_7, "TZSBEH2A.pcx"}},
      {// 要塞 (7)
       {Building::MAGE_GUILD_1, "TZFMAG1A.pcx"},
       {Building::MAGE_GUILD_2, "TZFMAG2A.pcx"},
       {Building::MAGE_GUILD_3, "TZFMAG3A.pcx"},
       {Building::TAVERN, "TZFTAVA.pcx"},
       {Building::SHIPYARD, "TZFDCK2.pcx"},
       {Building::FORT, "TZFCAS1.pcx"},
       {Building::CITADEL, "TZFCAS2.pcx"},
       {Building::CASTLE, "TZFCAS3.pcx"},
       {Building::VILLAGE_HALL, "TZFHAL1.pcx"},
       {Building::TOWN_HALL, "TZFHAL2.pcx"},
       {Building::CITY_HALL, "TZFHAL3.pcx"},
       {Building::CAPITOL, "TZFHAL4.pcx"},
       {Building::MARKETPLACE, "TZFMRKAA.pcx"},
       {Building::RESOURCE_SILO, "TZFMRK2A.pcx"},
       {Building::BLACKSMITH, "TZFAIDA.pcx"},
       {Building::SPECIAL_20, "TZFCAGE.pcx"}, // special1 for fortress
       {Building::HORDE_1, "TZFGNL1H.pcx"},
       {Building::HORDE_1_UPGR, "TZFGNL2H.pcx"},
       {Building::SHIP, "TZFDCK1.pcx"},
       {Building::SPECIAL_19, "TZFCASD.pcx"}, // special2 for fortress
       {Building::SPECIAL_18, "TZFCASA.pcx"}, // special3 for fortress
       {Building::GRAIL, "TZFHLYAA.pcx"},
       {Building::DWELLING_LEVEL_1, "TZFGNL1.pcx"},
       {Building::DWELLING_LEVEL_2, "TZFLIZ1.pcx"},
       {Building::DWELLING_LEVEL_3, "TZFFLY1A.pcx"},
       {Building::DWELLING_LEVEL_4, "TZFBAS1.pcx"},
       {Building::DWELLING_LEVEL_5, "TZFGOR1.pcx"},
       {Building::DWELLING_LEVEL_6, "TZFWYV1.pcx"},
       {Building::DWELLING_LEVEL_7, "TZFHYD1A.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_1, "TZFGNL2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_2, "TZFLIZ2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_3, "TZFFLY2A.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_4, "TZFBAS2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_5, "TZFGOR2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_6, "TZFWYV2.pcx"},
       {Building::DWELLING_UPGRADE_LEVEL_7, "TZFHYD2A.pcx"}}};

  //   const static inline std::unordered_map<uint8_t, std::string> townIndex =
  //   {
  //       {0, "townHall"},        {1, "cityHall"},
  //       {2, "capitol"},         {3, "fort"},
  //       {4, "citadel"},         {5, "castle"},
  //       {6, "tavern"},          {7, "blacksmith"},
  //       {8, "marketplace"},     {9, "resourceSilo"},
  //       {11, "mageGuild1"},     {12, "mageGuild2"},
  //       {13, "mageGuild3"},     {14, "mageGuild4"},
  //       {15, "mageGuild5"},     {16, "shipyard"},
  //       {17, "grail"},          {22, "dwellingLvl1"},
  //       {23, "dwellingUpLvl1"}, {24, "horde1"},
  //       {25, "dwellingLvl2"},   {26, "dwellingUpLvl2"},
  //       {27, "horde2"},         {28, "dwellingLvl3"},
  //       {29, "dwellingUpLvl3"}, {30, "horde3"},
  //       {31, "dwellingLvl4"},   {32, "dwellingUpLvl4"},
  //       {33, "horde4"},         {34, "dwellingLvl5"},
  //       {35, "dwellingUpLvl5"}, {36, "horde5"},
  //       {37, "dwellingLvl6"},   {38, "dwellingUpLvl6"},
  //       {39, "dwellingLvl7"},   {40, "dwellingUpLvl7"},
  //       {255, "villageHall"},
  //   };

  //   const static inline std::unordered_map<uint8_t, std::string>
  //       townSpecialIndex[] = {
  //           // castle - 索引0
  //           {{18, "special1"}, {20, "special2"}, {19, "special3"}},
  //           // rampart - 索引1
  //           {{18, "special1"}, {19, "special2"}, {20, "special3"}},
  //           // tower - 索引2
  //           {{10, "special1"},
  //            {20, "special2"},
  //            {18, "special3"},
  //            {19, "special4"}},
  //           // inferno - 索引3
  //           {{18, "special2"}, {19, "special3"}, {20, "special4"}},
  //           // necropolis - 索引4
  //           {{18, "special1"}, {19, "special2"}, {20, "special3"}},
  //           // dungeon - 索引5
  //           {{10, "special1"},
  //            {18, "special2"},
  //            {19, "special3"},
  //            {20, "special4"}},
  //           // stronghold - 索引6
  //           {{18, "special1"},
  //            {19, "special2"},
  //            {20, "special3"},
  //            {21, "special4"}},
  //           // fortress - 索引7
  //           {{20, "special1"}, {19, "special2"}, {18, "special3"}},
  //   };
};