#pragma once

#include "SDL3/SDL_rect.h"
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>
struct TownCfg {
  const static inline std::vector<std::vector<std::string>> creatureBackground =
      {{"TPCASCAS.pcx", "CRBKGCAS.pcx"}};

  const static inline std::vector<std::string> musicThemeStr = {
      "CstleTown", "Rampart", "TowerTown",  "InfernoTown",
      "NecroTown", "Dungeon", "Stronghold", "FortressTown"};

  const static inline std::string tavernVideoStr = "TAVERN.BIK";

  const static inline std::string guildBackgroundStr = "TPMAGE.pcx";

  const static inline std::vector<std::string> guildWindowStr = {
      "TPMAGECS.pcx", "TPMAGERM.pcx", "TPMAGEIN.pcx", "TPMAGEIN.pcx",
      "TPMAGENC.pcx", "TPMAGEDN.pcx", "TPMAGEST.pcx", "TPMAGEFR.pcx"};

  const static inline std::vector<std::string> backGroundsStr = {
      "TBCSBACK.pcx", "TBRMBACK.pcx", "TBTWBACK.pcx", "TBINBACK.pcx",
      "TBNCBACK.pcx", "TBDNBACK.pcx", "TBSTBACK.pcx", "TBFRBACK.pcx"};
  const static inline std::vector<std::string> hallBackgroundStr = {
      "TPTHBKCS.pcx", "TPTHBKRM.pcx", "TPTHBKTW.pcx", "TBINBACK.pcx",
      "TPTHBKNC.pcx", "TPTHBKDG.pcx", "TPTHBKTW.pcx", "TPTHBKFR.pcx"};
  const static inline std::vector<std::string> buildingsIconsStr = {
      "HALLCSTL.DEF", "HALLRAMP.DEF", "HALLTOWR.DEF", "HALLINFR.DEF",
      "HALLNECR.DEF", "HALLDUNG.DEF", "HALLSTRN.DEF", "HALLFORT.DEF"};
  const static inline std::vector<std::vector<std::vector<std::string>>>
      townHallSlots[] = {
          {
              // 0
              {{"villageHall", "townHall", "cityHall", "capitol"},
               {"fort", "citadel", "castle"},
               {"tavern", "special3"},
               {"blacksmith"}},
              {{"marketplace", "resourceSilo"},
               {"mageGuild1", "mageGuild2", "mageGuild3", "mageGuild4"},
               {"shipyard", "special1"}},
              {{"special2"}, {"horde1", "horde1Upgr"}},
              {{"dwellingLvl1", "dwellingUpLvl1"},
               {"dwellingLvl2", "dwellingUpLvl2"},
               {"dwellingLvl3", "dwellingUpLvl3"},
               {"dwellingLvl4", "dwellingUpLvl4"}},
              {{"dwellingLvl5", "dwellingUpLvl5"},
               {"dwellingLvl6", "dwellingUpLvl6"},
               {"dwellingLvl7", "dwellingUpLvl7"}}
              //
          },
          {
              // 1
              {{"villageHall", "townHall", "cityHall", "capitol"},
               {"fort", "citadel", "castle"},
               {"tavern"},
               {"blacksmith"}},
              {{"marketplace", "resourceSilo"},
               {"mageGuild1", "mageGuild2", "mageGuild3", "mageGuild4",
                "mageGuild5"},
               {"special1", "special2"}},
              {{"special3"},
               {"horde2", "horde2Upgr"},
               {"horde1", "horde1Upgr"}},
              {{"dwellingLvl1", "dwellingUpLvl1"},
               {"dwellingLvl2", "dwellingUpLvl2"},
               {"dwellingLvl3", "dwellingUpLvl3"},
               {"dwellingLvl4", "dwellingUpLvl4"}},
              {{"dwellingLvl5", "dwellingUpLvl5"},
               {"dwellingLvl6", "dwellingUpLvl6"},
               {"dwellingLvl7", "dwellingUpLvl7"}}
              //
          },
          // 2
          {{{"villageHall", "townHall", "cityHall", "capitol"},
            {"fort", "citadel", "castle"},
            {"tavern"},
            {"blacksmith"}},
           {{"marketplace", "resourceSilo"},
            {"mageGuild1", "mageGuild2", "mageGuild3", "mageGuild4",
             "mageGuild5"},
            {"special3"},
            {"special4"}},
           {{"special1"}, {"special2"}, {"horde1", "horde1Upgr"}},
           {{"dwellingLvl1", "dwellingUpLvl1"},
            {"dwellingLvl2", "dwellingUpLvl2"},
            {"dwellingLvl3", "dwellingUpLvl3"},
            {"dwellingLvl4", "dwellingUpLvl4"}},
           {{"dwellingLvl5", "dwellingUpLvl5"},
            {"dwellingLvl6", "dwellingUpLvl6"},
            {"dwellingLvl7", "dwellingUpLvl7"}}},

          {// 3 (Inferno)
           {{"villageHall", "townHall", "cityHall", "capitol"},
            {"fort", "citadel", "castle"},
            {"tavern"},
            {"blacksmith"}},
           {{"marketplace", "resourceSilo"},
            {"mageGuild1", "mageGuild2", "mageGuild3", "mageGuild4",
             "mageGuild5"},
            {"special4"},
            {"special2"}},
           {{"special3"}, {"horde1", "horde1Upgr"}, {"horde2", "horde2Upgr"}},
           {{"dwellingLvl1", "dwellingUpLvl1"},
            {"dwellingLvl2", "dwellingUpLvl2"},
            {"dwellingLvl3", "dwellingUpLvl3"},
            {"dwellingLvl4", "dwellingUpLvl4"}},
           {{"dwellingLvl5", "dwellingUpLvl5"},
            {"dwellingLvl6", "dwellingUpLvl6"},
            {"dwellingLvl7", "dwellingUpLvl7"}}},
          // 4 (Inferno)
          {{{"villageHall", "townHall", "cityHall", "capitol"},
            {"fort", "citadel", "castle"},
            {"tavern"},
            {"blacksmith"}},
           {{"marketplace", "resourceSilo"},
            {"mageGuild1", "mageGuild2", "mageGuild3", "mageGuild4",
             "mageGuild5"},
            {"special2"},
            {"shipyard"}},
           {{"special1"}, {"special3"}, {"horde1", "horde1Upgr"}},
           {{"dwellingLvl1", "dwellingUpLvl1"},
            {"dwellingLvl2", "dwellingUpLvl2"},
            {"dwellingLvl3", "dwellingUpLvl3"},
            {"dwellingLvl4", "dwellingUpLvl4"}},
           {{"dwellingLvl5", "dwellingUpLvl5"},
            {"dwellingLvl6", "dwellingUpLvl6"},
            {"dwellingLvl7", "dwellingUpLvl7"}}},
          // 5
          {{{"villageHall", "townHall", "cityHall", "capitol"},
            {"fort", "citadel", "castle"},
            {"tavern"},
            {"blacksmith"}},
           {{"marketplace", "resourceSilo"},
            {"mageGuild1", "mageGuild2", "mageGuild3", "mageGuild4",
             "mageGuild5"},
            {"special2"},
            {"special3"}},
           {{"special1"}, {"special4"}, {"horde1", "horde1Upgr"}},
           {{"dwellingLvl1", "dwellingUpLvl1"},
            {"dwellingLvl2", "dwellingUpLvl2"},
            {"dwellingLvl3", "dwellingUpLvl3"},
            {"dwellingLvl4", "dwellingUpLvl4"}},
           {{"dwellingLvl5", "dwellingUpLvl5"},
            {"dwellingLvl6", "dwellingUpLvl6"},
            {"dwellingLvl7", "dwellingUpLvl7"}}},
          // 6
          {{{"villageHall", "townHall", "cityHall", "capitol"},
            {"fort", "citadel", "castle"},
            {"tavern"},
            {"blacksmith"}},
           {{"marketplace", "resourceSilo"},
            {"mageGuild1", "mageGuild2", "mageGuild3"},
            {"special4"},
            {"special1"}},
           {{"special2"}, {"special3"}, {"horde1", "horde1Upgr"}},
           {{"dwellingLvl1", "dwellingUpLvl1"},
            {"dwellingLvl2", "dwellingUpLvl2"},
            {"dwellingLvl3", "dwellingUpLvl3"},
            {"dwellingLvl4", "dwellingUpLvl4"}},
           {{"dwellingLvl5", "dwellingUpLvl5"},
            {"dwellingLvl6", "dwellingUpLvl6"},
            {"dwellingLvl7", "dwellingUpLvl7"}}},
          {
              // 7 (Fortress)
              {{"villageHall", "townHall", "cityHall", "capitol"},
               {"fort", "citadel", "castle"},
               {"tavern"},
               {"blacksmith"}},
              {{"marketplace", "resourceSilo"},
               {"mageGuild1", "mageGuild2", "mageGuild3"},
               {"shipyard"}},
              {{"special1"},
               {"special2", "special3"},
               {"horde1", "horde1Upgr"}},
              {{"dwellingLvl1", "dwellingUpLvl1"},
               {"dwellingLvl2", "dwellingUpLvl2"},
               {"dwellingLvl3", "dwellingUpLvl3"},
               {"dwellingLvl4", "dwellingUpLvl4"}},
              {{"dwellingLvl5", "dwellingUpLvl5"},
               {"dwellingLvl6", "dwellingUpLvl6"},
               {"dwellingLvl7", "dwellingUpLvl7"}}
              //
          },
  };

  const static inline std::unordered_map<std::string, std::string> townBuilds[] = {
      {
          // 0
          {"extraAnimation", "TBCSEXT2.def"},
          {"mageGuild1", "TBCSMAGE.def"},
          {"mageGuild2", "TBCSMAG2.def"},
          {"mageGuild3", "TBCSMAG3.def"},
          {"mageGuild4", "TBCSMAG4.def"},
          {"tavern", "TBCSTVRN.def"},
          {"shipyard", "TBCSDOCK.def"},
          {"fort", "TBCSCSTL.def"},
          {"citadel", "TBCSCAS2.def"},
          {"castle", "TBCSCAS3.def"},
          {"villageHall", "TBCSHALL.def"},
          {"townHall", "TBCSHAL2.def"},
          {"cityHall", "TBCSHAL3.def"},
          {"capitol", "TBCSHAL4.def"},
          {"marketplace", "TBCSMARK.def"},
          {"resourceSilo", "TBCSSILO.def"},
          {"blacksmith", "TBCSBLAK.def"},
          {"special1", "TBCSSPEC.def"},
          {"horde1", "TBCSHRD1.def"},
          {"horde1Upgr", "TBCSHRD2.def"},
          {"ship", "TBCSBOAT.def"},
          {"special2", "TBCSEXT0.def"},
          {"special3", "TBCSEXT1.def"},
          {"grail", "TBCSHOLY.def"},
          {"dwellingLvl1", "TBCSDW_0.def"},
          {"dwellingLvl2", "TBCSDW_1.def"},
          {"dwellingLvl3", "TBCSDW_2.def"},
          {"dwellingLvl4", "TBCSDW_3.def"},
          {"dwellingLvl5", "TBCSDW_4.def"},
          {"dwellingLvl6", "TBCSDW_5.def"},
          {"dwellingLvl7", "TBCSDW_6.def"},
          {"dwellingUpLvl1", "TBCSUP_0.def"},
          {"dwellingUpLvl2", "TBCSUP_1.def"},
          {"dwellingUpLvl3", "TBCSUP_2.def"},
          {"dwellingUpLvl4", "TBCSUP_3.def"},
          {"dwellingUpLvl5", "TBCSUP_4.def"},
          {"dwellingUpLvl6", "TBCSUP_5.def"},
          {"dwellingUpLvl7", "TBCSUP_6.def"},
      },
      {
          // 1
          {"extraAnimation", "TBRMEXT2.def"},
          {"mageGuild1", "TBRMMAGE.def"},
          {"mageGuild2", "TBRMMAG2.def"},
          {"mageGuild3", "TBRMMAG3.def"},
          {"mageGuild4", "TBRMMAG4.def"},
          {"mageGuild5", "TBRMMAG5.def"},
          {"tavern", "TBRMTVRN.def"},
          {"fort", "TBRMCSTL.def"},
          {"citadel", "TBRMCAS2.def"},
          {"castle", "TBRMCAS3.def"},
          {"villageHall", "TBRMHALL.def"},
          {"townHall", "TBRMHAL2.def"},
          {"cityHall", "TBRMHAL3.def"},
          {"capitol", "TBRMHAL4.def"},
          {"marketplace", "TBRMMARK.def"},
          {"resourceSilo", "TBRMSILO.def"},
          {"blacksmith", "TBRMBLAK.def"},
          {"special1", "TBRMSPEC.def"},
          {"special2", "TBRMEXT0.def"},
          {"special3", "TBRMEXT1.def"},
          {"grail", "TBRMHOLY.def"},
          {"extraTownHall", "TBRMEXT3.def"},
          {"extraCityHall", "TBRMEXT4.def"},
          {"extraCapitol", "TBRMEXT5.def"},
          {"horde1", "TBRMHRD1.def"},
          {"horde1Upgr", "TBRMHRD2.def"},
          {"horde2", "TBRMHRD3.def"},
          {"horde2Upgr", "TBRMHRD4.def"},
          {"dwellingLvl1", "TBRMDW_0.def"},
          {"dwellingLvl2", "TBRMDW_1.def"},
          {"dwellingLvl3", "TBRMDW_2.def"},
          {"dwellingLvl4", "TBRMDW_3.def"},
          {"dwellingLvl5", "TBRMDW_4.def"},
          {"dwellingLvl6", "TBRMDW_5.def"},
          {"dwellingLvl7", "TBRMDW_6.def"},
          {"dwellingUpLvl1", "TBRMUP_0.def"},
          {"dwellingUpLvl2", "TBRMUP_1.def"},
          {"dwellingUpLvl3", "TBRMUP_2.def"},
          {"dwellingUpLvl4", "TBRMUP_3.def"},
          {"dwellingUpLvl5", "TBRMUP_4.def"},
          {"dwellingUpLvl6", "TBRMUP_5.def"},
          {"dwellingUpLvl7", "TBRMUP_6.def"}
          //
      },
      {
          // 2
          {"mageGuild1", "TBTWMAGE.def"},
          {"mageGuild2", "TBTWMAG2.def"},
          {"mageGuild3", "TBTWMAG3.def"},
          {"mageGuild4", "TBTWMAG4.def"},
          {"mageGuild5", "TBTWMAG5.def"},
          {"tavern", "TBTWTVRN.def"},
          {"fort", "TBTWCSTL.def"},
          {"citadel", "TBTWCAS2.def"},
          {"castle", "TBTWCAS3.def"},
          {"villageHall", "TBTWHALL.def"},
          {"townHall", "TBTWHAL2.def"},
          {"cityHall", "TBTWHAL3.def"},
          {"capitol", "TBTWHAL4.def"},
          {"marketplace", "TBTWMARK.def"},
          {"resourceSilo", "TBTWSILO.def"},
          {"blacksmith", "TBTWBLAK.def"},
          {"special1", "TBTWSPEC.def"},
          {"horde1", "TBTWHRD1.def"},
          {"horde1Upgr", "TBTWHRD2.def"},
          {"special2", "TBTWEXT0.def"},
          {"special3", "TBTWEXT1.def"},
          {"special4", "TBTWEXT2.def"},
          {"grail", "TBTWHOLY.def"},
          {"dwellingLvl1", "TBTWDW_0.def"},
          {"dwellingLvl2", "TBTWDW_1.def"},
          {"dwellingLvl3", "TBTWDW_2.def"},
          {"dwellingLvl4", "TBTWDW_3.def"},
          {"dwellingLvl5", "TBTWDW_4.def"},
          {"dwellingLvl6", "TBTWDW_5.def"},
          {"dwellingLvl7", "TBTWDW_6.def"},
          {"dwellingUpLvl1", "TBTWUP_0.def"},
          {"dwellingUpLvl2", "TBTWUP_1.def"},
          {"dwellingUpLvl3", "TBTWUP_2.def"},
          {"dwellingUpLvl4", "TBTWUP_3.def"},
          {"dwellingUpLvl5", "TBTWUP_4.def"},
          {"dwellingUpLvl6", "TBTWUP_5.def"},
          {"dwellingUpLvl7", "TBTWUP_6.def"},
      },
      {// 3 (Inferno)
       {"mageGuild1", "TBINMAGE.def"},     {"mageGuild2", "TBINMAG2.def"},
       {"mageGuild3", "TBINMAG3.def"},     {"mageGuild4", "TBINMAG4.def"},
       {"mageGuild5", "TBINMAG5.def"},     {"tavern", "TBINTVRN.def"},
       {"fort", "TBINCSTL.def"},           {"citadel", "TBINCAS2.def"},
       {"castle", "TBINCAS3.def"},         {"villageHall", "TBINHALL.def"},
       {"townHall", "TBINHAL2.def"},       {"cityHall", "TBINHAL3.def"},
       {"capitol", "TBINHAL4.def"},        {"marketplace", "TBINMARK.def"},
       {"resourceSilo", "TBINSILO.def"},   {"blacksmith", "TBINBLAK.def"},
       {"special2", "TBINEXT0.def"},       {"special3", "TBINEXT1.def"},
       {"special4", "TBINEXT2.def"},       {"horde1", "TBINHRD1.def"},
       {"horde1Upgr", "TBINHRD2.def"},     {"horde2", "TBINHRD3.def"},
       {"horde2Upgr", "TBINHRD4.def"},     {"grail", "TBINHOLY.def"},
       {"dwellingLvl1", "TBINDW_0.def"},   {"dwellingLvl2", "TBINDW_1.def"},
       {"dwellingLvl3", "TBINDW_2.def"},   {"dwellingLvl4", "TBINDW_3.def"},
       {"dwellingLvl5", "TBINDW_4.def"},   {"dwellingLvl6", "TBINDW_5.def"},
       {"dwellingLvl7", "TBINDW_6.def"},   {"dwellingUpLvl1", "TBINUP_0.def"},
       {"dwellingUpLvl2", "TBINUP_1.def"}, {"dwellingUpLvl3", "TBINUP_2.def"},
       {"dwellingUpLvl4", "TBINUP_3.def"}, {"dwellingUpLvl5", "TBINUP_4.def"},
       {"dwellingUpLvl6", "TBINUP_5.def"}, {"dwellingUpLvl7", "TBINUP_6.def"}},
      {{"extraAnimation", "TBNCEXT2.def"}, {"mageGuild1", "TBNCMAGE.def"},
       {"mageGuild2", "TBNCMAG2.def"},     {"mageGuild3", "TBNCMAG3.def"},
       {"mageGuild4", "TBNCMAG4.def"},     {"mageGuild5", "TBNCMAG5.def"},
       {"tavern", "TBNCTVRN.def"},         {"shipyard", "TBNCDOCK.def"},
       {"fort", "TBNCCSTL.def"},           {"citadel", "TBNCCAS2.def"},
       {"castle", "TBNCCAS3.def"},         {"villageHall", "TBNCHALL.def"},
       {"townHall", "TBNCHAL2.def"},       {"cityHall", "TBNCHAL3.def"},
       {"capitol", "TBNCHAL4.def"},        {"marketplace", "TBNCMARK.def"},
       {"resourceSilo", "TBNCSILO.def"},   {"blacksmith", "TBNCBLAK.def"},
       {"special1", "TBNCSPEC.def"},       {"horde1", "TBNCHRD1.def"},
       {"horde1Upgr", "TBNCHRD2.def"},     {"ship", "TBNCBOAT.def"},
       {"special2", "TBNCEXT0.def"},       {"special3", "TBNCEXT1.def"},
       {"grail", "TBNCHOLY.def"},          {"extraTownHall", "TBNCEXT3.def"},
       {"extraCityHall", "TBNCEXT4.def"},  {"extraCapitol", "TBNCEXT5.def"},
       {"dwellingLvl1", "TBNCDW_0.def"},   {"dwellingLvl2", "TBNCDW_1.def"},
       {"dwellingLvl3", "TBNCDW_2.def"},   {"dwellingLvl4", "TBNCDW_3.def"},
       {"dwellingLvl5", "TBNCDW_4.def"},   {"dwellingLvl6", "TBNCDW_5.def"},
       {"dwellingLvl7", "TBNCDW_6.def"},   {"dwellingUpLvl1", "TBNCUP_0.def"},
       {"dwellingUpLvl2", "TBNCUP_1.def"}, {"dwellingUpLvl3", "TBNCUP_2.def"},
       {"dwellingUpLvl4", "TBNCUP_3.def"}, {"dwellingUpLvl5", "TBNCUP_4.def"},
       {"dwellingUpLvl6", "TBNCUP_5.def"}, {"dwellingUpLvl7", "TBNCUP_6.def"}},
      {{"mageGuild1", "TBDNMAGE.def"},     {"mageGuild2", "TBDNMAG2.def"},
       {"mageGuild3", "TBDNMAG3.def"},     {"mageGuild4", "TBDNMAG4.def"},
       {"mageGuild5", "TBDNMAG5.def"},     {"tavern", "TBDNTVRN.def"},
       {"fort", "TBDNCSTL.def"},           {"citadel", "TBDNCAS2.def"},
       {"castle", "TBDNCAS3.def"},         {"villageHall", "TBDNHALL.def"},
       {"townHall", "TBDNHAL2.def"},       {"cityHall", "TBDNHAL3.def"},
       {"capitol", "TBDNHAL4.def"},        {"marketplace", "TBDNMARK.def"},
       {"resourceSilo", "TBDNSILO.def"},   {"blacksmith", "TBDNBLAK.def"},
       {"special1", "TBDNSPEC.def"},       {"horde1", "TBDNHRD1.def"},
       {"horde1Upgr", "TBDNHRD2.def"},     {"special2", "TBDNEXT0.def"},
       {"special3", "TBDNEXT1.def"},       {"special4", "TBDNEXT2.def"},
       {"grail", "TBDNHOLY.def"},          {"dwellingLvl1", "TBDNDW_0.def"},
       {"dwellingLvl2", "TBDNDW_1.def"},   {"dwellingLvl3", "TBDNDW_2.def"},
       {"dwellingLvl4", "TBDNDW_3.def"},   {"dwellingLvl5", "TBDNDW_4.def"},
       {"dwellingLvl6", "TBDNDW_5.def"},   {"dwellingLvl7", "TBDNDW_6.def"},
       {"dwellingUpLvl1", "TBDNUP_0.def"}, {"dwellingUpLvl2", "TBDNUP_1.def"},
       {"dwellingUpLvl3", "TBDNUP_2.def"}, {"dwellingUpLvl4", "TBDNUP_3.def"},
       {"dwellingUpLvl5", "TBDNUP_4.def"}, {"dwellingUpLvl6", "TBDNUP_5.def"},
       {"dwellingUpLvl7", "TBDNUP_6.def"}},
      {{"extraAnimation", "TBSTEXT3.def"}, {"mageGuild1", "TBSTMAGE.def"},
       {"mageGuild2", "TBSTMAG2.def"},     {"mageGuild3", "TBSTMAG3.def"},
       {"tavern", "TBSTTVRN.def"},         {"fort", "TBSTCSTL.def"},
       {"citadel", "TBSTCAS2.def"},        {"castle", "TBSTCAS3.def"},
       {"villageHall", "TBSTHALL.def"},    {"townHall", "TBSTHAL2.def"},
       {"cityHall", "TBSTHAL3.def"},       {"capitol", "TBSTHAL4.def"},
       {"marketplace", "TBSTMARK.def"},    {"resourceSilo", "TBSTSILO.def"},
       {"blacksmith", "TBSTBLAK.def"},     {"special1", "TBSTSPEC.def"},
       {"horde1", "TBSTHRD1.def"},         {"horde1Upgr", "TBSTHRD2.def"},
       {"special2", "TBSTEXT0.def"},       {"special3", "TBSTEXT1.def"},
       {"special4", "TBSTEXT2.def"},       {"grail", "TBSTHOLY.def"},
       {"dwellingLvl1", "TBSTDW_0.def"},   {"dwellingLvl2", "TBSTDW_1.def"},
       {"dwellingLvl3", "TBSTDW_2.def"},   {"dwellingLvl4", "TBSTDW_3.def"},
       {"dwellingLvl5", "TBSTDW_4.def"},   {"dwellingLvl6", "TBSTDW_5.def"},
       {"dwellingLvl7", "TBSTDW_6.def"},   {"dwellingUpLvl1", "TBSTUP_0.def"},
       {"dwellingUpLvl2", "TBSTUP_1.def"}, {"dwellingUpLvl3", "TBSTUP_2.def"},
       {"dwellingUpLvl4", "TBSTUP_3.def"}, {"dwellingUpLvl5", "TBSTUP_4.def"},
       {"dwellingUpLvl6", "TBSTUP_5.def"}, {"dwellingUpLvl7", "TBSTUP_6.def"}},
      {
          // 7 (Fortress)
          {"extraAnimation", "TBFREXT2.def"},
          {"mageGuild1", "TBFRMAGE.def"},
          {"mageGuild2", "TBFRMAG2.def"},
          {"mageGuild3", "TBFRMAG3.def"},
          {"tavern", "TBFRTVRN.def"},
          {"shipyard", "TBFRDOCK.def"},
          {"fort", "TBFRCSTL.def"},
          {"citadel", "TBFRCAS2.def"},
          {"castle", "TBFRCAS3.def"},
          {"villageHall", "TBFRHALL.def"},
          {"townHall", "TBFRHAL2.def"},
          {"cityHall", "TBFRHAL3.def"},
          {"capitol", "TBFRHAL4.def"},
          {"marketplace", "TBFRMARK.def"},
          {"resourceSilo", "TBFRSILO.def"},
          {"blacksmith", "TBFRBLAK.def"},
          {"special1", "TBFRSPEC.def"},
          {"horde1", "TBFRHRD1.def"},
          {"horde1Upgr", "TBFRHRD2.def"},
          {"ship", "TBFRBOAT.def"},
          {"special2", "TBFREXT0.def"},
          {"special3", "TBFREXT1.def"},
          {"grail", "TBFRHOLY.def"},
          {"extraCapitol", "TBFRWTRW.def"},
          {"dwellingLvl1", "TBFRDW_0.def"},
          {"dwellingLvl2", "TBFRDW_1.def"},
          {"dwellingLvl3", "TBFRDW_3.def"},
          {"dwellingLvl4", "TBFRDW_4.def"},
          {"dwellingLvl5", "TBFRDW_2.def"},
          {"dwellingLvl6", "TBFRDW_5.def"},
          {"dwellingLvl7", "TBFRDW_6.def"},
          {"dwellingUpLvl1", "TBFRUP_0.def"},
          {"dwellingUpLvl2", "TBFRUP_1.def"},
          {"dwellingUpLvl3", "TBFRUP_3.def"},
          {"dwellingUpLvl4", "TBFRUP_4.def"},
          {"dwellingUpLvl5", "TBFRUP_2.def"},
          {"dwellingUpLvl6", "TBFRUP_5.def"},
          {"dwellingUpLvl7", "TBFRUP_6.def"},
      },
  };

  const static inline std::unordered_map<std::string, std::string>
      townBorder[] = {
          {
              {"mageGuild1", "TOCSMAG1.pcx"},
              {"mageGuild2", "TOCSMAG2.pcx"},
              {"mageGuild3", "TOCSM301.pcx"},
              {"mageGuild4", "TOCSM401.pcx"},
              {"tavern", "TOCSTAV1.pcx"},
              {"shipyard", "TOCSDKMS.pcx"},
              {"fort", "TOCSCAS1.pcx"},
              {"citadel", "TOCSCAS2.pcx"},
              {"castle", "TOCSCAS3.pcx"},
              {"villageHall", "TOCSH101.pcx"},
              {"townHall", "TOCSH201.pcx"},
              {"cityHall", "TOCSH301.pcx"},
              {"capitol", "TOCSH401.pcx"},
              {"marketplace", "TOCSMRK1.pcx"},
              {"resourceSilo", "TOCSMRK2.pcx"},
              {"blacksmith", "TOCSBLAK.pcx"},
              {"special1", "TOCSLT01.pcx"},
              {"horde1", "TOCSGR1H.pcx"},
              {"horde1Upgr", "TOCSGR2H.pcx"},
              {"ship", "TOCSDKMN.pcx"},
              {"special2", "TOCSCAVM.pcx"},
              {"special3", "TOCSTAV2.pcx"},
              {"grail", "TOCSHOLY.pcx"},
              {"dwellingLvl1", "TOCSPIK1.pcx"},
              {"dwellingLvl2", "TOCSCRS1.pcx"},
              {"dwellingLvl3", "TOCSGR1N.pcx"},
              {"dwellingLvl4", "TOCSSWD1.pcx"},
              {"dwellingLvl5", "TOCSMON1.pcx"},
              {"dwellingLvl6", "TOCSC101.pcx"},
              {"dwellingLvl7", "TOCSANG1.pcx"},
              {"dwellingUpLvl1", "TOCSPIK2.pcx"},
              {"dwellingUpLvl2", "TOCSCRS2.pcx"},
              {"dwellingUpLvl3", "TOCSGR2N.pcx"},
              {"dwellingUpLvl4", "TOCSSWD2.pcx"},
              {"dwellingUpLvl5", "TOCSMON2.pcx"},
              {"dwellingUpLvl6", "TOCSCAV2.pcx"},
              {"dwellingUpLvl7", "TOCSANG2.pcx"},
          },
          {
              {"mageGuild1", "TORMAG1.pcx"},
              {"mageGuild2", "TORMAG2.pcx"},
              {"mageGuild3", "TORMAG3.pcx"},
              {"mageGuild4", "TORMAG4.pcx"},
              {"mageGuild5", "TORMAG5.pcx"},
              {"tavern", "TORTAV.pcx"},
              {"fort", "TORCAS1.pcx"},
              {"citadel", "TORCAS3.pcx"},
              {"castle", "TORCAS2.pcx"},
              {"villageHall", "TORHAL1.pcx"},
              {"townHall", "TORHAL2.pcx"},
              {"cityHall", "TORHAL3.pcx"},
              {"capitol", "TORHAL4.pcx"},
              {"marketplace", "TORMRK1.pcx"},
              {"resourceSilo", "TORMRK2.pcx"},
              {"blacksmith", "TORAID.pcx"},
              {"special1", "TORGAR1A.pcx"},
              {"horde1", "TORDWF1H.pcx"},
              {"horde1Upgr", "TORDWF2H.pcx"},
              {"special2", "TORGAR2A.pcx"},
              {"special3", "TORDWFT.pcx"},
              {"horde2", "TORTRE1H.pcx"},
              {"horde2Upgr", "TORTRE2H.pcx"},
              {"grail", "TORHOLY.pcx"},
              {"dwellingLvl1", "TORCEN1A.pcx"},
              {"dwellingLvl2", "TORDWF1.pcx"},
              {"dwellingLvl3", "TORELF1.pcx"},
              {"dwellingLvl4", "TORPEG1A.pcx"},
              {"dwellingLvl5", "TORTRE1.pcx"},
              {"dwellingLvl6", "TORUNI1.pcx"},
              {"dwellingLvl7", "TORDR1AA.pcx"},
              {"dwellingUpLvl1", "TORCEN2A.pcx"},
              {"dwellingUpLvl2", "TORDWF2.pcx"},
              {"dwellingUpLvl3", "TORELF2.pcx"},
              {"dwellingUpLvl4", "TORPEG2A.pcx"},
              {"dwellingUpLvl5", "TORTRE2.pcx"},
              {"dwellingUpLvl6", "TORUNI2.pcx"},
              {"dwellingUpLvl7", "TORDR2AA.pcx"},
          },
          {
              {"mageGuild1", "TOTGLD1.pcx"},
              {"mageGuild2", "TOTGLD2.pcx"},
              {"mageGuild3", "TOTGLD3.pcx"},
              {"mageGuild4", "TOTGLD4.pcx"},
              {"mageGuild5", "TOTGLD5.pcx"},
              {"tavern", "TOTTAV.pcx"},
              {"fort", "TOTCAS1.pcx"},
              {"citadel", "TOTCAS2.pcx"},
              {"castle", "TOTCAS3.pcx"},
              {"villageHall", "TOTHAL1.pcx"},
              {"townHall", "TOTHAL2.pcx"},
              {"cityHall", "TOTHAL3.pcx"},
              {"capitol", "TOTHAL4.pcx"},
              {"marketplace", "TOTMRK.pcx"},
              {"resourceSilo", "TOTMRKS.pcx"},
              {"blacksmith", "TOTBLKA.pcx"},
              {"special1", "TOTMRKA.pcx"},
              {"special2", "TOTCASW.pcx"},
              {"special3", "TOTGLDL.pcx"},
              {"special4", "TOTGLDW.pcx"},
              {"horde1", "TOTGAR1H.pcx"},
              {"horde1Upgr", "TOTGAR2H.pcx"},
              {"grail", "TOTHOLYA.pcx"},
              {"dwellingLvl1", "TOTGRM1A.pcx"},
              {"dwellingLvl2", "TOTGAR1.pcx"},
              {"dwellingLvl3", "TOTGOL1A.pcx"},
              {"dwellingLvl4", "TOTMAG1.pcx"},
              {"dwellingLvl5", "TOTGEN1.pcx"},
              {"dwellingLvl6", "TOTNAG1.pcx"},
              {"dwellingLvl7", "TOTTIT1.pcx"},
              {"dwellingUpLvl1", "TOTGRM2A.pcx"},
              {"dwellingUpLvl2", "TOTGAR2.pcx"},
              {"dwellingUpLvl3", "TOTGOL2A.pcx"},
              {"dwellingUpLvl4", "TOTMAG2.pcx"},
              {"dwellingUpLvl5", "TOTGEN2.pcx"},
              {"dwellingUpLvl6", "TOTNAG2.pcx"},
              {"dwellingUpLvl7", "TOTTIT2.pcx"},
          },
          {{"mageGuild1", "TOIMAG1A.pcx"},
           {"mageGuild2", "TOIMAG2A.pcx"},
           {"mageGuild3", "TOIMAG3A.pcx"},
           {"mageGuild4", "TOIMAG4A.pcx"},
           {"mageGuild5", "TOIMAG5A.pcx"},
           {"tavern", "TOITAV.pcx"},
           {"fort", "TOICAS2A.pcx"},
           {"citadel", "TOICAS1A.pcx"},
           {"castle", "TOICAS3A.pcx"},
           {"villageHall", "TOIHAL1.pcx"},
           {"townHall", "TOIHAL2.pcx"},
           {"cityHall", "TOIHAL3.pcx"},
           {"capitol", "TOIHAL4.pcx"},
           {"marketplace", "TOIMAR1.pcx"},
           {"resourceSilo", "TOIMAR2.pcx"},
           {"blacksmith", "TOIBLKA.pcx"},
           {"special2", "TOICAB1A.pcx"},
           {"special3", "TOICASGA.pcx"},
           {"special4", "TOIPAIN.pcx"},
           {"horde1", "TOIMP1HA.pcx"},
           {"horde1Upgr", "TOIMP2HA.pcx"},
           {"horde2", "TOIHND1H.pcx"},
           {"horde2Upgr", "TOIHND2H.pcx"},
           {"grail", "TOIHOLY.pcx"},
           {"dwellingLvl1", "TOIMP1A.pcx"},
           {"dwellingLvl2", "TOIGOG1A.pcx"},
           {"dwellingLvl3", "TOIHND1.pcx"},
           {"dwellingLvl4", "TOIDMN1.pcx"},
           {"dwellingLvl5", "TOIPIT1.pcx"},
           {"dwellingLvl6", "TOIEFR1.pcx"},
           {"dwellingLvl7", "TOIDVL1.pcx"},
           {"dwellingUpLvl1", "TOIMP2A.pcx"},
           {"dwellingUpLvl2", "TOIGOG2A.pcx"},
           {"dwellingUpLvl3", "TOIHND2.pcx"},
           {"dwellingUpLvl4", "TOIDMN2.pcx"},
           {"dwellingUpLvl5", "TOIPIT2.pcx"},
           {"dwellingUpLvl6", "TOIEFR2.pcx"},
           {"dwellingUpLvl7", "TOIDVL2.pcx"}},
          {{"mageGuild1", "TONMAG1.pcx"},
           {"mageGuild2", "TONMAG2.pcx"},
           {"mageGuild3", "TONMAG3.pcx"},
           {"mageGuild4", "TONMAG4.pcx"},
           {"mageGuild5", "TONMAG5.pcx"},
           {"tavern", "TONTAV.pcx"},
           {"shipyard", "TONSHPBA.pcx"},
           {"fort", "TONCAS1.pcx"},
           {"citadel", "TONCAS2.pcx"},
           {"castle", "TONCAS3.pcx"},
           {"villageHall", "TONHAL1.pcx"},
           {"townHall", "TONHAL2.pcx"},
           {"cityHall", "TONHAL3.pcx"},
           {"capitol", "TONHAL4.pcx"},
           {"marketplace", "TONMRK1.pcx"},
           {"resourceSilo", "TONMRK2.pcx"},
           {"blacksmith", "TONSMITA.pcx"},
           {"special1", "TONSHRDA.pcx"},
           {"horde1", "TONSKE1H.pcx"},
           {"horde1Upgr", "TONSKE2H.pcx"},
           {"ship", "TONSHPNA.pcx"},
           {"special2", "TONNECRA.pcx"},
           {"special3", "TONSKELT.pcx"},
           {"grail", "TONHOLYA.pcx"},
           {"dwellingLvl1", "TONSKEL1.pcx"},
           {"dwellingLvl2", "TONZOMB1.pcx"},
           {"dwellingLvl3", "TONWIGH1.pcx"},
           {"dwellingLvl4", "TONVAM1.pcx"},
           {"dwellingLvl5", "TONLICH1.pcx"},
           {"dwellingLvl6", "TONBKN1.pcx"},
           {"dwellingLvl7", "TONBON1.pcx"},
           {"dwellingUpLvl1", "TONSKEL2.pcx"},
           {"dwellingUpLvl2", "TONZOMB2.pcx"},
           {"dwellingUpLvl3", "TONWIGH2.pcx"},
           {"dwellingUpLvl4", "TONVAM2.pcx"},
           {"dwellingUpLvl5", "TONLICH2.pcx"},
           {"dwellingUpLvl6", "TONBKN2.pcx"},
           {"dwellingUpLvl7", "TONBON2.pcx"}},
          {
              {"mageGuild1", "TODMAG1.pcx"},
              {"mageGuild2", "TODMAG2.pcx"},
              {"mageGuild3", "TODMAG3.pcx"},
              {"mageGuild4", "TODMAG4.pcx"},
              {"mageGuild5", "TODMAG5.pcx"},
              {"tavern", "TODTAV.pcx"},
              {"fort", "TODCAS1.pcx"},
              {"citadel", "TODCAS2.pcx"},
              {"castle", "TODCAS3.pcx"},
              {"villageHall", "TODHALL1.pcx"},
              {"townHall", "TODHALL2.pcx"},
              {"cityHall", "TODHALL3.pcx"},
              {"capitol", "TODHALL4.pcx"},
              {"marketplace", "TODMARK.pcx"},
              {"resourceSilo", "TODSILO.pcx"},
              {"blacksmith", "TODSMITH.pcx"},
              {"special1", "TODART.pcx"},
              {"horde1", "TODTR1HA.pcx"},
              {"horde1Upgr", "TODTR2HA.pcx"},
              {"special2", "TODVOR1A.pcx"},
              {"special3", "TODPORTA.pcx"},
              {"special4", "TODACAD.pcx"},
              {"grail", "TODHOLY.pcx"},
              {"dwellingLvl1", "TODTRG1A.pcx"},
              {"dwellingLvl2", "TODHAR1.pcx"},
              {"dwellingLvl3", "TODBEH1A.pcx"},
              {"dwellingLvl4", "TODMED1.pcx"},
              {"dwellingLvl5", "TODMIN1.pcx"},
              {"dwellingLvl6", "TODMAN1.pcx"},
              {"dwellingLvl7", "TODDRA1A.pcx"},
              {"dwellingUpLvl1", "TODTRG2A.pcx"},
              {"dwellingUpLvl2", "TODHAR2.pcx"},
              {"dwellingUpLvl3", "TODBEH2A.pcx"},
              {"dwellingUpLvl4", "TODMED2.pcx"},
              {"dwellingUpLvl5", "TODMIN2.pcx"},
              {"dwellingUpLvl6", "TODMAN2.pcx"},
              {"dwellingUpLvl7", "TODDRA2A.pcx"},
          },
          {
              {"mageGuild1", "TOSMAG1.pcx"},
              {"mageGuild2", "TOSMAG2.pcx"},
              {"mageGuild3", "TOSMAG3.pcx"},
              {"tavern", "TOSTAV.pcx"},
              {"fort", "TOSCA1.pcx"},
              {"citadel", "TOSCA2.pcx"},
              {"castle", "TOSCA3.pcx"},
              {"villageHall", "TOSHAL1A.pcx"},
              {"townHall", "TOSHAL2A.pcx"},
              {"cityHall", "TOSHAL3A.pcx"},
              {"capitol", "TOSHAL4A.pcx"},
              {"marketplace", "TOSMRK1.pcx"},
              {"resourceSilo", "TOSMRK2.pcx"},
              {"blacksmith", "TOSBLK1.pcx"},
              {"special1", "TOSCA1EA.pcx"},
              {"horde1", "TOSGOB1H.pcx"},
              {"horde1Upgr", "TOSGOB2H.pcx"},
              {"special2", "TOSMRK1C.pcx"},
              {"special3", "TOSBLK2.pcx"},
              {"special4", "TOSVAH.pcx"},
              {"grail", "TOSHOLYA.pcx"},
              {"dwellingLvl1", "TOSGOB1.pcx"},
              {"dwellingLvl2", "TOSWOL1.pcx"},
              {"dwellingLvl3", "TOSORC1.pcx"},
              {"dwellingLvl4", "TOSOGR1.pcx"},
              {"dwellingLvl5", "TOSROC1.pcx"},
              {"dwellingLvl6", "TOSCYC1.pcx"},
              {"dwellingLvl7", "TOSBEH1A.pcx"},
              {"dwellingUpLvl1", "TOSGOB2.pcx"},
              {"dwellingUpLvl2", "TOSWOL2.pcx"},
              {"dwellingUpLvl3", "TOSORC2.pcx"},
              {"dwellingUpLvl4", "TOSOGR2.pcx"},
              {"dwellingUpLvl5", "TOSROC2.pcx"},
              {"dwellingUpLvl6", "TOSCYC2A.pcx"},
              {"dwellingUpLvl7", "TOSBEH2A.pcx"},
          },
          {
              // 7 (Fortress)
              {"mageGuild1", "TOFMAG1A.pcx"},
              {"mageGuild2", "TOFMAG2A.pcx"},
              {"mageGuild3", "TOFMAG3A.pcx"},
              {"tavern", "TOFTAVA.pcx"},
              {"shipyard", "TOFDCK2.pcx"},
              {"fort", "TOFCAS1.pcx"},
              {"citadel", "TOFCAS2.pcx"},
              {"castle", "TOFCAS3.pcx"},
              {"villageHall", "TOFHAL1.pcx"},
              {"townHall", "TOFHAL2.pcx"},
              {"cityHall", "TOFHAL3.pcx"},
              {"capitol", "TOFHAL4.pcx"},
              {"marketplace", "TOFMRKAA.pcx"},
              {"resourceSilo", "TOFMRK2A.pcx"},
              {"blacksmith", "TOFAIDA.pcx"},
              {"special1", "TOFCAGE.pcx"},
              {"horde1", "TOFGNL1H.pcx"},
              {"horde1Upgr", "TOFGNL2H.pcx"},
              {"ship", "TOFDCK1.pcx"},
              {"special2", "TOFCASD.pcx"},
              {"special3", "TOFCASA.pcx"},
              {"grail", "TOFHLYAA.pcx"},
              {"dwellingLvl1", "TOFGNL1.pcx"},
              {"dwellingLvl2", "TOFLIZ1.pcx"},
              {"dwellingLvl3", "TOFFLY1A.pcx"},
              {"dwellingLvl4", "TOFBAS1.pcx"},
              {"dwellingLvl5", "TOFGOR1.pcx"},
              {"dwellingLvl6", "TOFWYV1.pcx"},
              {"dwellingLvl7", "TOFHYD1A.pcx"},
              {"dwellingUpLvl1", "TOFGNL2.pcx"},
              {"dwellingUpLvl2", "TOFLIZ2.pcx"},
              {"dwellingUpLvl3", "TOFFLY2A.pcx"},
              {"dwellingUpLvl4", "TOFBAS2.pcx"},
              {"dwellingUpLvl5", "TOFGOR2.pcx"},
              {"dwellingUpLvl6", "TOFWYV2.pcx"},
              {"dwellingUpLvl7", "TOFHYD2A.pcx"},
          },
  };
  const static inline std::unordered_map<std::string, std::string> townArea[] =
      {
          // 0
          {{"mageGuild1", "TZCSMAG1.pcx"},
           {"mageGuild2", "TZCSMAG2.pcx"},
           {"mageGuild3", "TZCSM301.pcx"},
           {"mageGuild4", "TZCSM401.pcx"},
           {"tavern", "TZCSTAV1.pcx"},
           {"shipyard", "TZCSDKMS.pcx"},
           {"fort", "TZCSCAS1.pcx"},
           {"citadel", "TZCSCAS2.pcx"},
           {"castle", "TZCSCAS3.pcx"},
           {"villageHall", "TZCSH101.pcx"},
           {"townHall", "TZCSH201.pcx"},
           {"cityHall", "TZCSH301.pcx"},
           {"capitol", "TZCSH401.pcx"},
           {"marketplace", "TZCSMRK1.pcx"},
           {"resourceSilo", "TZCSMRK2.pcx"},
           {"blacksmith", "TZCSBLAK.pcx"},
           {"special1", "TZCSLT01.pcx"},
           {"horde1", "TZCSGR1H.pcx"},
           {"horde1Upgr", "TZCSGR2H.pcx"},
           {"ship", "TZCSDKMN.pcx"},
           {"special2", "TZCSCAVM.pcx"},
           {"special3", "TZCSTAV2.pcx"},
           {"grail", "TZCSHOLY.pcx"},
           {"dwellingLvl1", "TZCSPIK1.pcx"},
           {"dwellingLvl2", "TZCSCRS1.pcx"},
           {"dwellingLvl3", "TZCSGR1N.pcx"},
           {"dwellingLvl4", "TZCSSWD1.pcx"},
           {"dwellingLvl5", "TZCSMON1.pcx"},
           {"dwellingLvl6", "TZCSCAV1.pcx"},
           {"dwellingLvl7", "TZCSANG1.pcx"},
           {"dwellingUpLvl1", "TZCSPIK2.pcx"},
           {"dwellingUpLvl2", "TZCSCRS2.pcx"},
           {"dwellingUpLvl3", "TZCSGR2N.pcx"},
           {"dwellingUpLvl4", "TZCSSWD2.pcx"},
           {"dwellingUpLvl5", "TZCSMON2.pcx"},
           {"dwellingUpLvl6", "TZCSCAV2.pcx"},
           {"dwellingUpLvl7", "TZCSANG2.pcx"}},
          {{"mageGuild1", "TZRMAG1.pcx"},
           {"mageGuild2", "TZRMAG2.pcx"},
           {"mageGuild3", "TZRMAG3.pcx"},
           {"mageGuild4", "TZRMAG4.pcx"},
           {"mageGuild5", "TZRMAG5.pcx"},
           {"tavern", "TZRTAV.pcx"},
           {"fort", "TZRCAS1.pcx"},
           {"citadel", "TZRCAS3.pcx"},
           {"castle", "TZRCAS2.pcx"},
           {"villageHall", "TZRHAL1.pcx"},
           {"townHall", "TZRHAL2.pcx"},
           {"cityHall", "TZRHAL3.pcx"},
           {"capitol", "TZRHAL4.pcx"},
           {"marketplace", "TZRMRK1.pcx"},
           {"resourceSilo", "TZRMRK2.pcx"},
           {"blacksmith", "TZRAID.pcx"},
           {"special1", "TZRGAR1A.pcx"},
           {"horde1", "TZRDWF1H.pcx"},
           {"horde1Upgr", "TZRDWF2H.pcx"},
           {"special2", "TZRGAR2A.pcx"},
           {"special3", "TZRDWFT.pcx"},
           {"horde2", "TZRTRE1H.pcx"},
           {"horde2Upgr", "TZRTRE2H.pcx"},
           {"grail", "TZRHOLY.pcx"},
           {"dwellingLvl1", "TZRCEN1A.pcx"},
           {"dwellingLvl2", "TZRDWF1.pcx"},
           {"dwellingLvl3", "TZRELF1.pcx"},
           {"dwellingLvl4", "TZRPEG1A.pcx"},
           {"dwellingLvl5", "TZRTRE1.pcx"},
           {"dwellingLvl6", "TZRUNI1.pcx"},
           {"dwellingLvl7", "TZRDR1AA.pcx"},
           {"dwellingUpLvl1", "TZRCEN2A.pcx"},
           {"dwellingUpLvl2", "TZRDWF2.pcx"},
           {"dwellingUpLvl3", "TZRELF2.pcx"},
           {"dwellingUpLvl4", "TZRPEG2A.pcx"},
           {"dwellingUpLvl5", "TZRTRE2.pcx"},
           {"dwellingUpLvl6", "TZRUNI2.pcx"},
           {"dwellingUpLvl7", "TZRDR2AA.pcx"}},
          {{"mageGuild1", "TZTGLD1.pcx"},
           {"mageGuild2", "TZTGLD2.pcx"},
           {"mageGuild3", "TZTGLD3.pcx"},
           {"mageGuild4", "TZTGLD4.pcx"},
           {"mageGuild5", "TZTGLD5.pcx"},
           {"tavern", "TZTTAV.pcx"},
           {"fort", "TZTCAS1.pcx"},
           {"citadel", "TZTCAS2.pcx"},
           {"castle", "TZTCAS3.pcx"},
           {"villageHall", "TZTHAL1.pcx"},
           {"townHall", "TZTHAL2.pcx"},
           {"cityHall", "TZTHAL3.pcx"},
           {"capitol", "TZTHAL4.pcx"},
           {"marketplace", "TZTMRK.pcx"},
           {"resourceSilo", "TZTMRKS.pcx"},
           {"blacksmith", "TZTBLKA.pcx"},
           {"special1", "TZTMRKA.pcx"},
           {"special2", "TZTCASW.pcx"},
           {"special3", "TZTGLDL.pcx"},
           {"special4", "TZTGLDW.pcx"},
           {"horde1", "TZTGAR1H.pcx"},
           {"horde1Upgr", "TZTGAR2H.pcx"},
           {"grail", "TZTHOLYA.pcx"},
           {"dwellingLvl1", "TZTGRM1A.pcx"},
           {"dwellingLvl2", "TZTGAR1.pcx"},
           {"dwellingLvl3", "TZTGOL1A.pcx"},
           {"dwellingLvl4", "TZTMAG1.pcx"},
           {"dwellingLvl5", "TZTGEN1.pcx"},
           {"dwellingLvl6", "TZTNAG1.pcx"},
           {"dwellingLvl7", "TZTTIT1.pcx"},
           {"dwellingUpLvl1", "TZTGRM2A.pcx"},
           {"dwellingUpLvl2", "TZTGAR2.pcx"},
           {"dwellingUpLvl3", "TZTGOL2A.pcx"},
           {"dwellingUpLvl4", "TZTMAG2.pcx"},
           {"dwellingUpLvl5", "TZTGEN2.pcx"},
           {"dwellingUpLvl6", "TZTNAG2.pcx"},
           {"dwellingUpLvl7", "TZTTIT2.pcx"}},
          {// 3 (Inferno)
           {"mageGuild1", "TZIMAG1A.pcx"},
           {"mageGuild2", "TZIMAG2A.pcx"},
           {"mageGuild3", "TZIMAG3A.pcx"},
           {"mageGuild4", "TZIMAG4A.pcx"},
           {"mageGuild5", "TZIMAG5A.pcx"},
           {"tavern", "TZITAV.pcx"},
           {"fort", "TZICAS2A.pcx"},
           {"citadel", "TZICAS1A.pcx"},
           {"castle", "TZICAS3A.pcx"},
           {"villageHall", "TZIHAL1.pcx"},
           {"townHall", "TZIHAL2.pcx"},
           {"cityHall", "TZIHAL3.pcx"},
           {"capitol", "TZIHAL4.pcx"},
           {"marketplace", "TZIMAR1.pcx"},
           {"resourceSilo", "TZIMAR2.pcx"},
           {"blacksmith", "TZIBLKA.pcx"},
           {"special2", "TZICAB1A.pcx"},
           {"special3", "TZICASGA.pcx"},
           {"special4", "TZIPAIN.pcx"},
           {"horde1", "TZIMP1HA.pcx"},
           {"horde1Upgr", "TZIMP2HA.pcx"},
           {"horde2", "TZIHND1H.pcx"},
           {"horde2Upgr", "TZIHND2H.pcx"},
           {"grail", "TZIHOLY.pcx"},
           {"dwellingLvl1", "TZIMP1A.pcx"},
           {"dwellingLvl2", "TZIGOG1A.pcx"},
           {"dwellingLvl3", "TZIHND1.pcx"},
           {"dwellingLvl4", "TZIDMN1.pcx"},
           {"dwellingLvl5", "TZIPIT1.pcx"},
           {"dwellingLvl6", "TZIEFR1.pcx"},
           {"dwellingLvl7", "TZIDVL1.pcx"},
           {"dwellingUpLvl1", "TZIMP2A.pcx"},
           {"dwellingUpLvl2", "TZIGOG2A.pcx"},
           {"dwellingUpLvl3", "TZIHND2.pcx"},
           {"dwellingUpLvl4", "TZIDMN2.pcx"},
           {"dwellingUpLvl5", "TZIPIT2.pcx"},
           {"dwellingUpLvl6", "TZIEFR2.pcx"},
           {"dwellingUpLvl7", "TZIDVL2.pcx"}},
          {{"mageGuild1", "TZNMAG1.pcx"},
           {"mageGuild2", "TZNMAG2.pcx"},
           {"mageGuild3", "TZNMAG3.pcx"},
           {"mageGuild4", "TZNMAG4.pcx"},
           {"mageGuild5", "TZNMAG5.pcx"},
           {"tavern", "TZNTAV.pcx"},
           {"shipyard", "TZNSHPBA.pcx"},
           {"fort", "TZNCAS1.pcx"},
           {"citadel", "TZNCAS2.pcx"},
           {"castle", "TZNCAS3.pcx"},
           {"villageHall", "TZNHAL1.pcx"},
           {"townHall", "TZNHAL2.pcx"},
           {"cityHall", "TZNHAL3.pcx"},
           {"capitol", "TZNHAL4.pcx"},
           {"marketplace", "TZNMRK1.pcx"},
           {"resourceSilo", "TZNMRK2.pcx"},
           {"blacksmith", "TZNSMITA.pcx"},
           {"special1", "TZNSHRDA.pcx"},
           {"horde1", "TZNSKE1H.pcx"},
           {"horde1Upgr", "TZNSKE2H.pcx"},
           {"ship", "TZNSHPNA.pcx"},
           {"special2", "TZNNECRA.pcx"},
           {"special3", "TZNSKELT.pcx"},
           {"grail", "TZNHOLYA.pcx"},
           {"dwellingLvl1", "TZNSKEL1.pcx"},
           {"dwellingLvl2", "TZNZOMB1.pcx"},
           {"dwellingLvl3", "TZNWIGH1.pcx"},
           {"dwellingLvl4", "TZNVAM1.pcx"},
           {"dwellingLvl5", "TZNLICH1.pcx"},
           {"dwellingLvl6", "TZNBKN1.pcx"},
           {"dwellingLvl7", "TZNBON1.pcx"},
           {"dwellingUpLvl1", "TZNSKEL2.pcx"},
           {"dwellingUpLvl2", "TZNZOMB2.pcx"},
           {"dwellingUpLvl3", "TZNWIGH2.pcx"},
           {"dwellingUpLvl4", "TZNVAM2.pcx"},
           {"dwellingUpLvl5", "TZNLICH2.pcx"},
           {"dwellingUpLvl6", "TZNBKN2.pcx"},
           {"dwellingUpLvl7", "TZNBON2.pcx"}},
          {{"mageGuild1", "TZDMAG1.pcx"},
           {"mageGuild2", "TZDMAG2.pcx"},
           {"mageGuild3", "TZDMAG3.pcx"},
           {"mageGuild4", "TZDMAG4.pcx"},
           {"mageGuild5", "TZDMAG5.pcx"},
           {"tavern", "TZDTAV.pcx"},
           {"fort", "TZDCAS1.pcx"},
           {"citadel", "TZDCAS2.pcx"},
           {"castle", "TZDCAS3.pcx"},
           {"villageHall", "TZDHALL1.pcx"},
           {"townHall", "TZDHALL2.pcx"},
           {"cityHall", "TZDHALL3.pcx"},
           {"capitol", "TZDHALL4.pcx"},
           {"marketplace", "TZDMARK.pcx"},
           {"resourceSilo", "TZDSILO.pcx"},
           {"blacksmith", "TZDSMITH.pcx"},
           {"special1", "TZDART.pcx"},
           {"horde1", "TZDTR1HA.pcx"},
           {"horde1Upgr", "TZDTR2HA.pcx"},
           {"special2", "TZDVOR1A.pcx"},
           {"special3", "TZDPORTA.pcx"},
           {"special4", "TZDACAD.pcx"},
           {"grail", "TZDHOLY.pcx"},
           {"dwellingLvl1", "TZDTRG1A.pcx"},
           {"dwellingLvl2", "TZDHAR1.pcx"},
           {"dwellingLvl3", "TZDBEH1A.pcx"},
           {"dwellingLvl4", "TZDMED1.pcx"},
           {"dwellingLvl5", "TZDMIN1.pcx"},
           {"dwellingLvl6", "TZDMAN1.pcx"},
           {"dwellingLvl7", "TZDDRA1A.pcx"},
           {"dwellingUpLvl1", "TZDTRG2A.pcx"},
           {"dwellingUpLvl2", "TZDHAR2.pcx"},
           {"dwellingUpLvl3", "TZDBEH2A.pcx"},
           {"dwellingUpLvl4", "TZDMED2.pcx"},
           {"dwellingUpLvl5", "TZDMIN2.pcx"},
           {"dwellingUpLvl6", "TZDMAN2.pcx"},
           {"dwellingUpLvl7", "TZDDRA2A.pcx"}},
          {{"mageGuild1", "TZSMAG1.pcx"},
           {"mageGuild2", "TZSMAG2.pcx"},
           {"mageGuild3", "TZSMAG3.pcx"},
           {"tavern", "TZSTAV.pcx"},
           {"fort", "TZSCA1.pcx"},
           {"citadel", "TZSCA2.pcx"},
           {"castle", "TZSCA3.pcx"},
           {"villageHall", "TZSHAL1A.pcx"},
           {"townHall", "TZSHAL2A.pcx"},
           {"cityHall", "TZSHAL3A.pcx"},
           {"capitol", "TZSHAL4A.pcx"},
           {"marketplace", "TZSMRK1.pcx"},
           {"resourceSilo", "TZSMRK2.pcx"},
           {"blacksmith", "TZSBLK1.pcx"},
           {"special1", "TZSCA1EA.pcx"},
           {"horde1", "TZSGOB1H.pcx"},
           {"horde1Upgr", "TZSGOB2H.pcx"},
           {"special2", "TZSMRK1C.pcx"},
           {"special3", "TZSBLK2.pcx"},
           {"special4", "TZSVAH.pcx"},
           {"grail", "TZSHOLYA.pcx"},
           {"dwellingLvl1", "TZSGOB1.pcx"},
           {"dwellingLvl2", "TZSWOL1.pcx"},
           {"dwellingLvl3", "TZSORC1.pcx"},
           {"dwellingLvl4", "TZSOGR1.pcx"},
           {"dwellingLvl5", "TZSROC1.pcx"},
           {"dwellingLvl6", "TZSCYC1.pcx"},
           {"dwellingLvl7", "TZSBEH1A.pcx"},
           {"dwellingUpLvl1", "TZSGOB2.pcx"},
           {"dwellingUpLvl2", "TZSWOL2.pcx"},
           {"dwellingUpLvl3", "TZSORC2.pcx"},
           {"dwellingUpLvl4", "TZSOGR2.pcx"},
           {"dwellingUpLvl5", "TZSROC2.pcx"},
           {"dwellingUpLvl6", "TZSCYC2A.pcx"},
           {"dwellingUpLvl7", "TZSBEH2A.pcx"}},
          {// 7 (Fortress)
           {"mageGuild1", "TZFMAG1A.pcx"},
           {"mageGuild2", "TZFMAG2A.pcx"},
           {"mageGuild3", "TZFMAG3A.pcx"},
           {"tavern", "TZFTAVA.pcx"},
           {"shipyard", "TZFDCK2.pcx"},
           {"fort", "TZFCAS1.pcx"},
           {"citadel", "TZFCAS2.pcx"},
           {"castle", "TZFCAS3.pcx"},
           {"villageHall", "TZFHAL1.pcx"},
           {"townHall", "TZFHAL2.pcx"},
           {"cityHall", "TZFHAL3.pcx"},
           {"capitol", "TZFHAL4.pcx"},
           {"marketplace", "TZFMRKAA.pcx"},
           {"resourceSilo", "TZFMRK2A.pcx"},
           {"blacksmith", "TZFAIDA.pcx"},
           {"special1", "TZFCAGE.pcx"},
           {"horde1", "TZFGNL1H.pcx"},
           {"horde1Upgr", "TZFGNL2H.pcx"},
           {"ship", "TZFDCK1.pcx"},
           {"special2", "TZFCASD.pcx"},
           {"special3", "TZFCASA.pcx"},
           {"grail", "TZFHLYAA.pcx"},
           {"dwellingLvl1", "TZFGNL1.pcx"},
           {"dwellingLvl2", "TZFLIZ1.pcx"},
           {"dwellingLvl3", "TZFFLY1A.pcx"},
           {"dwellingLvl4", "TZFBAS1.pcx"},
           {"dwellingLvl5", "TZFGOR1.pcx"},
           {"dwellingLvl6", "TZFWYV1.pcx"},
           {"dwellingLvl7", "TZFHYD1A.pcx"},
           {"dwellingUpLvl1", "TZFGNL2.pcx"},
           {"dwellingUpLvl2", "TZFLIZ2.pcx"},
           {"dwellingUpLvl3", "TZFFLY2A.pcx"},
           {"dwellingUpLvl4", "TZFBAS2.pcx"},
           {"dwellingUpLvl5", "TZFGOR2.pcx"},
           {"dwellingUpLvl6", "TZFWYV2.pcx"},
           {"dwellingUpLvl7", "TZFHYD2A.pcx"}},
  };

  const static inline std::unordered_set<std::string> townDefaultAni[] = {
      {"extraAnimation"},
      {"extraAnimation"},
      {},
      {},
      {"extraAnimation"},
      {},
      {},
      {"extraAnimation"}};

  const static inline std::unordered_map<std::string, SDL_Point> townPoint[] = {
      {
          {"extraAnimation", {46, 119}}, //
          {"mageGuild1", {707, 166}},
          {"mageGuild2", {706, 135}},
          {"mageGuild3", {704, 107}},
          {"mageGuild4", {704, 76}},
          {"tavern", {0, 230}},
          {"shipyard", {478, 134}},
          {"fort", {595, 66}},
          {"citadel", {478, 66}},
          {"castle", {478, 37}},
          {"villageHall", {0, 209}},
          {"townHall", {0, 176}},
          {"cityHall", {0, 164}},
          {"capitol", {0, 154}},
          {"marketplace", {413, 264}},
          {"resourceSilo", {488, 228}},
          {"blacksmith", {213, 251}},
          {"special1", {533, 71}},
          {"horde1", {76, 53}},
          {"horde1Upgr", {76, 35}},
          {"ship", {478, 134}},
          {"special2", {384, 193}},
          {"special3", {0, 198}},
          {"grail", {456, 109}},
          {"dwellingLvl1", {304, 92}},
          {"dwellingLvl2", {360, 130}},
          {"dwellingLvl3", {76, 57}},
          {"dwellingLvl4", {176, 101}},
          {"dwellingLvl5", {563, 211}},
          {"dwellingLvl6", {174, 190}},
          {"dwellingLvl7", {303, 0}},
          {"dwellingUpLvl1", {304, 65}},
          {"dwellingUpLvl2", {360, 115}},
          {"dwellingUpLvl3", {76, 35}},
          {"dwellingUpLvl4", {176, 85}},
          {"dwellingUpLvl5", {563, 173}},
          {"dwellingUpLvl6", {160, 190}},
          {"dwellingUpLvl7", {303, 0}},
      },
      {
          // 1
          {"extraAnimation", {327, 236}},
          {"mageGuild1", {454, 200}},
          {"mageGuild2", {438, 178}},
          {"mageGuild3", {418, 153}},
          {"mageGuild4", {406, 129}},
          {"mageGuild5", {384, 104}},
          {"tavern", {181, 229}},
          {"fort", {63, 25}},
          {"citadel", {79, 18}},
          {"castle", {79, 18}},
          {"villageHall", {565, 216}},
          {"townHall", {538, 187}},
          {"cityHall", {538, 187}},
          {"capitol", {534, 187}},
          {"marketplace", {129, 301}},
          {"resourceSilo", {245, 324}},
          {"blacksmith", {558, 105}},
          {"special1", {555, 297}},
          {"special2", {555, 297}},
          {"special3", {0, 181}},
          {"grail", {0, 54}},
          {"extraTownHall", {293, 235}},
          {"extraCityHall", {295, 191}},
          {"extraCapitol", {260, 171}},
          {"horde1", {0, 154}},
          {"horde1Upgr", {0, 143}},
          {"horde2", {47, 142}},
          {"horde2Upgr", {47, 142}},
          {"dwellingLvl1", {0, 236}},
          {"dwellingLvl2", {0, 154}},
          {"dwellingLvl3", {668, 101}},
          {"dwellingLvl4", {287, 73}},
          {"dwellingLvl5", {68, 146}},
          {"dwellingLvl6", {362, 90}},
          {"dwellingLvl7", {502, 27}},
          {"dwellingUpLvl1", {0, 236}},
          {"dwellingUpLvl2", {0, 143}},
          {"dwellingUpLvl3", {665, 101}},
          {"dwellingUpLvl4", {287, 28}},
          {"dwellingUpLvl5", {63, 146}},
          {"dwellingUpLvl6", {362, 90}},
          {"dwellingUpLvl7", {502, 5}},
      },
      {
          // 2 (Tower)
          {"mageGuild1", {597, 82}},
          {"mageGuild2", {593, 65}},
          {"mageGuild3", {593, 48}},
          {"mageGuild4", {593, 31}},
          {"mageGuild5", {593, 14}},
          {"tavern", {375, 278}},
          {"fort", {304, 0}},
          {"citadel", {301, 0}},
          {"castle", {301, 0}},
          {"villageHall", {0, 259}},
          {"townHall", {0, 220}},
          {"cityHall", {0, 82}},
          {"capitol", {0, 82}},
          {"marketplace", {614, 292}},
          {"resourceSilo", {763, 214}},
          {"blacksmith", {478, 211}},
          {"special1", {674, 276}},
          {"special2", {409, 82}},
          {"special3", {702, 115}},
          {"special4", {592, 189}},
          {"grail", {237, 14}},
          {"horde1", {0, 47}},
          {"horde1Upgr", {0, 28}},
          {"dwellingLvl1", {453, 221}},
          {"dwellingLvl2", {4, 46}},
          {"dwellingLvl3", {209, 177}},
          {"dwellingLvl4", {613, 95}},
          {"dwellingLvl5", {511, 75}},
          {"dwellingLvl6", {681, 208}},
          {"dwellingLvl7", {75, 144}},
          {"dwellingUpLvl1", {446, 221}},
          {"dwellingUpLvl2", {4, 28}},
          {"dwellingUpLvl3", {209, 177}},
          {"dwellingUpLvl4", {613, 74}},
          {"dwellingUpLvl5", {511, 8}},
          {"dwellingUpLvl6", {681, 157}},
          {"dwellingUpLvl7", {75, 91}},
      },
      {// 3 (Inferno)
       {"mageGuild1", {667, 127}},
       {"mageGuild2", {667, 101}},
       {"mageGuild3", {667, 83}},
       {"mageGuild4", {667, 56}},
       {"mageGuild5", {667, 35}},
       {"tavern", {105, 219}},
       {"fort", {222, 44}},
       {"citadel", {222, 44}},
       {"castle", {222, 18}},
       {"villageHall", {0, 174}},
       {"townHall", {0, 174}},
       {"cityHall", {0, 174}},
       {"capitol", {0, 131}},
       {"marketplace", {511, 301}},
       {"resourceSilo", {497, 337}},
       {"blacksmith", {684, 253}},
       {"special2", {297, 0}},
       {"special3", {227, 174}},
       {"special4", {593, 104}},
       {"horde1", {614, 256}},
       {"horde1Upgr", {614, 221}},
       {"horde2", {10, 301}},
       {"horde2Upgr", {9, 273}},
       {"grail", {24, 10}},
       {"dwellingLvl1", {614, 256}},
       {"dwellingLvl2", {187, 248}},
       {"dwellingLvl3", {9, 325}},
       {"dwellingLvl4", {414, 204}},
       {"dwellingLvl5", {359, 296}},
       {"dwellingLvl6", {220, 350}},
       {"dwellingLvl7", {420, 153}},
       {"dwellingUpLvl1", {614, 221}},
       {"dwellingUpLvl2", {187, 212}},
       {"dwellingUpLvl3", {9, 273}},
       {"dwellingUpLvl4", {412, 197}},
       {"dwellingUpLvl5", {359, 244}},
       {"dwellingUpLvl6", {220, 282}},
       {"dwellingUpLvl7", {420, 105}}},
      {{"extraAnimation", {25, 279}},
       {"mageGuild1", {341, 116}},
       {"mageGuild2", {341, 97}},
       {"mageGuild3", {341, 78}},
       {"mageGuild4", {340, 62}},
       {"mageGuild5", {343, 35}},
       {"tavern", {508, 189}},
       {"shipyard", {617, 265}},
       {"fort", {138, 66}},
       {"citadel", {139, 66}},
       {"castle", {34, 18}},
       {"villageHall", {468, 76}},
       {"townHall", {482, 56}},
       {"cityHall", {478, 26}},
       {"capitol", {481, 26}},
       {"marketplace", {347, 215}},
       {"resourceSilo", {276, 185}},
       {"blacksmith", {382, 252}},
       {"special1", {18, 0}},
       {"horde1", {80, 222}},
       {"horde1Upgr", {64, 222}},
       {"ship", {617, 265}},
       {"special2", {307, 61}},
       {"special3", {247, 275}},
       {"grail", {410, 88}},
       {"extraTownHall", {0, 241}},
       {"extraCityHall", {321, 255}},
       {"extraCapitol", {475, 257}},
       {"dwellingLvl1", {80, 222}},
       {"dwellingLvl2", {502, 223}},
       {"dwellingLvl3", {0, 187}},
       {"dwellingLvl4", {607, 212}},
       {"dwellingLvl5", {206, 207}},
       {"dwellingLvl6", {0, 31}},
       {"dwellingLvl7", {663, 25}},
       {"dwellingUpLvl1", {64, 222}},
       {"dwellingUpLvl2", {498, 224}},
       {"dwellingUpLvl3", {0, 179}},
       {"dwellingUpLvl4", {615, 193}},
       {"dwellingUpLvl5", {222, 171}},
       {"dwellingUpLvl6", {0, 30}},
       {"dwellingUpLvl7", {662, 23}}},
      {{"mageGuild1", {164, 119}},
       {"mageGuild2", {164, 97}},
       {"mageGuild3", {164, 77}},
       {"mageGuild4", {164, 61}},
       {"mageGuild5", {164, 15}},
       {"tavern", {211, 297}},
       {"fort", {363, 87}},
       {"citadel", {363, 87}},
       {"castle", {363, 87}},
       {"villageHall", {0, 234}},
       {"townHall", {0, 223}},
       {"cityHall", {0, 223}},
       {"capitol", {0, 203}},
       {"marketplace", {590, 318}},
       {"resourceSilo", {624, 335}},
       {"blacksmith", {544, 248}},
       {"special1", {746, 294}},
       {"horde1", {0, 326}},
       {"horde1Upgr", {0, 300}},
       {"special2", {131, 26}},
       {"special3", {687, 177}},
       {"special4", {313, 298}},
       {"grail", {562, 24}},
       {"dwellingLvl1", {0, 326}},
       {"dwellingLvl2", {0, 26}},
       {"dwellingLvl3", {118, 308}},
       {"dwellingLvl4", {300, 29}},
       {"dwellingLvl5", {551, 186}},
       {"dwellingLvl6", {270, 253}},
       {"dwellingLvl7", {550, 0}},
       {"dwellingUpLvl1", {0, 300}},
       {"dwellingUpLvl2", {0, 26}},
       {"dwellingUpLvl3", {118, 256}},
       {"dwellingUpLvl4", {300, 29}},
       {"dwellingUpLvl5", {519, 172}},
       {"dwellingUpLvl6", {270, 253}},
       {"dwellingUpLvl7", {550, 0}}},
      {{"extraAnimation", {23, 20}},   {"mageGuild1", {473, 67}},
       {"mageGuild2", {473, 37}},      {"mageGuild3", {473, 1}},
       {"tavern", {170, 280}},         {"fort", {402, 148}},
       {"citadel", {402, 114}},        {"castle", {402, 114}},
       {"villageHall", {0, 259}},      {"townHall", {0, 225}},
       {"cityHall", {0, 201}},         {"capitol", {0, 148}},
       {"marketplace", {397, 308}},    {"resourceSilo", {458, 248}},
       {"blacksmith", {660, 286}},     {"special1", {550, 229}},
       {"horde1", {373, 239}},         {"horde1Upgr", {373, 220}},
       {"special2", {473, 282}},       {"special3", {617, 286}},
       {"special4", {313, 13}},        {"grail", {321, 105}},
       {"dwellingLvl1", {373, 239}},   {"dwellingLvl2", {266, 246}},
       {"dwellingLvl3", {566, 232}},   {"dwellingLvl4", {197, 204}},
       {"dwellingLvl5", {137, 30}},    {"dwellingLvl6", {622, 160}},
       {"dwellingLvl7", {604, 0}},     {"dwellingUpLvl1", {373, 220}},
       {"dwellingUpLvl2", {266, 225}}, {"dwellingUpLvl3", {566, 158}},
       {"dwellingUpLvl4", {197, 137}}, {"dwellingUpLvl5", {129, 15}},
       {"dwellingUpLvl6", {616, 93}},  {"dwellingUpLvl7", {604, 0}}},
      {// 7 (Fortress)
       {"extraAnimation", {372, 227}}, {"mageGuild1", {0, 200}},
       {"mageGuild2", {0, 177}},       {"mageGuild3", {0, 135}},
       {"tavern", {634, 219}},         {"shipyard", {197, 294}},
       {"fort", {368, 118}},           {"citadel", {368, 98}},
       {"castle", {368, 55}},          {"villageHall", {166, 128}},
       {"townHall", {166, 97}},        {"cityHall", {166, 51}},
       {"capitol", {166, 2}},          {"marketplace", {382, 219}},
       {"resourceSilo", {448, 210}},   {"blacksmith", {360, 160}},
       {"special1", {703, 36}},        {"horde1", {641, 121}},
       {"horde1Upgr", {641, 68}},      {"ship", {197, 294}},
       {"special2", {341, 174}},       {"special3", {349, 79}},
       {"grail", {468, 260}},          {"extraCapitol", {320, 141}},
       {"dwellingLvl1", {641, 168}},   {"dwellingLvl2", {141, 178}},
       {"dwellingLvl3", {192, 85}},    {"dwellingLvl4", {0, 292}},
       {"dwellingLvl5", {15, 127}},    {"dwellingLvl6", {0, 4}},
       {"dwellingLvl7", {612, 291}},   {"dwellingUpLvl1", {641, 107}},
       {"dwellingUpLvl2", {125, 163}}, {"dwellingUpLvl3", {159, 19}},
       {"dwellingUpLvl4", {0, 257}},   {"dwellingUpLvl5", {15, 69}},
       {"dwellingUpLvl6", {0, 4}},     {"dwellingUpLvl7", {587, 263}}},

  };

  const static inline std::vector<std::string> townZ[] = {
      {"grail",          "fort",           "citadel",        "castle",
       "special1",       "shipyard",       "ship",           "special2",
       "dwellingLvl7",   "dwellingUpLvl7", "horde1",         "horde1Upgr",
       "dwellingLvl1",   "dwellingLvl3",   "dwellingLvl6",   "dwellingUpLvl1",
       "dwellingUpLvl3", "dwellingUpLvl6", "marketplace",    "blacksmith",
       "dwellingLvl2",   "dwellingLvl4",   "dwellingUpLvl2", "dwellingUpLvl4",
       "extraAnimation", "mageGuild1",     "mageGuild2",     "mageGuild3",
       "mageGuild4",     "villageHall",    "townHall",       "cityHall",
       "capitol",        "resourceSilo",   "dwellingLvl5",   "dwellingUpLvl5",
       "tavern",         "special3"},
      //    1
      {"dwellingLvl7",   "dwellingUpLvl7", "fort",           "citadel",
       "castle",         "blacksmith",     "grail",          "horde1",
       "horde1Upgr",     "dwellingLvl2",   "dwellingUpLvl2", "dwellingLvl6",
       "dwellingUpLvl6", "mageGuild1",     "mageGuild2",     "mageGuild3",
       "mageGuild4",     "mageGuild5",     "horde2",         "horde2Upgr",
       "dwellingLvl5",   "dwellingUpLvl5", "dwellingLvl3",   "dwellingUpLvl3",
       "dwellingLvl4",   "dwellingUpLvl4", "special3",       "tavern",
       "extraAnimation", "special1",       "special2",       "dwellingLvl1",
       "dwellingUpLvl1", "extraTownHall",  "marketplace",    "extraCapitol",
       "resourceSilo"},
      //    2
      {"grail",          "fort",           "citadel",        "castle",
       "dwellingLvl7",   "dwellingUpLvl7", "special1",       "special4",
       "tavern",         "dwellingLvl1",   "dwellingLvl3",   "dwellingUpLvl1",
       "dwellingUpLvl3", "dwellingLvl6",   "dwellingUpLvl6", "resourceSilo",
       "mageGuild1",     "mageGuild2",     "mageGuild3",     "mageGuild4",
       "mageGuild5",     "villageHall",    "townHall",       "cityHall",
       "capitol",        "marketplace",    "blacksmith",     "dwellingLvl2",
       "dwellingLvl4",   "dwellingUpLvl2", "dwellingUpLvl4", "dwellingLvl5",
       "dwellingUpLvl5", "special2",       "special3",       "horde1",
       "horde1Upgr"},
      {"special2",       "dwellingLvl7",   "dwellingUpLvl7", "fort",
       "citadel",        "castle",         "special3",       "grail",
       "dwellingLvl4",   "dwellingUpLvl4", "dwellingLvl5",   "dwellingUpLvl5",
       "dwellingLvl2",   "dwellingUpLvl2", "marketplace",    "dwellingLvl6",
       "dwellingUpLvl6", "resourceSilo",   "tavern",         "blacksmith",
       "horde1",         "horde1Upgr",     "horde2",         "horde2Upgr",
       "dwellingLvl1",   "dwellingLvl3",   "dwellingUpLvl1", "dwellingUpLvl3",
       "mageGuild1",     "mageGuild2",     "mageGuild3",     "mageGuild4",
       "mageGuild5",     "villageHall",    "townHall",       "cityHall",
       "capitol",        "special4"},
      {"dwellingLvl3",   "dwellingUpLvl3", "extraAnimation", "special1",
       "mageGuild1",     "mageGuild2",     "mageGuild3",     "mageGuild4",
       "mageGuild5",     "shipyard",       "ship",           "special2",
       "villageHall",    "townHall",       "cityHall",       "capitol",
       "dwellingLvl6",   "dwellingUpLvl6", "resourceSilo",   "dwellingLvl2",
       "dwellingUpLvl2", "dwellingLvl4",   "dwellingUpLvl4", "marketplace",
       "dwellingLvl5",   "dwellingUpLvl5", "special3",       "horde1",
       "horde1Upgr",     "dwellingLvl1",   "dwellingUpLvl1", "extraTownHall",
       "extraCityHall",  "extraCapitol",   "blacksmith",     "fort",
       "citadel",        "castle",         "tavern",         "grail",
       "dwellingLvl7",   "dwellingUpLvl7"},
      {"blacksmith",     "dwellingLvl4",   "dwellingUpLvl4", "dwellingLvl6",
       "dwellingUpLvl6", "dwellingLvl7",   "dwellingUpLvl7", "mageGuild1",
       "mageGuild2",     "mageGuild3",     "mageGuild4",     "mageGuild5",
       "marketplace",    "special1",       "dwellingLvl3",   "dwellingUpLvl3",
       "dwellingLvl5",   "dwellingUpLvl5", "grail",          "resourceSilo",
       "fort",           "citadel",        "castle",         "horde1",
       "horde1Upgr",     "dwellingLvl1",   "dwellingUpLvl1", "tavern",
       "villageHall",    "townHall",       "cityHall",       "capitol",
       "special2",       "special3",       "special4",       "dwellingLvl2",
       "dwellingUpLvl2"},
      {"dwellingLvl6",   "dwellingUpLvl6", "mageGuild1",     "mageGuild2",
       "mageGuild3",     "special4",       "fort",           "citadel",
       "castle",         "dwellingLvl5",   "dwellingUpLvl5", "marketplace",
       "special1",       "dwellingLvl2",   "dwellingUpLvl2", "dwellingLvl3",
       "dwellingUpLvl3", "resourceSilo",   "special3",       "tavern",
       "grail",          "special2",       "horde1",         "horde1Upgr",
       "dwellingLvl1",   "dwellingUpLvl1", "villageHall",    "townHall",
       "cityHall",       "capitol",        "blacksmith",     "dwellingLvl4",
       "dwellingUpLvl4", "dwellingLvl7",   "dwellingUpLvl7", "extraAnimation"},
      {"special3",       "castle",         "citadel",        "fort",
       "dwellingLvl5",   "dwellingUpLvl5", "special2",       "shipyard",
       "ship",           "dwellingLvl1",   "dwellingUpLvl1", "horde1",
       "dwellingLvl4",   "dwellingUpLvl4", "blacksmith",     "extraCapitol",
       "tavern",         "villageHall",    "townHall",       "cityHall",
       "capitol",        "marketplace",    "grail",          "dwellingLvl7",
       "dwellingUpLvl7", "extraAnimation", "mageGuild1",     "mageGuild2",
       "mageGuild3",     "dwellingLvl2",   "dwellingUpLvl2", "dwellingLvl3",
       "dwellingUpLvl3", "dwellingLvl6",   "dwellingUpLvl6", "horde1Upgr",
       "special1",       "resourceSilo"}

  };

  const static inline std::unordered_map<uint8_t, std::string> townIndex = {
      {0, "townHall"},        {1, "cityHall"},
      {2, "capitol"},         {3, "fort"},
      {4, "citadel"},         {5, "castle"},
      {6, "tavern"},          {7, "blacksmith"},
      {8, "marketplace"},     {9, "resourceSilo"},
      {11, "mageGuild1"},     {12, "mageGuild2"},
      {13, "mageGuild3"},     {14, "mageGuild4"},
      {15, "mageGuild5"},     {16, "shipyard"},
      {17, "grail"},          {22, "dwellingLvl1"},
      {23, "dwellingUpLvl1"}, {24, "horde1"},
      {25, "dwellingLvl2"},   {26, "dwellingUpLvl2"},
      {27, "horde2"},         {28, "dwellingLvl3"},
      {29, "dwellingUpLvl3"}, {30, "horde3"},
      {31, "dwellingLvl4"},   {32, "dwellingUpLvl4"},
      {33, "horde4"},         {34, "dwellingLvl5"},
      {35, "dwellingUpLvl5"}, {36, "horde5"},
      {37, "dwellingLvl6"},   {38, "dwellingUpLvl6"},
      {39, "dwellingLvl7"},   {40, "dwellingUpLvl7"},
      {255, "villageHall"},
  };

  const static inline std::unordered_map<uint8_t, std::string>
      townSpecialIndex[] = {
          // castle - 索引0
          {{18, "special1"}, {20, "special2"}, {19, "special3"}},
          // rampart - 索引1
          {{18, "special1"}, {19, "special2"}, {20, "special3"}},
          // tower - 索引2
          {{10, "special1"},
           {20, "special2"},
           {18, "special3"},
           {19, "special4"}},
          // inferno - 索引3
          {{18, "special2"}, {19, "special3"}, {20, "special4"}},
          // necropolis - 索引4
          {{18, "special1"}, {19, "special2"}, {20, "special3"}},
          // dungeon - 索引5
          {{10, "special1"},
           {18, "special2"},
           {19, "special3"},
           {20, "special4"}},
          // stronghold - 索引6
          {{18, "special1"},
           {19, "special2"},
           {20, "special3"},
           {21, "special4"}},
          // fortress - 索引7
          {{20, "special1"}, {19, "special2"}, {18, "special3"}},
  };
};