#pragma once

#include <cstdint>
struct Enum {
  enum class DWEINCTYPE : uint8_t {
    BASE,
    BUILD,
    ARTIFACT,
  };

  enum class GAMESET : uint8_t {
    MY_HERO_SPEED,
    OTHER_HERO_SPEED,
    MAP_SPEED,
    ANIMATE_EFFECT,
    MUSIC1,
    MUSIC2,
    HERO_TIP,
    QUICK_BATTLE,
    ANIMATE_TEXT,
    BUILD_FADE,
    MAP_MSG,
    BACK_MUSIC,
  };

  enum class MARKET : uint8_t {
    RES_BUY,
    RES_SEND,
    ART_BUY,
    ART_SELL,
    CRE_SELL,
  };

  enum class ALTAR : uint8_t {
    ART,
    CRE,
    SKE, // 骷髅转换场
  };

  enum class CURSOR : uint8_t {
    ADVENTURE, // set of various cursors for adventure map
    COMBAT,    // set of various cursors for combat
    DEFAULT,   // default arrow and hourglass cursors
    SPELL,     // animated cursor for spellcasting
    FADE,      // animated cursor for spellcasting
    HIDE       // hide
  };
  enum class CRADVNTR : uint8_t {
    POINTER = 0,
    HOURGLASS = 1,
    HERO = 2,
    TOWN = 3,
    T1_MOVE = 4,
    T1_ATTACK = 5,
    T1_SAIL = 6,
    T1_DISEMBARK = 7,
    T1_EXCHANGE = 8,
    T1_VISIT = 9,
    T2_MOVE = 10,
    T2_ATTACK = 11,
    T2_SAIL = 12,
    T2_DISEMBARK = 13,
    T2_EXCHANGE = 14,
    T2_VISIT = 15,
    T3_MOVE = 16,
    T3_ATTACK = 17,
    T3_SAIL = 18,
    T3_DISEMBARK = 19,
    T3_EXCHANGE = 20,
    T3_VISIT = 21,
    T4_MOVE = 22,
    T4_ATTACK = 23,
    T4_SAIL = 24,
    T4_DISEMBARK = 25,
    T4_EXCHANGE = 26,
    T4_VISIT = 27,
    T1_SAIL_VISIT = 28,
    T2_SAIL_VISIT = 29,
    T3_SAIL_VISIT = 30,
    T4_SAIL_VISIT = 31,
    SCROLL_NORTH = 32,
    SCROLL_NORTHEAST = 33,
    SCROLL_EAST = 34,
    SCROLL_SOUTHEAST = 35,
    SCROLL_SOUTH = 36,
    SCROLL_SOUTHWEST = 37,
    SCROLL_WEST = 38,
    SCROLL_NORTHWEST = 39,
    // POINTER_COPY       = 40, // probably unused
    TELEPORT = 41,
    SCUTTLE_BOAT = 42,
  };
  enum class ADAG : uint8_t {
    UP = 9,
    UPRIGHT = 10,
    RIGHT = 11,
    DOWNRIGHT = 12,
    DOWN = 13,
    DOWNLEFT = 14,
    LEFT = 15,
    UPLEFT = 16,
  };

  enum RESTYPE : uint8_t {
    CRYSTAL = 0,
    GEM = 1,
    MERCURY = 2,
    ORE = 3,
    SULFUR = 4,
    WOOD = 5,
    GOLD = 6,

    // 随机资源
    RAMDOM_RESOURCE
  };

  enum class SCNTYPE : uint8_t {
    MOD,
    POP,
  };

  enum class CRETYPE : uint8_t {
    POP_HERO,
    POP_DWE,
    POP_BAT,
    MOD_HERO,
    MOD_DWE,
    MOD_BAT,
  };

  enum class CLICKTYPE : uint8_t {
    L_UP,
    L_DOWN,
    R_UP,
    R_DOWN,
  };

  enum class LANG : uint8_t {
    ENGLISH,
    CHINESE,
  };

  enum FACTION : uint8_t {
    FACTION_CASTLE,
    FACTION_RAMPART,
    FACTION_TOWER,
    FACTION_INFERNO,
    FACTION_NECROPOLIS,
    FACTION_DUNGEON,
    FACTION_STRONGHOLD,
    FACTION_FORTRESS,
    FACTION_CONFLUX,
    FACTION_NEUTRAL,
  };

  enum CREATURE : uint16_t {
    // 城堡
    PIKEMAN = 0,
    HALBERDIER = 1,
    ARCHER = 2,
    MARKSMAN = 3,
    GRIFFIN = 4,
    ROYAL_GRIFFIN = 5,
    SWORDSMAN = 6,
    CRUSADER = 7,
    MONK = 8,
    ZEALOT = 9,
    CAVALIER = 10,
    CHAMPION = 11,
    ANGEL = 12,
    ARCHANGEL = 13,

    // 壁垒
    CENTAUR = 14,
    CENTAUR_CAPTAIN = 15,
    DWARF = 16,
    BATTLE_DWARF = 17,
    WOOD_ELF = 18,
    GRAND_ELF = 19,
    PEGASUS = 20,
    SILVER_PEGASUS = 21,
    DENDROID_GUARD = 22,
    DENDROID_SOLDIER = 23,
    UNICORN = 24,
    WAR_UNICORN = 25,
    GREEN_DRAGON = 26,
    GOLD_DRAGON = 27,

    // 塔楼
    GREMLIN = 28,
    MASTER_GREMLIN = 29,
    STONE_GARGOYLE = 30,
    OBSIDIAN_GARGOYLE = 31,
    STONE_GOLEM = 32,
    IRON_GOLEM = 33,
    MAGE = 34,
    ARCH_MAGE = 35,
    GENIE = 36,
    MASTER_GENIE = 37,
    NAGA = 38,
    NAGA_QUEEN = 39,
    GIANT = 40,
    TITAN = 41,

    // 地狱
    IMP = 42,
    FAMILIAR = 43,
    GOG = 44,
    MAGOG = 45,
    HELL_HOUND = 46,
    CERBERUS = 47,
    DEMON = 48,
    HORNED_DEMON = 49,
    PIT_FIEND = 50,
    PIT_LORD = 51,
    EFREETI = 52,
    EFREET_SULTAN = 53,
    DEVIL = 54,
    ARCH_DEVIL = 55,

    // 墓园
    SKELETON = 56,
    SKELETON_WARRIOR = 57,
    WALKING_DEAD = 58,
    ZOMBIE = 59,
    WIGHT = 60,
    WRAITH = 61,
    VAMPIRE = 62,
    VAMPIRE_LORD = 63,
    LICH = 64,
    POWER_LICH = 65,
    BLACK_KNIGHT = 66,
    DREAD_KNIGHT = 67,
    BONE_DRAGON = 68,
    GHOST_DRAGON = 69,

    // 地牢
    TROGLODYTE = 70,
    INFERNAL_TROGLODYTE = 71,
    HARPY = 72,
    HARPY_HAG = 73,
    BEHOLDER = 74,
    EVIL_EYE = 75,
    MEDUSA = 76,
    MEDUSA_QUEEN = 77,
    MINOTAUR = 78,
    MINOTAUR_KING = 79,
    MANTICORE = 80,
    SCORPICORE = 81,
    RED_DRAGON = 82,
    BLACK_DRAGON = 83,

    // 据点
    GOBLIN = 84,
    HOBGOBLIN = 85,
    WOLF_RIDER = 86,
    WOLF_RAIDER = 87,
    ORC = 88,
    ORC_CHIEFTAIN = 89,
    OGRE = 90,
    OGRE_MAGE = 91,
    ROC = 92,
    THUNDERBIRD = 93,
    CYCLOPS = 94,
    CYCLOPS_KING = 95,
    BEHEMOTH = 96,
    ANCIENT_BEHEMOTH = 97,

    // 要塞
    GNOLL = 98,
    GNOLL_MARAUDER = 99,
    LIZARDMAN = 100,
    LIZARD_WARRIOR = 101,
    GORGON = 102,
    MIGHTY_GORGON = 103,
    SERPENT_FLY = 104,
    DRAGON_FLY = 105,
    BASILISK = 106,
    GREATER_BASILISK = 107,
    WYVERN = 108,
    WYVERN_MONARCH = 109,
    HYDRA = 110,
    CHAOS_HYDRA = 111,

    // 元素生物1
    AIR_ELEMENTAL = 112,
    EARTH_ELEMENTAL = 113,
    FIRE_ELEMENTAL = 114,
    WATER_ELEMENTAL = 115,
    GOLD_GOLEM = 116,
    DIAMOND_GOLEM = 117,

    // 元素生物2
    PIXIE = 118,
    SPRITE = 119,
    PSYCHIC_ELEMENTAL = 120,
    MAGIC_ELEMENTAL = 121,
    NOT_USED_1 = 122,
    ICE_ELEMENTAL = 123,
    NOT_USED_2 = 124,
    MAGMA_ELEMENTAL = 125,
    NOT_USED_3 = 126,
    STORM_ELEMENTAL = 127,
    NOT_USED_4 = 128,
    ENERGY_ELEMENTAL = 129,
    FIREBIRD = 130,
    PHOENIX = 131,

    // 特殊生物1
    AZURE_DRAGON = 132,
    CRYSTAL_DRAGON = 133,
    FAERIE_DRAGON = 134,
    RUST_DRAGON = 135,
    ENCHANTER = 136,
    SHARPSHOOTER = 137,
    HALFLING = 138,
    PEASANT = 139,
    BOAR = 140,
    MUMMY = 141,
    NOMAD = 142,
    ROGUE = 143,
    TROLL = 144,

    // 战争机器
    CATAPULT = 145,
    BALLISTA = 146,
    FIRST_AID_TENT = 147,
    AMMO_CART = 148,
    ARROW_TOWER = 149,
  };

  enum CREATURE_EX_ATTRIBUTE {
    // 基本类型属性
    SHOOTING_ARMY,         // 远程部队
    FLYING_ARMY,           // 飞行部队
    DOUBLE_WIDE,           // 2格兵种
    IS_UNDEAD,             // 丧尸
    MAGIC_RESISTANCE,      // 魔法抵抗
    DRAGON,                // 龙
    DRAGON_TWO_HEX_ATTACK, // 龙息

    // 特殊能力属性
    const_no_melee_penalty,     // 无近战惩罚
    const_two_attacks,          // 攻击两次
    const_two_distance_attacks, // 攻击两次(远程)
    const_free_attack,          // 不被反击
    const_jousting,             // 冲锋加成（杀伤力可增大）
    const_raises_morale,        // 提升士气
    const_lowers_morale,        // 降低士气
    const_no_wall_penalty,      // 无城墙惩罚
    const_two_retaliation,      // 两次反击
    const_three_retaliation,    // 三次反击(反戈一击+两次反击)
    const_unlimit_retaliation,  // 无限反击次数
    const_spell,                // 生物可以释放魔法
    const_spell_after_attack,   // 攻击后释放魔法
    const_spell_after_hit,      // 被攻击后产生的魔法
    const_hate,                 // 死敌属性
    const_enemy_spell_cost,     //  增加(减少)敌方魔法消耗

    // 兵种等级属性
    KING_1, // 7级生物（龙、比蒙、九头怪等）
    KING_2, // 天使/恶魔级别
    KING_3, // 巨人/泰坦级别

    // 魔法免疫属性
    IMMUNE_TO_MIND_SPELLS, // 免疫心智魔法
    IMMUNE_TO_FIRE_SPELLS, // 免疫火系魔法
    IMMUNE_TO_CAVALRY,     // 免疫骑兵冲锋
    IMMUNE_TO_LEVEL,       // 免疫魔法等级

    // 攻城属性
    CATAPULT_ATTACK, // 攻击城墙

    // 攻击方式属性
    MULTI_HEADED,        // 多头攻击（攻击多个敌人）
    HAS_EXTENDED_ATTACK, // 扩展攻击范围
  };

  enum HERO_CLASS : uint8_t {
    HERO_CLASS_KNIGHT = 0,
    HERO_CLASS_CLERIC = 1,
    HERO_CLASS_RANGER = 2,
    HERO_CLASS_DRUID = 3,
    HERO_CLASS_ALCHEMIST = 4,
    HERO_CLASS_WIZARD = 5,
    HERO_CLASS_DEMON = 6,
    HERO_CLASS_HERETIC = 7,
    HERO_CLASS_DEATH_KNIGHT = 8,
    HERO_CLASS_NECROMANCER = 9,
    HERO_CLASS_OVERLORD = 10,
    HERO_CLASS_WARLOCK = 11,
    HERO_CLASS_BARBARIAN = 12,
    HERO_CLASS_BATTLE_MAGE = 13,
    HERO_CLASS_BEASTMASTER = 14,
    HERO_CLASS_WITCH = 15,
    HERO_CLASS_ELEMENTALIST = 16,
    HERO_CLASS_PLANESWALKER = 17,
  };

  enum SECOND_SKILL : uint8_t {
    PATHFINDING = 0,
    ARCHERY = 1,
    LOGISTICS = 2,
    SCOUTING = 3,
    DIPLOMACY = 4,
    NAVIGATION = 5,
    LEADERSHIP = 6,
    WISDOM = 7,
    MYSTICISM = 8,
    LUCK = 9,
    BALLISTICS = 10,
    EAGLE_EYE = 11,
    NECROMANCY = 12,
    ESTATES = 13,
    FIRE_MAGIC = 14,
    AIR_MAGIC = 15,
    WATER_MAGIC = 16,
    EARTH_MAGIC = 17,
    SCHOLAR = 18,
    TACTICS = 19,
    ARTILLERY = 20,
    LEARNING = 21,
    OFFENCE = 22,
    ARMORER = 23,
    INTELLIGENCE = 24,
    SORCERY = 25,
    RESISTANCE = 26,
    FIRST_AID = 27
  };

  enum SECOND_SKILL_LEVEL : uint8_t { BASIC = 0, ADVANCED = 1, EXPERT = 2 };

  enum HERO_SPECIAL : uint8_t {
    // 技能类特长
    SPECIAL_SECONDARY_SKILL, // 对应二级技能 (如：archery, armorer, logistics等)
    SPECIAL_SPECIFIC_SPELL,
    // 生物类特长
    SPECIAL_CREATURE, // 特定生物增强

    // 属性类特长
    SPECIAL_PRIMARY_SKILL,            // 主要属性 (攻击、防御)
    SPECIAL_GENERAL_DAMAGE_PREMY,     // 通用伤害加成
    SPECIAL_GENERAL_DAMAGE_REDUCTION, // 通用伤害减免
    SPECIAL_STACKS_SPEED,             // 部队速度

    // 资源类特长
    SPECIAL_GENERATE_RESOURCE, // 资源生成 (gold, mercury, sulfur等)
    // 特殊类特长
    SPECIAL_SPECIAL_UPGRADE, // 特殊升级 (如：archer升级为sharpshooter)
  };

  enum SPELL : uint8_t {
    // Adventure map spells
    SUMMON_BOAT = 0,
    SCUTTLE_BOAT = 1,
    VISIONS = 2,
    VIEW_EARTH = 3,
    DISGUISE = 4,
    VIEW_AIR = 5,
    FLY = 6,
    WATER_WALK = 7,
    DIMENSION_DOOR = 8,
    TOWN_PORTAL = 9,

    // Combat spells
    QUICKSAND = 10,
    LAND_MINE = 11,
    FORCE_FIELD = 12,
    FIRE_WALL = 13,
    EARTHQUAKE = 14,
    MAGIC_ARROW = 15,
    ICE_BOLT = 16,
    LIGHTNING_BOLT = 17,
    IMPLOSION = 18,
    CHAIN_LIGHTNING = 19,
    FROST_RING = 20,
    FIREBALL = 21,
    INFERNO = 22,
    METEOR_SHOWER = 23,
    DEATH_RIPPLE = 24,
    DESTROY_UNDEAD = 25,
    ARMAGEDDON = 26,
    SHIELD = 27,
    AIR_SHIELD = 28,
    FIRE_SHIELD = 29,
    PROTECTION_FROM_AIR = 30,
    PROTECTION_FROM_FIRE = 31,
    PROTECTION_FROM_WATER = 32,
    PROTECTION_FROM_EARTH = 33,
    ANTI_MAGIC = 34,
    DISPEL = 35,
    MAGIC_MIRROR = 36,
    CURE = 37,
    RESURRECTION = 38,
    ANIMATE_DEAD = 39,
    SACRIFICE = 40,
    BLESS = 41,
    CURSE = 42,
    BLOODLUST = 43,
    PRECISION = 44,
    WEAKNESS = 45,
    STONE_SKIN = 46,
    DISRUPTING_RAY = 47,
    PRAYER = 48,
    MIRTH = 49,
    SORROW = 50,
    FORTUNE = 51,
    MISFORTUNE = 52,
    HASTE = 53,
    SLOW = 54,
    SLAYER = 55,
    FRENZY = 56,
    TITANS_LIGHTNING_BOLT = 57,
    COUNTERSTRIKE = 58,
    BERSERK = 59,
    HYPNOTIZE = 60,
    FORGETFULNESS = 61,
    BLIND = 62,
    TELEPORT = 63,
    REMOVE_OBSTACLE = 64,
    CLONE = 65,
    SUMMON_FIRE_ELEMENTAL = 66,
    SUMMON_EARTH_ELEMENTAL = 67,
    SUMMON_WATER_ELEMENTAL = 68,
    SUMMON_AIR_ELEMENTAL = 69,
    // Creature abilities
    STONE_GAZE = 70,
    POISON = 71,
    BIND = 72,
    DISEASE = 73,
    PARALYZE = 74,
    AGE = 75,
    DEATH_CLOUD = 76,
    THUNDERBOLT = 77,
    DISPEL_HELPFUL_SPELLS = 78,
    DEATH_STARE = 79,
    ACID_BREATH_DEFENSE = 80,
    ACID_BREATH_DAMAGE = 81,
  };

  enum BUILD : int32_t {
    // 通用建筑
    BUILD_VILLAGE_HALL = -1,
    BUILD_TOWN_HALL = 0,
    BUILD_CITY_HALL = 1,
    BUILD_CAPITOL = 2,
    BUILD_FORT = 3,
    BUILD_CITADEL = 4,
    BUILD_CASTLE = 5,
    BUILD_TAVERN = 6,
    BUILD_BLACKSMITH = 7,
    BUILD_MARKETPLACE = 8,
    BUILD_RESOURCE_SILO = 9,

    BUILD_SPECIAL_10 = 10,
    // 魔法行会
    BUILD_MAGE_GUILD_1 = 11,
    BUILD_MAGE_GUILD_2 = 12,
    BUILD_MAGE_GUILD_3 = 13,
    BUILD_MAGE_GUILD_4 = 14,
    BUILD_MAGE_GUILD_5 = 15,

    BUILD_SHIPYARD = 16,
    BUILD_GRAIL = 17,

    // 特殊建筑编号（根据城镇不同而意义不同）
    BUILD_SPECIAL_18 = 18,
    BUILD_SPECIAL_19 = 19,
    BUILD_SPECIAL_20 = 20,
    BUILD_SPECIAL_21 = 21,

    // 生物巢穴
    BUILD_DWELLING_LEVEL_1 = 22,
    BUILD_DWELLING_UPGRADE_LEVEL_1 = 23,
    BUILD_HORDE_1 = 24,
    BUILD_DWELLING_LEVEL_2 = 25,
    BUILD_DWELLING_UPGRADE_LEVEL_2 = 26,
    BUILD_HORDE_2 = 27,
    BUILD_DWELLING_LEVEL_3 = 28,
    BUILD_DWELLING_UPGRADE_LEVEL_3 = 29,
    BUILD_HORDE_3 = 30,
    BUILD_DWELLING_LEVEL_4 = 31,
    BUILD_DWELLING_UPGRADE_LEVEL_4 = 32,
    BUILD_HORDE_4 = 33,
    BUILD_DWELLING_LEVEL_5 = 34,
    BUILD_DWELLING_UPGRADE_LEVEL_5 = 35,
    BUILD_HORDE_5 = 36,
    BUILD_DWELLING_LEVEL_6 = 37,
    BUILD_DWELLING_UPGRADE_LEVEL_6 = 38,
    BUILD_DWELLING_LEVEL_7 = 39,
    BUILD_DWELLING_UPGRADE_LEVEL_7 = 40,
    // 额外的建筑,补充
    BUILD_SHIP,
    BUILD_HORDE_UPGRADE_1,
    BUILD_HORDE_UPGRADE_2,
    BUILD_HORDE_UPGRADE_3,
    BUILD_HORDE_UPGRADE_4,
    BUILD_HORDE_UPGRADE_5,

    // 一些额外的动画
    BUILD_EXTRA_ANIMATE_1,
    BUILD_EXTRA_ANIMATE_2,
    BUILD_EXTRA_ANIMATE_3,
  };

  enum BUILD_BONUS : uint8_t {
    CREATURE_GROWTH,
    CREATURE_GROWTH_RATE,
    TOWN_BATTLE_MORALE_RAISE,
    TOWN_BATTLE_LUCK_RAISE,
    TOWN_BATTLE_ESCAPE,
    TOWN_BATTLE_SIEGE,
    RESTORE_MANA,
    HERO_PRIMAYRY_SKILL,
    HERO_SECOND_SKILL,
    HERO_MOVENT_LAND,
    HERO_MOVENT_SEA,
    HERO_MANA,
  };

  enum ARTIFACT_BONUS_TYPE {
    // 主要技能
    ARTIFACT_PRIMARY_SKILL,

    // 士气和幸运
    ARTIFACT_MORALE,
    ARTIFACT_LUCK,

    // 视野
    ARTIFACT_SIGHT_RADIUS,

    // 亡灵相关
    ARTIFACT_UNDEAD_RAISE_PERCENTAGE,

    // 魔法抗性
    ARTIFACT_MAGIC_RESISTANCE,

    // 伤害加成,远程
    ARTIFACT_PERCENTAGE_DAMAGE_BOOST_RANGED,
    // 伤害加成,远程
    ARTIFACT_PERCENTAGE_DAMAGE_BOOST_MELEE,
    // 伤害加成,通用
    ARTIFACT_PERCENTAGE_DAMAGE_BOOST,

    // 战斗法术学习
    ARTIFACT_LEARN_BATTLE_SPELL_CHANCE,

    // 投降折扣
    ARTIFACT_SURRENDER_DISCOUNT,

    // 速度相关
    ARTIFACT_STACKS_SPEED,

    // 移动力
    ARTIFACT_MOVEMENT_SEA,
    ARTIFACT_MOVEMENT_LAND,
    ARTIFACT_FLYING_MOVEMENT,
    ARTIFACT_WATER_WALKING,

    // 法力相关
    ARTIFACT_MANA_REGENERATION,
    ARTIFACT_FULL_MANA_REGENERATION,

    // 法术相关
    ARTIFACT_SPELL_DURATION,
    ARTIFACT_SPELL_DAMAGE,
    ARTIFACT_SPELLS_OF_SCHOOL,
    ARTIFACT_SPELLS_OF_LEVEL,
    ARTIFACT_SPELL_IMMUNITY,
    ARTIFACT_LEVEL_SPELL_IMMUNITY,
    ARTIFACT_BLOCK_MAGIC_ABOVE,
    ARTIFACT_BLOCK_ALL_MAGIC,
    ARTIFACT_NEGATE_ALL_NATURAL_IMMUNITIES,
    ARTIFACT_SPELL_RESISTANCE_AURA,

    // 单位属性
    ARTIFACT_STACK_HEALTH,
    ARTIFACT_HP_REGENERATION,

    // 资源生成
    ARTIFACT_GENERATE_RESOURCE,

    // 生物增长
    ARTIFACT_CREATURE_GROWTH,
    ARTIFACT_CREATURE_GROWTH_PERCENT,

    // 战斗相关
    ARTIFACT_NO_DISTANCE_PENALTY,
    ARTIFACT_NO_WALL_PENALTY,
    ARTIFACT_FREE_SHOOTING,
    ARTIFACT_BATTLE_NO_FLEEING,
    ARTIFACT_WHIRLPOOL_PROTECTION,
    ARTIFACT_FREE_SHIP_BOARDING,

    // 法术
    ARTIFACT_SPELL,
    ARTIFACT_OPENING_BATTLE_SPELL,

    // 阵营相关
    ARTIFACT_NONEVIL_ALIGNMENT_MIX,

    // 亡灵巫术
    ARTIFACT_IMPROVED_NECROMANCY,

    // 心智免疫
    ARTIFACT_MIND_IMMUNITY,
  };

  enum ARTIFACT_SLOT : uint8_t {
    HEAD,
    SHOULDERS,
    NECK,
    RIGHT_HAND,
    LEFT_HAND,
    TORSO,
    RIGHT_RING,
    LEFT_RING,
    FEET,
    MISC1,
    MISC2,
    MISC3,
    MISC4,
    MACH1,
    MACH2,
    MACH3,
    MACH4,
    SPELLBOOK,
    MISC5,
  };

  enum PRIMARY_SKILL_TYPE {
    PRIMARY_SKILL_ATTACK,
    PRIMARY_SKILL_DEFENCE,
    PRIMARY_SKILL_SPELLPOWER,
    PRIMARY_SKILL_KNOWLEDGE,
  };

  enum ARTIFACT_ID {
    // Basic artifacts (0-6)
    ARTIFACT_SPELL_BOOK = 0,
    ARTIFACT_SPELL_SCROLL = 1,
    ARTIFACT_GRAIL = 2,
    ARTIFACT_CATAPULT = 3,
    ARTIFACT_BALLISTA = 4,
    ARTIFACT_AMMO_CART = 5,
    ARTIFACT_FIRST_AID_TENT = 6,

    // Weapons - Attack (7-12)
    ARTIFACT_CENTAUR_AXE = 7,
    ARTIFACT_BLACKSHARD_OF_THE_DEAD_KNIGHT = 8,
    ARTIFACT_GREATER_GNOLDS_FLAIL = 9,
    ARTIFACT_OGRES_CLUB_OF_HAVOC = 10,
    ARTIFACT_SWORD_OF_HELLFIRE = 11,
    ARTIFACT_TITANS_GLADIUS = 12,

    // Shields - Defence (13-18)
    ARTIFACT_SHIELD_OF_THE_DWARVEN_LORDS = 13,
    ARTIFACT_SHIELD_OF_THE_YAWNING_DEAD = 14,
    ARTIFACT_BUCKLER_OF_THE_GNOLF_KING = 15,
    ARTIFACT_TARG_OF_THE_RAMPAGING_OGRE = 16,
    ARTIFACT_SHIELD_OF_THE_DAMNED = 17,
    ARTIFACT_SENTINELS_SHIELD = 18,

    // Helmets - Knowledge (19-24)
    ARTIFACT_HELM_OF_THE_ALABASTER_UNICORN = 19,
    ARTIFACT_SKULL_HELMET = 20,
    ARTIFACT_HELM_OF_CHAOS = 21,
    ARTIFACT_CROWN_OF_THE_SUPREME_MAGI = 22,
    ARTIFACT_HELLSTORM_HELMET = 23,
    ARTIFACT_THUNDER_HELMET = 24,

    // Armor - Spell Power (25-30)
    ARTIFACT_BREASTPLATE_OF_PETRIFIED_WOOD = 25,
    ARTIFACT_RIB_CAGE = 26,
    ARTIFACT_SCALES_OF_THE_GREATER_BASILISK = 27,
    ARTIFACT_TUNIC_OF_THE_CYCLOPS_KING = 28,
    ARTIFACT_BREASTPLATE_OF_BRIMSTONE = 29,
    ARTIFACT_TITANS_CUIRASS = 30,

    // Combined artifact components - All stats (31-36)
    ARTIFACT_ARMOR_OF_WONDER = 31,
    ARTIFACT_SANDALS_OF_THE_SAINT = 32,
    ARTIFACT_CELESTIAL_NECKLACE_OF_BLISS = 33,
    ARTIFACT_LIONS_SHIELD_OF_COURAGE = 34,
    ARTIFACT_SWORD_OF_JUDGEMENT = 35,
    ARTIFACT_HELM_OF_HEAVENLY_ENLIGHTENMENT = 36,

    // Dragon series (37-45)
    ARTIFACT_QUIET_EYE_OF_THE_DRAGON = 37,
    ARTIFACT_RED_DRAGON_FLAME_TONGUE = 38,
    ARTIFACT_DRAGON_SCALE_SHIELD = 39,
    ARTIFACT_DRAGON_SCALE_ARMOR = 40,
    ARTIFACT_DRAGONBONE_GREAVES = 41,
    ARTIFACT_DRAGON_WING_TABARD = 42,
    ARTIFACT_NECKLACE_OF_DRAGONTEETH = 43,
    ARTIFACT_CROWN_OF_DRAGONTOOTH = 44,
    ARTIFACT_STILL_EYE_OF_THE_DRAGON = 45,

    // Luck artifacts (46-48)
    ARTIFACT_CLOVER_OF_FORTUNE = 46,
    ARTIFACT_CARDS_OF_PROPHECY = 47,
    ARTIFACT_LADYBIRD_OF_LUCK = 48,

    // Morale artifacts (49-51)
    ARTIFACT_BADGE_OF_COURAGE = 49,
    ARTIFACT_CREST_OF_VALOR = 50,
    ARTIFACT_GLYPH_OF_GALLANTRY = 51,

    // Sight radius artifacts (52-53)
    ARTIFACT_SPECULUM = 52,
    ARTIFACT_SPYGLASS = 53,

    // Necromancy artifacts (54-56)
    ARTIFACT_AMULET_OF_THE_UNDERTAKER = 54,
    ARTIFACT_VAMPIRES_COWL = 55,
    ARTIFACT_DEAD_MANS_BOOTS = 56,

    // Magic resistance artifacts (57-59)
    ARTIFACT_GARNITURE_OF_INTERFERENCE = 57,
    ARTIFACT_SURCOAT_OF_COUNTERPOISE = 58,
    ARTIFACT_BOOTS_OF_POLARITY = 59,

    // Archery artifacts (60-62)
    ARTIFACT_BOW_OF_ELVEN_CHERRYWOOD = 60,
    ARTIFACT_BOWSTRING_OF_THE_UNICORNS_MANE = 61,
    ARTIFACT_ANGEL_FEATHER_ARROWS = 62,

    // Battle spell learning artifacts (63-65)
    ARTIFACT_BIRD_OF_PERCEPTION = 63,
    ARTIFACT_STOIC_WATCHMAN = 64,
    ARTIFACT_EMBLEM_OF_COGNIZANCE = 65,

    // Surrender discount artifacts (66-68)
    ARTIFACT_STATESMANS_MEDAL = 66,
    ARTIFACT_DIPLOMATS_RING = 67,
    ARTIFACT_AMBASSADORS_SASH = 68,

    // Movement artifacts (69-72)
    ARTIFACT_RING_OF_THE_WAYFARER = 69,
    ARTIFACT_EQUESTRIANS_GLOVES = 70,
    ARTIFACT_NECKLACE_OF_OCEAN_GUIDANCE = 71,
    ARTIFACT_ANGEL_WINGS = 72,

    // Mana regeneration artifacts (73-75)
    ARTIFACT_CHARM_OF_MANA = 73,
    ARTIFACT_TALISMAN_OF_MANA = 74,
    ARTIFACT_MYSTIC_ORB_OF_MANA = 75,

    // Spell duration artifacts (76-78)
    ARTIFACT_COLLAR_OF_CONJURING = 76,
    ARTIFACT_RING_OF_CONJURING = 77,
    ARTIFACT_CAPE_OF_CONJURING = 78,

    // Spell damage artifacts (79-82)
    ARTIFACT_ORB_OF_THE_FIRMAMENT = 79,
    ARTIFACT_ORB_OF_SILT = 80,
    ARTIFACT_ORB_OF_TEMPESTUOUS_FIRE = 81,
    ARTIFACT_ORB_OF_DRIVING_RAIN = 82,

    // Special magic artifacts (83-93)
    ARTIFACT_RECANTERS_CLOAK = 83,
    ARTIFACT_SPIRIT_OF_OPPRESSION = 84,
    ARTIFACT_HOURGLASS_OF_THE_EVIL_HOUR = 85,
    ARTIFACT_TOME_OF_FIRE_MAGIC = 86,
    ARTIFACT_TOME_OF_AIR_MAGIC = 87,
    ARTIFACT_TOME_OF_WATER_MAGIC = 88,
    ARTIFACT_TOME_OF_EARTH_MAGIC = 89,
    ARTIFACT_BOOTS_OF_LEVITATION = 90,
    ARTIFACT_GOLDEN_BOW = 91,
    ARTIFACT_SPHERE_OF_PERMANENCE = 92,
    ARTIFACT_ORB_OF_VULNERABILITY = 93,

    // Health artifacts (94-96)
    ARTIFACT_RING_OF_VITALITY = 94,
    ARTIFACT_RING_OF_LIFE = 95,
    ARTIFACT_VIAL_OF_LIFEBLOOD = 96,

    // Speed artifacts (97-99)
    ARTIFACT_NECKLACE_OF_SWIFTNESS = 97,
    ARTIFACT_BOOTS_OF_SPEED = 98,
    ARTIFACT_CAPE_OF_VELOCITY = 99,

    // Pendants - Spell immunity (100-108)
    ARTIFACT_PENDANT_OF_DISPASSION = 100,
    ARTIFACT_PENDANT_OF_SECOND_SIGHT = 101,
    ARTIFACT_PENDANT_OF_HOLINESS = 102,
    ARTIFACT_PENDANT_OF_LIFE = 103,
    ARTIFACT_PENDANT_OF_DEATH = 104,
    ARTIFACT_PENDANT_OF_FREE_WILL = 105,
    ARTIFACT_PENDANT_OF_NEGATIVITY = 106,
    ARTIFACT_PENDANT_OF_TOTAL_RECALL = 107,
    ARTIFACT_PENDANT_OF_COURAGE = 108,

    // Resource generation artifacts (109-117)
    ARTIFACT_EVERFLOWING_CRYSTAL_CLOAK = 109,
    ARTIFACT_RING_OF_INFINITE_GEMS = 110,
    ARTIFACT_EVERPOURING_VIAL_OF_MERCURY = 111,
    ARTIFACT_INEXHAUSTIBLE_CART_OF_ORE = 112,
    ARTIFACT_EVERSMOKING_RING_OF_SULFUR = 113,
    ARTIFACT_INEXHAUSTIBLE_CART_OF_LUMBER = 114,
    ARTIFACT_ENDLESS_SACK_OF_GOLD = 115,
    ARTIFACT_ENDLESS_BAG_OF_GOLD = 116,
    ARTIFACT_ENDLESS_PURSE_OF_GOLD = 117,

    // Legion series (118-122)
    ARTIFACT_LEGS_OF_LEGION = 118,
    ARTIFACT_LOINS_OF_LEGION = 119,
    ARTIFACT_TORSO_OF_LEGION = 120,
    ARTIFACT_ARMS_OF_LEGION = 121,
    ARTIFACT_HEAD_OF_LEGION = 122,

    // Hats (123-124)
    ARTIFACT_SEA_CAPTAINS_HAT = 123,
    ARTIFACT_SPELLBINDERS_HAT = 124,

    // Special artifacts (125-140)
    ARTIFACT_SHACKLES_OF_WAR = 125,
    ARTIFACT_ORB_OF_INHIBITION = 126,
    ARTIFACT_VIAL_OF_DRAGON_BLOOD = 127,
    ARTIFACT_ARMAGEDDONS_BLADE = 128,
    ARTIFACT_ANGELIC_ALLIANCE = 129,
    ARTIFACT_CLOAK_OF_THE_UNDEAD_KING = 130,
    ARTIFACT_ELIXIR_OF_LIFE = 131,
    ARTIFACT_ARMOR_OF_THE_DAMNED = 132,
    ARTIFACT_STATUE_OF_LEGION = 133,
    ARTIFACT_POWER_OF_THE_DRAGON_FATHER = 134,
    ARTIFACT_TITANS_THUNDER = 135,
    ARTIFACT_ADMIRALS_HAT = 136,
    ARTIFACT_BOW_OF_THE_SHARPSHOOTER = 137,
    ARTIFACT_WIZARDS_WELL = 138,
    ARTIFACT_RING_OF_THE_MAGI = 139,
    ARTIFACT_CORNUCOPIA = 140,

    // Unused artifacts (141-143)
    ARTIFACT_UNUSED_1 = 141,
    ARTIFACT_UNUSED_2 = 142,
    ARTIFACT_UNUSED_3 = 143,
  };

  enum SPELL_SCHOOL {
    SPELL_SCHOOL_AIR,
    SPELL_SCHOOL_FIRE,
    SPELL_SCHOOL_WATER,
    SPELL_SCHOOL_EARTH,
  };

  enum BATTLE_FIELD {
    BATTLE_FIELD_SAND_SHORE,
    BATTLE_FIELD_SAND_MESAS,
    BATTLE_FIELD_DIRT_BIRCHES,
    BATTLE_FIELD_DIRT_HILLS,
    BATTLE_FIELD_DIRT_PINES,
    BATTLE_FIELD_GRASS_HILLS,
    BATTLE_FIELD_GRASS_PINES,
    BATTLE_FIELD_LAVA,
    BATTLE_FIELD_MAGIC_PLAINS,
    BATTLE_FIELD_SNOW_MOUNTAINS,
    BATTLE_FIELD_SNOW_TREES,
    BATTLE_FIELD_SUBTERRANEAN,
    BATTLE_FIELD_SWAMP_TREES,
    BATTLE_FIELD_FIERY_FIELDS,
    BATTLE_FIELD_ROCKLANDS,
    BATTLE_FIELD_MAGIC_CLOUDS,
    BATTLE_FIELD_LUCID_POOLS,
    BATTLE_FIELD_HOLY_GROUND,
    BATTLE_FIELD_CLOVER_FIELD,
    BATTLE_FIELD_EVIL_FOG,
    BATTLE_FIELD_CURSED_GROUND,
    BATTLE_FIELD_ROUGH,
    BATTLE_FIELD_SHIP_TO_SHIP,
    BATTLE_FIELD_SHIP
  };

  enum  TERRAIN {
    TERRAIN_DIRT,
    TERRAIN_SAND,
    TERRAIN_GRASS,
    TERRAIN_SNOW,
    TERRAIN_SWAMP,
    TERRAIN_ROUGH,
    TERRAIN_SUBTERRA,
    TERRAIN_LAVA,
    TERRAIN_WATER,
    TERRAIN_ROCK
};
};
